// scripts/ingest-nis2-cybersakerhetslagen.ts
// Cybersakerhetslagen (Swedish NIS2 transposition) + associated MSB/PTS/FI guidance
// Authority: MSB (primary), multiple sector authorities

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'nis2-cybersakerhetslagen.json');

const controls = [
  // -- Styrning och ansvarighet (Governance and accountability) --
  { control_number: 'NIS2-1', title: 'Management body responsibility for cybersecurity', title_nl: 'Ledningens ansvar for cybersakerhet', description: 'Management bodies of essential and important entities shall approve cybersecurity risk management measures and oversee their implementation.', description_nl: 'Ledningsorgan for vasentliga och viktiga verksamhetsutovare ska godkanna riskhanteringsatgarder for cybersakerhet och overvaka genomforandet.', category: 'Styrning', subcategory: 'Ledningsansvar', level: 'Lag', iso_mapping: '5.1', implementation_guidance: 'Forankra cybersakerhet pa styrelseniva. Styrelsen ska godkanna riskhanteringsatgarder och ta ansvar for bristande efterlevnad.', verification_guidance: 'Kontrollera att styrelsen har godkant cybersakerhetsatgarder och overvakar genomforandet.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-2', title: 'Cybersecurity training for management', title_nl: 'Cybersakerhetsutbildning for ledningen', description: 'Members of management bodies shall undergo regular cybersecurity training.', description_nl: 'Ledamorer i ledningsorgan ska genomga regelbunden cybersakerhetsutbildning.', category: 'Styrning', subcategory: 'Utbildning', level: 'Lag', iso_mapping: '6.3', implementation_guidance: 'Sakerstall att styrelseledamoter och ledande befattningshavare genomgar cybersakerhetsutbildning minst arligen.', verification_guidance: 'Kontrollera att utbildning genomforts och dokumenterats.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-3', title: 'Cybersecurity risk management policy', title_nl: 'Policy for hantering av cybersakerhetsrisker', description: 'An all-hazards cybersecurity risk management policy shall be established covering network and information systems.', description_nl: 'En policy for allomfattande hantering av cybersakerhetsrisker ska uppratttas som omfattar natverk och informationssystem.', category: 'Styrning', subcategory: 'Policy', level: 'Lag', iso_mapping: '5.1', implementation_guidance: 'Uppractta en cybersakerhetspolicy som omfattar alla hot. Inkludera riskbedomning, atgarder och uppfoljning.', verification_guidance: 'Kontrollera att cybersakerhetspolicy ar upprattad och godkand.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },

  // -- Riskhanteringsatgarder (Risk management measures - Article 21) --
  { control_number: 'NIS2-4', title: 'Risk analysis and information system security policies', title_nl: 'Riskanalys och sakerhhetspolicyer for informationssystem', description: 'Risk analyses and security policies for information systems shall be established and maintained.', description_nl: 'Riskanalyser och sakerhetspolicyer for informationssystem ska uppratttas och underhallas.', category: 'Riskhanteringsatgarder', subcategory: 'Riskanalys', level: 'Lag', iso_mapping: '5.1', implementation_guidance: 'Genomfor riskanalyser for alla natverks- och informationssystem. Uppractta policyer som behandlar identifierade risker.', verification_guidance: 'Kontrollera att riskanalyser ar genomforda och att policyer ar aktuella.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-5', title: 'Incident handling', title_nl: 'Incidenthantering', description: 'Procedures for incident prevention, detection, and response shall be established.', description_nl: 'Rutiner for incidentforebyggande, detektering och hantering ska uppratttas.', category: 'Riskhanteringsatgarder', subcategory: 'Incidenthantering', level: 'Lag', iso_mapping: '5.24', implementation_guidance: 'Uppractta incidenthanteringsrutiner med forebyggande, detekterande och reagerande atgarder. Testa regelbundet.', verification_guidance: 'Kontrollera att incidenthanteringsrutiner ar upprattade och testade.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-6', title: 'Business continuity and crisis management', title_nl: 'Driftkontinuitet och krishantering', description: 'Business continuity plans including backup management and crisis management shall be established.', description_nl: 'Driftkontinuitetsplaner inklusive sakerhetskopieringshantering och krishantering ska uppratttas.', category: 'Riskhanteringsatgarder', subcategory: 'Kontinuitet', level: 'Lag', iso_mapping: '5.29', implementation_guidance: 'Uppractta driftkontinuitetsplaner, sakerhetskopiieringsrutiner och krishanteringsplaner. Ovraa minst arligen.', verification_guidance: 'Kontrollera att kontinuitetsplaner och krishanteringsrutiner finns och ar testade.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-7', title: 'Supply chain security', title_nl: 'Leveranskedjesakerhet', description: 'Security aspects of relationships with direct suppliers and service providers shall be addressed.', description_nl: 'Sakerhetsaspekter av relationer med direkta leverantorer och tjansteleverantorer ska hanteras.', category: 'Riskhanteringsatgarder', subcategory: 'Leveranskedja', level: 'Lag', iso_mapping: '5.19', implementation_guidance: 'Beddomma leverantorsrisker. Inkludera sakerhetskrav i leverantorsavtal. Overvaka leverantorernas cybersakerhet.', verification_guidance: 'Kontrollera att leverantorssakerhet hanteras systematiskt.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-8', title: 'Security in network and system acquisition, development, and maintenance', title_nl: 'Sakerhet vid anskaffning, utveckling och underhall', description: 'Security shall be integrated in the acquisition, development, and maintenance of network and information systems.', description_nl: 'Sakerhet ska integreras vid anskaffning, utveckling och underhall av natverk och informationssystem.', category: 'Riskhanteringsatgarder', subcategory: 'Systemutveckling', level: 'Lag', iso_mapping: '8.25', implementation_guidance: 'Inkludera sakerhetskrav i anskaffning. Tilllampa SSDLC vid utveckling. Underhall sakerhetsuppdateringar.', verification_guidance: 'Kontrollera att sakerhet beaktas vid anskaffning och utveckling.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-9', title: 'Vulnerability handling and disclosure', title_nl: 'Sarbarhetshantering och rapportering', description: 'Policies and procedures for handling and disclosing vulnerabilities shall be established.', description_nl: 'Policyer och rutiner for hantering och rapportering av sarbarheter ska uppratttas.', category: 'Riskhanteringsatgarder', subcategory: 'Sarbarhetshantering', level: 'Lag', iso_mapping: '8.8', implementation_guidance: 'Uppractta sarbarhetshanteringsprocess med definierade SLA. Implementera VDP (Vulnerability Disclosure Policy).', verification_guidance: 'Kontrollera att sarbarhetshantering ar implementerad.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-10', title: 'Cybersecurity risk management effectiveness assessment', title_nl: 'Bedomning av cybersakerhetsatgarders effektivitet', description: 'Policies and procedures to assess the effectiveness of cybersecurity risk management measures shall be established.', description_nl: 'Policyer och rutiner for att bedoma effektiviteten av atgarder for cybersakerhetsriskhantering ska uppratttas.', category: 'Riskhanteringsatgarder', subcategory: 'Effektivitet', level: 'Lag', iso_mapping: '5.36', implementation_guidance: 'Genomfor regelbundna effektivitetsbedomningar av cybersakerhetsatgarder. Anvand nyckeltal och revisioner.', verification_guidance: 'Kontrollera att effektivitetsbedommningar genomfors regelbundet.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-11', title: 'Basic cyber hygiene and cybersecurity training', title_nl: 'Grundlaggande cyberhygien och cybersakerhetsutbildning', description: 'Basic cyber hygiene practices and cybersecurity training shall be implemented for all personnel.', description_nl: 'Grundlaggande cyberhygienpraxis och cybersakerhetsutbildning ska implementeras for all personal.', category: 'Riskhanteringsatgarder', subcategory: 'Utbildning', level: 'Lag', iso_mapping: '6.3', implementation_guidance: 'Genomfor regelbunden cybersakerhetsutbildning for all personal. Tilllampa grundlaggande cyberhygienrutiner.', verification_guidance: 'Kontrollera att utbildning genomfors och att cyberhygien tilllampas.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-12', title: 'Cryptography and encryption policies', title_nl: 'Policyer for kryptografi och kryptering', description: 'Policies for the use of cryptography and encryption shall be established where appropriate.', description_nl: 'Policyer for anvandning av kryptografi och kryptering ska uppratttas dar det ar lampligt.', category: 'Riskhanteringsatgarder', subcategory: 'Kryptering', level: 'Lag', iso_mapping: '8.24', implementation_guidance: 'Uppractta krypteringspolicy. Definiera krav pa krypteringsstyrka och nyckelhantering for olika dataklasser.', verification_guidance: 'Kontrollera att krypteringspolicy ar upprattad och tilllampas.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-13', title: 'Multi-factor authentication and secure communication', title_nl: 'Flerfaktorsautentisering och saker kommunikation', description: 'Multi-factor authentication, continuous authentication, and secured voice/video/text communications shall be used where appropriate.', description_nl: 'Flerfaktorsautentisering, kontinuerlig autentisering och sakrad rost-/video-/textkommunikation ska anvandas dar det ar lampligt.', category: 'Riskhanteringsatgarder', subcategory: 'Autentisering', level: 'Lag', iso_mapping: '8.5', implementation_guidance: 'Implementera MFA for alla privilegierade konton och fjaurratkomst. Anvand sakra kommunikationsverktyg.', verification_guidance: 'Kontrollera att MFA ar implementerat och att sakra kommunikationsverktyg anvands.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-14', title: 'Human resources security and access control', title_nl: 'Personalsakerhet och atkomstkontrollpolicyer', description: 'Human resources security policies and access control policies shall be established.', description_nl: 'Personalsakerhetspolicyer och atkomstkontrollpolicyer ska uppratttas.', category: 'Riskhanteringsatgarder', subcategory: 'Personalsakerhet', level: 'Lag', iso_mapping: '6.1', implementation_guidance: 'Uppractta personalsakerhetspolicyer. Implementera atkomstkontroll med principen om minsta behorigrhet.', verification_guidance: 'Kontrollera att personalsakerhets- och atkomstkontrollpolicyer ar implementerade.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-15', title: 'Asset management', title_nl: 'Tillgangshantering', description: 'An inventory of assets relevant to cybersecurity shall be maintained.', description_nl: 'En inventering av tillgangar som ar relevanta for cybersakerhet ska underhallas.', category: 'Riskhanteringsatgarder', subcategory: 'Tillgangar', level: 'Lag', iso_mapping: '5.9', implementation_guidance: 'Inventera alla IT-tillgangar. Underhall registret lopande. Koppla tillgangar till agare.', verification_guidance: 'Kontrollera att tillgangsinventering ar komplett och aktuell.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },

  // -- Incidentrapportering (Incident reporting - Article 23) --
  { control_number: 'NIS2-16', title: 'Early warning (within 24 hours)', title_nl: 'Tidig varning (inom 24 timmar)', description: 'An early warning shall be submitted to the CSIRT within 24 hours of becoming aware of a significant incident.', description_nl: 'En tidig varning ska lamnas till CSIRT inom 24 timmar efter att man blivit medveten om en betydande incident.', category: 'Incidentrapportering', subcategory: 'Tidig varning', level: 'Lag', iso_mapping: '5.24', implementation_guidance: 'Uppractta rutiner for att lamna tidig varning till MSB/CERT-SE inom 24 timmar.', verification_guidance: 'Kontrollera att rutiner for 24-timmarsrapportering finns.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-17', title: 'Incident notification (within 72 hours)', title_nl: 'Incidentanmalan (inom 72 timmar)', description: 'A full incident notification shall be submitted within 72 hours, updating the early warning with severity assessment and impact.', description_nl: 'En fullstandig incidentanmalan ska lamnas inom 72 timmar, som uppdaterar den tidiga varningen med allvarlighetsbedoming och paverkan.', category: 'Incidentrapportering', subcategory: 'Anmalan', level: 'Lag', iso_mapping: '5.26', implementation_guidance: 'Komplettera tidig varning med detaljerad incidentrapport inom 72 timmar. Inkludera allvarlighetsbedoming.', verification_guidance: 'Kontrollera att fullstandig incidentanmalan lamnas inom 72 timmar.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-18', title: 'Final incident report (within one month)', title_nl: 'Slutrapport (inom en manad)', description: 'A final report shall be submitted within one month including root cause analysis, mitigation measures, and cross-border impact.', description_nl: 'En slutrapport ska lamnas inom en manad som inkluderar grundorsaksanalys, begransningsatgarder och gransoverskridande paverkan.', category: 'Incidentrapportering', subcategory: 'Slutrapport', level: 'Lag', iso_mapping: '5.27', implementation_guidance: 'Uppractta slutrapport med grundorsaksanalys, atgarder och rekommendationer. Lamna till MSB/CERT-SE inom en manad.', verification_guidance: 'Kontrollera att slutrapport lamnas inom en manad.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },

  // -- Tillsyn och sanktioner (Supervision and sanctions) --
  { control_number: 'NIS2-19', title: 'Cooperation with supervisory authorities', title_nl: 'Samarbete med tillsynsmyndigheter', description: 'Entities shall cooperate with supervisory authorities and provide requested information for supervision purposes.', description_nl: 'Verksamhetsutovare ska samarbeta med tillsynsmyndigheter och tillhandahalla begard information for tillsynsandamal.', category: 'Tillsyn', subcategory: 'Samarbete', level: 'Lag', iso_mapping: '5.35', implementation_guidance: 'Forbered for tillsynsbesok. Sakerstall att dokumentation ar tillganglig och att personal kan svara pa fragor.', verification_guidance: 'Kontrollera att organisationen ar beredd for tillsynsbesok.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-20', title: 'Self-registration requirement', title_nl: 'Krav pa egenregistrering', description: 'Essential and important entities shall register with the relevant supervisory authority.', description_nl: 'Vasentliga och viktiga verksamhetsutovare ska registrera sig hos behorig tillsynsmyndighet.', category: 'Tillsyn', subcategory: 'Registrering', level: 'Lag', iso_mapping: '5.31', implementation_guidance: 'Identifiera om organisationen omfattas av NIS2. Registrera hos behorig tillsynsmyndighet (MSB, PTS, FI).', verification_guidance: 'Kontrollera att registrering ar genomford.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },

  // -- Tillagg: NIS2 fordjupning --
  { control_number: 'NIS2-21', title: 'Significant incident definition criteria', title_nl: 'Definitionskriterier for betydande incident', description: 'Criteria for what constitutes a significant incident under NIS2 shall be documented and applied to all security events.', description_nl: 'Kriterier for vad som utgor en betydande incident enligt NIS2 ska dokumenteras och tilllampas pa alla sakerhatshandelser.', category: 'Incidentrapportering', subcategory: 'Definition', level: 'Lag', iso_mapping: '5.25', implementation_guidance: 'Dokumentera NIS2:s definition av betydande incident (500+ anvandare, tjansteavbrott, integritetspaverkan). Integrera i incidentklassificering.', verification_guidance: 'Kontrollera att kriterierna for betydande incident ar dokumenterade och tillampade.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-22', title: 'Sector-specific NIS2 compliance mapping', title_nl: 'Sektorsspecifik NIS2-efterlevnadskartlaggning', description: 'Organizations shall map NIS2 requirements to their specific sector regulations and supervisory authority expectations.', description_nl: 'Organisationer ska kartlagga NIS2-krav till sina specifika sektorsforeskrifter och tillsynsmyndighetens forvantningar.', category: 'Styrning', subcategory: 'Kartlaggning', level: 'Lag', iso_mapping: '5.31', implementation_guidance: 'Kartlagg NIS2-krav mot branschspecifika foreskrifter (PTS for telekom, FI for finans, etc.). Identifiera gap.', verification_guidance: 'Kontrollera att NIS2-kartlaggning ar genomford for relevant sektor.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-23', title: 'Cross-border incident coordination', title_nl: 'Gransoverskridande incidentsamordning', description: 'Entities operating in multiple EU member states shall coordinate incident response with all relevant national CSIRTs.', description_nl: 'Enheter som verkar i flera EU-medlemsstater ska samordna incidenthantering med alla berorda nationella CSIRT:er.', category: 'Incidentrapportering', subcategory: 'Gransoverskridande', level: 'Lag', iso_mapping: '5.24', implementation_guidance: 'Identifiera berorda CSIRT:er i alla lander dar verksamheten bedrivs. Uppractta kontaktvaagar for gransoverskridande incidenter.', verification_guidance: 'Kontrollera att gransoverskridande kontaktvaagar ar upprattade.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-24', title: 'NIS2 management accountability and sanctions awareness', title_nl: 'NIS2 ledningsansvar och sanktionsmedvetenhet', description: 'Management bodies shall be informed of personal liability and potential sanctions for NIS2 non-compliance.', description_nl: 'Ledningsorgan ska informeras om personligt ansvar och potentiella sanktioner vid NIS2-bristande efterlevnad.', category: 'Styrning', subcategory: 'Sanktioner', level: 'Lag', iso_mapping: '5.1', implementation_guidance: 'Informera styrelse och ledning om NIS2-sanktioner (upp till 10 MEUR eller 2% av global omsattning). Dokumentera genomgang.', verification_guidance: 'Kontrollera att ledningen ar informerad om sanktionsregler.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
  { control_number: 'NIS2-25', title: 'Security audits and compliance testing', title_nl: 'Sakerhetsrevisioner och efterlevnadstestning', description: 'Regular security audits and compliance testing against NIS2 requirements shall be performed.', description_nl: 'Regelbundna sakerhetsrevisioner och efterlevnadstestning mot NIS2-krav ska genomforas.', category: 'Tillsyn', subcategory: 'Revision', level: 'Lag', iso_mapping: '5.35', implementation_guidance: 'Genomfor arlig NIS2-efterlevnadsrevision. Tilllampa penetrationstestning och sarbarhetsscanning. Dokumentera resultat.', verification_guidance: 'Kontrollera att NIS2-revisioner genomfors regelbundet.', source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/' },
];

async function main(): Promise<void> {
  console.log('NIS2 Cybersakerhetslagen Ingestion Script');
  console.log('==========================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} requirements.`);

  const output = {
    framework: {
      id: 'nis2-cybersakerhetslagen',
      name: 'Swedish NIS2 Transposition (Cybersakerhetslagen)',
      name_nl: 'Cybersakerhetslagen (svensk NIS2-implementation)',
      issuing_body: 'Riksdagen / MSB / PTS / FI',
      version: '2025',
      effective_date: '2025-01-01',
      scope: 'Swedish transposition of the EU NIS2 Directive into national law, covering essential and important entities across all NIS2 sectors',
      scope_sectors: ['government', 'digital_infrastructure', 'telecom', 'finance', 'healthcare', 'energy', 'transport', 'water'],
      structure_description: 'Organized by NIS2 pillar: governance (NIS2-1 to NIS2-3, NIS2-22, NIS2-24), risk management measures (NIS2-4 to NIS2-15 — Article 21), incident reporting (NIS2-16 to NIS2-18, NIS2-21, NIS2-23 — Article 23), and supervision (NIS2-19 to NIS2-20, NIS2-25).',
      source_url: 'https://www.msb.se/sv/amnesomraden/cybersakerhet-och-informationssakerhet/nis-direktivet/',
      license: 'Swedish law (public)',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
