// scripts/ingest-msb-grundlaggande.ts
// MSB Grundläggande säkerhetsåtgärder (Basic Security Measures)
// Authority: Myndigheten för samhällsskydd och beredskap (MSB)

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'msb-grundlaggande.json');

interface Control {
  control_number: string;
  title: string | null;
  title_nl: string;
  description: string | null;
  description_nl: string;
  category: string;
  subcategory: string | null;
  level: string | null;
  iso_mapping: string | null;
  implementation_guidance: string | null;
  verification_guidance: string | null;
  source_url: string | null;
}

const controls: Control[] = [
  // ── Tekniska åtgärder (Technical measures) ───────────────────────────────
  { control_number: 'GT1', title: 'Patch management', title_nl: 'Patchhantering', description: 'All systems shall have security patches applied within defined timeframes based on severity.', description_nl: 'Alla system ska ha säkerhetsuppdateringar applicerade inom definierade tidsramar baserat på allvarlighetsgrad.', category: 'Tekniska åtgärder', subcategory: 'Uppdatering', level: 'Grundläggande', iso_mapping: '8.8', implementation_guidance: 'Upprätta en process för patchhantering. Kritiska patchar bör appliceras inom 72 timmar, höga inom 14 dagar.', verification_guidance: 'Granska patchstatus och kontrollera att tidsramar följs.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT2', title: 'Antivirus and endpoint protection', title_nl: 'Antivirus och ändpunktsskydd', description: 'All endpoints shall have up-to-date antivirus or endpoint detection and response (EDR) software installed.', description_nl: 'Alla ändpunkter ska ha uppdaterat antivirus- eller EDR-programvara installerad.', category: 'Tekniska åtgärder', subcategory: 'Skadlig kod', level: 'Grundläggande', iso_mapping: '8.7', implementation_guidance: 'Installera och underhåll skydd mot skadlig kod på alla klienter och servrar. Aktivera realtidsskanning.', verification_guidance: 'Kontrollera att skyddet är installerat och uppdaterat på samtliga enheter.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT3', title: 'Firewall configuration', title_nl: 'Brandväggskonfiguration', description: 'Firewalls shall be configured to deny all traffic by default and only allow necessary, documented traffic flows.', description_nl: 'Brandväggar ska konfigureras för att neka all trafik som standard och bara tillåta nödvändiga, dokumenterade trafikflöden.', category: 'Tekniska åtgärder', subcategory: 'Brandvägg', level: 'Grundläggande', iso_mapping: '8.20', implementation_guidance: 'Tillämpa principen om minsta möjliga åtkomst i brandväggsregler. Dokumentera och granska regler regelbundet.', verification_guidance: 'Granska brandväggsregler och verifiera att onödiga regler tagits bort.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT4', title: 'Regular backup', title_nl: 'Regelbunden säkerhetskopiering', description: 'Critical data shall be backed up regularly with tested restoration procedures. Backups shall be stored separately from primary systems.', description_nl: 'Kritisk data ska säkerhetskopieras regelbundet med testade återställningsrutiner. Kopior ska lagras separat från primära system.', category: 'Tekniska åtgärder', subcategory: 'Säkerhetskopiering', level: 'Grundläggande', iso_mapping: '8.13', implementation_guidance: 'Genomför daglig säkerhetskopiering av kritiska system. Testa återställning kvartalsvis. Lagra kopior på annan plats.', verification_guidance: 'Kontrollera att säkerhetskopior tas dagligen och att återställningstester genomförs.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT5', title: 'Encryption of sensitive data', title_nl: 'Kryptering av känslig data', description: 'Sensitive data shall be encrypted at rest and in transit using current encryption standards.', description_nl: 'Känslig data ska krypteras vid lagring och överföring med aktuella krypteringsstandarder.', category: 'Tekniska åtgärder', subcategory: 'Kryptering', level: 'Grundläggande', iso_mapping: '8.24', implementation_guidance: 'Använd TLS 1.2 eller högre för data i transit. Kryptera hårddiskar och databaser som innehåller känslig information.', verification_guidance: 'Verifiera TLS-konfiguration och kontrollera diskkryptering på servrar och klienter.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT6', title: 'Network segmentation', title_nl: 'Nätverkssegmentering', description: 'Networks shall be segmented to isolate critical systems and limit lateral movement in case of a breach.', description_nl: 'Nätverk ska segmenteras för att isolera kritiska system och begränsa lateral förflyttning vid intrång.', category: 'Tekniska åtgärder', subcategory: 'Nätverk', level: 'Grundläggande', iso_mapping: '8.22', implementation_guidance: 'Separera olika säkerhetszoner i nätverket. Använd VLAN och brandväggar mellan segmenten.', verification_guidance: 'Granska nätverksdiagram och verifiera att segmentering är korrekt implementerad.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT7', title: 'Centralized logging', title_nl: 'Centraliserad loggning', description: 'Security-relevant events shall be logged centrally and protected from unauthorized modification.', description_nl: 'Säkerhetsrelevanta händelser ska loggas centralt och skyddas mot obehörig ändring.', category: 'Tekniska åtgärder', subcategory: 'Loggning', level: 'Grundläggande', iso_mapping: '8.15', implementation_guidance: 'Implementera en central loggtjänst (SIEM). Logga inloggningar, administrativa åtgärder och säkerhetshändelser.', verification_guidance: 'Kontrollera att loggar samlas in centralt och att de är skyddade mot manipulation.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT8', title: 'Multi-factor authentication', title_nl: 'Flerfaktorsautentisering', description: 'Multi-factor authentication shall be required for remote access, administrative access, and access to sensitive systems.', description_nl: 'Flerfaktorsautentisering ska krävas vid fjärråtkomst, administrativ åtkomst och åtkomst till känsliga system.', category: 'Tekniska åtgärder', subcategory: 'Autentisering', level: 'Grundläggande', iso_mapping: '8.5', implementation_guidance: 'Implementera MFA för VPN, administratörsåtkomst, e-post och molntjänster.', verification_guidance: 'Kontrollera att MFA är aktiverat på alla definierade system.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT9', title: 'Vulnerability scanning', title_nl: 'Sårbarhetsskanning', description: 'Regular vulnerability scans shall be performed on all internet-facing systems and critical internal systems.', description_nl: 'Regelbundna sårbarhetsskanningar ska genomföras på alla internetexponerade system och kritiska interna system.', category: 'Tekniska åtgärder', subcategory: 'Sårbarhet', level: 'Grundläggande', iso_mapping: '8.8', implementation_guidance: 'Skanna internetexponerade system veckovis och interna system månadsvis. Åtgärda identifierade sårbarheter.', verification_guidance: 'Granska skanningsrapporter och verifiera att sårbarheter åtgärdas.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT10', title: 'Secure DNS configuration', title_nl: 'Säker DNS-konfiguration', description: 'DNS services shall be configured securely with DNSSEC enabled where applicable.', description_nl: 'DNS-tjänster ska konfigureras säkert med DNSSEC aktiverat där det är tillämpligt.', category: 'Tekniska åtgärder', subcategory: 'DNS', level: 'Grundläggande', iso_mapping: '8.20', implementation_guidance: 'Aktivera DNSSEC på organisationens domäner. Använd säkra DNS-resolvers.', verification_guidance: 'Verifiera DNSSEC-konfigurationen och DNS-resolverkonfigurationer.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT11', title: 'Email security (SPF, DKIM, DMARC)', title_nl: 'E-postsäkerhet (SPF, DKIM, DMARC)', description: 'Email authentication protocols SPF, DKIM, and DMARC shall be configured for all organizational domains.', description_nl: 'E-postautentiseringsprotokollen SPF, DKIM och DMARC ska konfigureras för alla organisationens domäner.', category: 'Tekniska åtgärder', subcategory: 'E-post', level: 'Grundläggande', iso_mapping: '8.20', implementation_guidance: 'Konfigurera SPF, DKIM och DMARC med p=reject-policy. Övervaka DMARC-rapporter.', verification_guidance: 'Kontrollera DNS-poster för SPF, DKIM och DMARC. Verifiera att DMARC-policy är satt till reject.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT12', title: 'Secure system hardening', title_nl: 'Säker systemhärdning', description: 'Systems shall be hardened according to recognized benchmarks before deployment.', description_nl: 'System ska härdas enligt erkända riktlinjer innan de tas i drift.', category: 'Tekniska åtgärder', subcategory: 'Härdning', level: 'Grundläggande', iso_mapping: '8.9', implementation_guidance: 'Tillämpa CIS Benchmarks eller motsvarande härdningsriktlinjer. Inaktivera onödiga tjänster och portar.', verification_guidance: 'Jämför systemkonfigurationer mot härdningsriktlinjer.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT13', title: 'Web application firewall', title_nl: 'Brandvägg för webbapplikationer', description: 'Internet-facing web applications shall be protected by a web application firewall (WAF).', description_nl: 'Internetexponerade webbapplikationer ska skyddas av en brandvägg för webbapplikationer (WAF).', category: 'Tekniska åtgärder', subcategory: 'Webb', level: 'Grundläggande', iso_mapping: '8.20', implementation_guidance: 'Implementera WAF framför internetexponerade webbapplikationer. Konfigurera regler mot OWASP Top 10.', verification_guidance: 'Kontrollera att WAF är konfigurerad och aktiv för alla exponerade webbapplikationer.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT14', title: 'Endpoint device management', title_nl: 'Hantering av ändpunktsenheter', description: 'All user endpoint devices shall be registered, managed, and protected according to security policy.', description_nl: 'Alla användares ändpunktsenheter ska registreras, hanteras och skyddas enligt säkerhetspolicy.', category: 'Tekniska åtgärder', subcategory: 'Ändpunkter', level: 'Grundläggande', iso_mapping: '8.1', implementation_guidance: 'Implementera MDM-lösning (Mobile Device Management). Registrera alla enheter och tillämpa säkerhetspolicyer.', verification_guidance: 'Kontrollera att alla enheter är registrerade i MDM och att policyer tillämpas.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT15', title: 'Intrusion detection', title_nl: 'Intrångsdetektering', description: 'Intrusion detection or prevention systems shall be deployed to monitor network traffic for malicious activity.', description_nl: 'System för intrångsdetektering eller intrångsskydd ska installeras för att övervaka nätverkstrafik.', category: 'Tekniska åtgärder', subcategory: 'Övervakning', level: 'Grundläggande', iso_mapping: '8.16', implementation_guidance: 'Implementera IDS/IPS i nätverkets gränspunkter. Granska larm regelbundet.', verification_guidance: 'Kontrollera att IDS/IPS är aktiv och att larm granskas.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT16', title: 'Secure remote access', title_nl: 'Säker fjärråtkomst', description: 'Remote access shall only be provided through secure, encrypted channels with proper authentication.', description_nl: 'Fjärråtkomst ska endast ske genom säkra, krypterade kanaler med korrekt autentisering.', category: 'Tekniska åtgärder', subcategory: 'Fjärråtkomst', level: 'Grundläggande', iso_mapping: '8.5', implementation_guidance: 'Använd VPN med stark kryptering för fjärråtkomst. Kräv MFA vid inloggning.', verification_guidance: 'Granska VPN-konfiguration och kontrollera att MFA är aktiverat.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT17', title: 'TLS configuration', title_nl: 'TLS-konfiguration', description: 'All external and internal services shall use TLS 1.2 or higher with strong cipher suites.', description_nl: 'Alla externa och interna tjänster ska använda TLS 1.2 eller högre med starka krypteringssviter.', category: 'Tekniska åtgärder', subcategory: 'Kryptering', level: 'Grundläggande', iso_mapping: '8.24', implementation_guidance: 'Konfigurera TLS 1.2 eller 1.3 på alla tjänster. Inaktivera svaga krypteringssviter och äldre TLS-versioner.', verification_guidance: 'Skanna TLS-konfiguration med verktyg som testssl.sh. Verifiera att TLS 1.0/1.1 är inaktiverat.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT18', title: 'Least privilege access', title_nl: 'Minsta möjliga behörighet', description: 'Access rights shall be assigned based on the principle of least privilege, granting only the minimum access needed.', description_nl: 'Behörigheter ska tilldelas baserat på principen om minsta möjliga behörighet, och ge bara den åtkomst som krävs.', category: 'Tekniska åtgärder', subcategory: 'Behörigheter', level: 'Grundläggande', iso_mapping: '5.15', implementation_guidance: 'Granska behörigheter regelbundet. Tillämpa rollbaserad åtkomstkontroll (RBAC).', verification_guidance: 'Genomför behörighetsgranskningar och kontrollera att principen följs.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT19', title: 'Secure password policy', title_nl: 'Säker lösenordspolicy', description: 'A password policy requiring strong, unique passwords shall be enforced across all systems.', description_nl: 'En lösenordspolicy som kräver starka, unika lösenord ska tillämpas på alla system.', category: 'Tekniska åtgärder', subcategory: 'Lösenord', level: 'Grundläggande', iso_mapping: '5.17', implementation_guidance: 'Kräv minst 12 tecken, blandade teckentyper. Rekommendera lösenordshanterare. Förbjud återanvändning.', verification_guidance: 'Granska lösenordspolicyn och kontrollera att den tillämpas tekniskt.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT20', title: 'Mobile device security', title_nl: 'Säkerhet för mobila enheter', description: 'Mobile devices used for work shall be protected with encryption, PIN/biometric lock, and remote wipe capability.', description_nl: 'Mobila enheter som används i arbetet ska skyddas med kryptering, PIN/biometriskt lås och möjlighet till fjärradering.', category: 'Tekniska åtgärder', subcategory: 'Mobila enheter', level: 'Grundläggande', iso_mapping: '8.1', implementation_guidance: 'Kräv enhetskryptering, skärmlåsning och fjärradering. Hantera via MDM.', verification_guidance: 'Kontrollera MDM-policyer och verifiera att enheter uppfyller kraven.', source_url: 'https://www.informationssakerhet.se/metodstod/' },

  // ── Administrativa åtgärder (Administrative measures) ────────────────────
  { control_number: 'GA1', title: 'Information security policy', title_nl: 'Informationssäkerhetspolicy', description: 'A documented information security policy shall be approved by management and communicated to all employees.', description_nl: 'En dokumenterad informationssäkerhetspolicy ska godkännas av ledningen och kommuniceras till alla anställda.', category: 'Administrativa åtgärder', subcategory: 'Policy', level: 'Grundläggande', iso_mapping: '5.1', implementation_guidance: 'Upprätta en informationssäkerhetspolicy som är anpassad till organisationens verksamhet.', verification_guidance: 'Kontrollera att policyn finns, är godkänd och kommunicerad.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA2', title: 'Security awareness training', title_nl: 'Utbildning i säkerhetsmedvetenhet', description: 'All employees shall complete annual information security awareness training.', description_nl: 'Alla anställda ska genomgå årlig utbildning i säkerhetsmedvetenhet.', category: 'Administrativa åtgärder', subcategory: 'Utbildning', level: 'Grundläggande', iso_mapping: '6.3', implementation_guidance: 'Genomför årlig medvetenhetsutbildning. Inkludera nätfisketester. Anpassa till aktuella hot.', verification_guidance: 'Granska utbildningsregister och kontrollera att alla har genomfört utbildningen.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA3', title: 'Incident response procedures', title_nl: 'Rutiner för incidenthantering', description: 'Documented incident response procedures shall be established, tested, and communicated.', description_nl: 'Dokumenterade rutiner för incidenthantering ska upprättas, testas och kommuniceras.', category: 'Administrativa åtgärder', subcategory: 'Incidenter', level: 'Grundläggande', iso_mapping: '5.24', implementation_guidance: 'Upprätta en incidenthanteringsplan med roller, eskaleringsvägar och kontaktlistor. Testa årligen.', verification_guidance: 'Kontrollera att incidenthanteringsrutiner finns och har testats.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA4', title: 'Access management procedures', title_nl: 'Rutiner för behörighetshantering', description: 'Procedures for granting, reviewing, and revoking access rights shall be established.', description_nl: 'Rutiner för tilldelning, granskning och borttagning av behörigheter ska upprättas.', category: 'Administrativa åtgärder', subcategory: 'Behörigheter', level: 'Grundläggande', iso_mapping: '5.18', implementation_guidance: 'Upprätta rutiner som säkerställer att behörigheter tilldelas vid behov och tas bort vid avslut.', verification_guidance: 'Granska rutinerna och kontrollera att behörighetsgranskningar genomförs.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA5', title: 'Information classification scheme', title_nl: 'Klassificeringsmodell för information', description: 'An information classification scheme shall be established to ensure appropriate protection of organizational information.', description_nl: 'En klassificeringsmodell för information ska upprättas för att säkerställa lämpligt skydd av organisationens information.', category: 'Administrativa åtgärder', subcategory: 'Klassificering', level: 'Grundläggande', iso_mapping: '5.12', implementation_guidance: 'Definiera klassificeringsnivåer med tillhörande hanteringsregler. Utbilda personal i klassificering.', verification_guidance: 'Kontrollera att klassificeringsmodellen finns och tillämpas.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA6', title: 'Supplier security assessment', title_nl: 'Säkerhetsbedömning av leverantörer', description: 'Information security requirements shall be included in supplier agreements, and suppliers shall be assessed regularly.', description_nl: 'Informationssäkerhetskrav ska ingå i leverantörsavtal, och leverantörer ska bedömas regelbundet.', category: 'Administrativa åtgärder', subcategory: 'Leverantörer', level: 'Grundläggande', iso_mapping: '5.19', implementation_guidance: 'Inkludera säkerhetskrav i leverantörsavtal. Genomför regelbundna leverantörsbedömningar.', verification_guidance: 'Granska leverantörsavtal och kontrollera att säkerhetskrav ingår.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA7', title: 'Business continuity plan', title_nl: 'Kontinuitetsplan', description: 'A business continuity plan shall be maintained to ensure critical functions can continue during disruptions.', description_nl: 'En kontinuitetsplan ska upprätthållas för att säkerställa att kritiska funktioner kan fortsätta vid störningar.', category: 'Administrativa åtgärder', subcategory: 'Kontinuitet', level: 'Grundläggande', iso_mapping: '5.29', implementation_guidance: 'Upprätta en kontinuitetsplan med prioriterade processer, RTO/RPO och kommunikationsplaner.', verification_guidance: 'Kontrollera att planen finns, är aktuell och att den har testats.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA8', title: 'Risk assessment', title_nl: 'Riskbedömning', description: 'Regular risk assessments shall be performed to identify and address information security risks.', description_nl: 'Regelbundna riskbedömningar ska genomföras för att identifiera och hantera informationssäkerhetsrisker.', category: 'Administrativa åtgärder', subcategory: 'Riskhantering', level: 'Grundläggande', iso_mapping: '5.1', implementation_guidance: 'Genomför riskbedömning minst årligen. Uppdatera vid väsentliga förändringar.', verification_guidance: 'Granska riskbedömningar och kontrollera att de genomförs regelbundet.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA9', title: 'Document management', title_nl: 'Dokumenthantering', description: 'Security documents, policies, and procedures shall be maintained, version-controlled, and accessible to relevant personnel.', description_nl: 'Säkerhetsdokument, policyer och rutiner ska underhållas, versionhanteras och vara tillgängliga för berörd personal.', category: 'Administrativa åtgärder', subcategory: 'Dokumentation', level: 'Grundläggande', iso_mapping: '5.37', implementation_guidance: 'Upprätta en dokumentstruktur med versionhantering. Säkerställ att dokument granskas regelbundet.', verification_guidance: 'Kontrollera att dokument är aktuella och tillgängliga.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA10', title: 'Security in procurement', title_nl: 'Säkerhet vid upphandling', description: 'Information security requirements shall be considered during procurement of IT systems and services.', description_nl: 'Informationssäkerhetskrav ska beaktas vid upphandling av IT-system och tjänster.', category: 'Administrativa åtgärder', subcategory: 'Upphandling', level: 'Grundläggande', iso_mapping: '5.19', implementation_guidance: 'Inkludera säkerhetskrav i kravspecifikationer vid upphandling. Genomför säkerhetsbedömning av leverantörer.', verification_guidance: 'Granska upphandlingsdokument och kontrollera att säkerhetskrav ingår.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA11', title: 'Personnel offboarding security', title_nl: 'Säkerhet vid personalavslut', description: 'Procedures for handling information security aspects when employees leave shall be established.', description_nl: 'Rutiner för hantering av informationssäkerhetsaspekter vid anställdas avslut ska upprättas.', category: 'Administrativa åtgärder', subcategory: 'Personal', level: 'Grundläggande', iso_mapping: '6.5', implementation_guidance: 'Upprätta en checklista för avslut som inkluderar borttagning av behörigheter, återlämning av utrustning och avslut av konton.', verification_guidance: 'Kontrollera att avslutschecklistan följs vid personalförändringar.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA12', title: 'Confidentiality agreements', title_nl: 'Sekretessavtal', description: 'Confidentiality or non-disclosure agreements reflecting the organization\'s needs shall be identified, documented, and regularly reviewed.', description_nl: 'Sekretessavtal som återspeglar organisationens behov ska identifieras, dokumenteras och regelbundet granskas.', category: 'Administrativa åtgärder', subcategory: 'Avtal', level: 'Grundläggande', iso_mapping: '6.6', implementation_guidance: 'Kräv sekretessavtal av alla anställda och konsulter. Granska avtalen regelbundet.', verification_guidance: 'Kontrollera att sekretessavtal finns undertecknade för all personal.', source_url: 'https://www.informationssakerhet.se/metodstod/' },

  // ── Fysiska åtgärder (Physical measures) ─────────────────────────────────
  { control_number: 'GF1', title: 'Physical access control to server rooms', title_nl: 'Fysisk åtkomstkontroll till serverrum', description: 'Server rooms and data centers shall have physical access controls with logging.', description_nl: 'Serverrum och datahallar ska ha fysiska åtkomstkontroller med loggning.', category: 'Fysiska åtgärder', subcategory: 'Tillträde', level: 'Grundläggande', iso_mapping: '7.2', implementation_guidance: 'Installera passersystem med loggning för serverrum. Begränsa tillträde till behörig personal.', verification_guidance: 'Granska tillträdesloggar och kontrollera att passersystemet fungerar.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GF2', title: 'Fire and water protection', title_nl: 'Brand- och vattenskydd', description: 'Fire suppression and water detection systems shall be installed in facilities housing critical IT systems.', description_nl: 'Brandskyddssystem och vattendetektorer ska installeras i lokaler som innehåller kritiska IT-system.', category: 'Fysiska åtgärder', subcategory: 'Brandskydd', level: 'Grundläggande', iso_mapping: '7.5', implementation_guidance: 'Installera brandlarm, släcksystem och vattendetektorer i serverrum. Genomför regelbundna tester.', verification_guidance: 'Kontrollera att brandskydd och vattendetektorer är installerade och testade.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GF3', title: 'Uninterruptible power supply', title_nl: 'Avbrottsfri strömförsörjning', description: 'Critical IT equipment shall be connected to uninterruptible power supply (UPS) units.', description_nl: 'Kritisk IT-utrustning ska anslutas till avbrottsfri strömförsörjning (UPS).', category: 'Fysiska åtgärder', subcategory: 'Strömförsörjning', level: 'Grundläggande', iso_mapping: '7.11', implementation_guidance: 'Installera UPS för kritiska system. Dimensionera för att klara planerad nedstängningstid.', verification_guidance: 'Kontrollera att UPS-enheter fungerar och att kapaciteten är tillräcklig.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GF4', title: 'Visitor management', title_nl: 'Besökshantering', description: 'Visitors to secure areas shall be registered, accompanied, and their access logged.', description_nl: 'Besökare i säkra områden ska registreras, åtföljas och deras tillträde loggas.', category: 'Fysiska åtgärder', subcategory: 'Besökare', level: 'Grundläggande', iso_mapping: '7.2', implementation_guidance: 'Upprätta rutiner för besökshantering med registrering och ledsagning.', verification_guidance: 'Granska besöksloggar och kontrollera att rutinerna följs.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GF5', title: 'Secure disposal of equipment', title_nl: 'Säker avveckling av utrustning', description: 'Equipment containing storage media shall be securely disposed of to prevent data recovery.', description_nl: 'Utrustning som innehåller lagringsmedia ska avvecklas säkert för att förhindra dataåterställning.', category: 'Fysiska åtgärder', subcategory: 'Avveckling', level: 'Grundläggande', iso_mapping: '7.14', implementation_guidance: 'Upprätta rutiner för säker radering eller destruktion av lagringsmedia vid avveckling.', verification_guidance: 'Kontrollera att destruktionsprotokoll upprättas.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GF6', title: 'Cable security', title_nl: 'Kabelsäkerhet', description: 'Power and telecommunications cabling carrying data or supporting services shall be protected from interception or damage.', description_nl: 'Kraft- och telekommunikationskablage som bär data eller stödjer tjänster ska skyddas mot avlyssning eller skada.', category: 'Fysiska åtgärder', subcategory: 'Kablage', level: 'Grundläggande', iso_mapping: '7.12', implementation_guidance: 'Skydda kablage i kabelkanaler. Separera kraft- och datakablage.', verification_guidance: 'Inspektera kabeldragning och kontrollera att skydd finns.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GF7', title: 'Environmental monitoring', title_nl: 'Miljöövervakning', description: 'Environmental conditions in server rooms shall be monitored for temperature, humidity, and other threats.', description_nl: 'Miljöförhållanden i serverrum ska övervakas avseende temperatur, fuktighet och andra hot.', category: 'Fysiska åtgärder', subcategory: 'Övervakning', level: 'Grundläggande', iso_mapping: '7.5', implementation_guidance: 'Installera temperatur- och fuktighetssensorer i serverrum. Konfigurera larm vid avvikelser.', verification_guidance: 'Kontrollera att sensorer är installerade och att larm fungerar.', source_url: 'https://www.informationssakerhet.se/metodstod/' },

  // ── Tekniska åtgärder — Additional ────────────────────────────────────────
  { control_number: 'GT21', title: 'Application whitelisting', title_nl: 'Applikationsvitlistning', description: 'Only approved applications shall be allowed to execute on endpoints and servers.', description_nl: 'Bara godkända applikationer ska tillåtas köras på ändpunkter och servrar.', category: 'Tekniska åtgärder', subcategory: 'Applikationskontroll', level: 'Grundläggande', iso_mapping: '8.19', implementation_guidance: 'Implementera applikationsvitlistning via AppLocker, WDAC eller motsvarande. Definiera tillåtna program.', verification_guidance: 'Kontrollera att applikationsvitlistning är aktiv och att policyer tillämpas.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT22', title: 'Database security', title_nl: 'Databassäkerhet', description: 'Databases shall be hardened with access controls, encryption of sensitive fields, and audit logging of queries.', description_nl: 'Databaser ska härdas med åtkomstkontroller, kryptering av känsliga fält och granskningsloggning av frågor.', category: 'Tekniska åtgärder', subcategory: 'Databas', level: 'Grundläggande', iso_mapping: '8.25', implementation_guidance: 'Begränsa databasåtkomst. Kryptera känsliga kolumner. Aktivera audit logging.', verification_guidance: 'Granska databaskonfiguration och kontrollera att åtkomstkontroller och loggning är aktiva.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT23', title: 'DNS sinkhole for malicious domains', title_nl: 'DNS-sinkhole för skadliga domäner', description: 'DNS resolution shall be configured to block known malicious domains using sinkhole or RPZ techniques.', description_nl: 'DNS-upplösning ska konfigureras för att blockera kända skadliga domäner med sinkhole- eller RPZ-teknik.', category: 'Tekniska åtgärder', subcategory: 'DNS', level: 'Grundläggande', iso_mapping: '8.23', implementation_guidance: 'Konfigurera DNS RPZ med hotinformationsflöden. Blockera kända C2-domäner och skadliga webbplatser.', verification_guidance: 'Kontrollera att RPZ är konfigurerat och att blockeringslistor uppdateras.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT24', title: 'Privileged account separation', title_nl: 'Separation av privilegierade konton', description: 'Administrative accounts shall be separate from regular user accounts, with dedicated workstations for administrative tasks.', description_nl: 'Administrativa konton ska vara separata från vanliga användarkonton, med dedikerade arbetsstationer för administrativa uppgifter.', category: 'Tekniska åtgärder', subcategory: 'Behörigheter', level: 'Grundläggande', iso_mapping: '8.2', implementation_guidance: 'Tilldela separata administrativa konton. Använd PAW (Privileged Access Workstation) för administration.', verification_guidance: 'Kontrollera att administrativa konton är separata och att PAW används.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT25', title: 'Automated configuration management', title_nl: 'Automatiserad konfigurationshantering', description: 'System configurations shall be managed through automated tools to ensure consistency and detect drift.', description_nl: 'Systemkonfigurationer ska hanteras genom automatiserade verktyg för att säkerställa konsekvens och upptäcka avvikelser.', category: 'Tekniska åtgärder', subcategory: 'Konfiguration', level: 'Grundläggande', iso_mapping: '8.9', implementation_guidance: 'Använd konfigurationshanteringsverktyg (Ansible, Puppet, etc.). Detektera konfigurationsavvikelser automatiskt.', verification_guidance: 'Kontrollera att konfigurationshantering är implementerad och att avvikelser rapporteras.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GT26', title: 'Secure boot and firmware integrity', title_nl: 'Säker uppstart och firmware-integritet', description: 'Systems shall use secure boot mechanisms to verify firmware and OS integrity at startup.', description_nl: 'System ska använda mekanismer för säker uppstart för att verifiera firmware- och OS-integritet vid start.', category: 'Tekniska åtgärder', subcategory: 'Härdning', level: 'Grundläggande', iso_mapping: '8.9', implementation_guidance: 'Aktivera Secure Boot och TPM. Verifiera firmware-integritet. Övervaka firmware-uppdateringar.', verification_guidance: 'Kontrollera att Secure Boot är aktiverat och att firmware är uppdaterad.', source_url: 'https://www.informationssakerhet.se/metodstod/' },

  // ── Administrativa åtgärder — Additional ──────────────────────────────────
  { control_number: 'GA13', title: 'Change management', title_nl: 'Ändringshantering', description: 'Changes to IT systems shall follow a formal change management process with risk assessment and approval.', description_nl: 'Ändringar i IT-system ska följa en formell ändringshanteringsprocess med riskbedömning och godkännande.', category: 'Administrativa åtgärder', subcategory: 'Ändringshantering', level: 'Grundläggande', iso_mapping: '8.32', implementation_guidance: 'Upprätta en ändringshanteringsprocess med riskbedömning, godkännande och testning innan driftsättning.', verification_guidance: 'Granska ändringsloggar och kontrollera att processen följs.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA14', title: 'Privacy impact assessment', title_nl: 'Konsekvensbedömning avseende dataskydd', description: 'A privacy impact assessment shall be performed when processing personal data with high risk.', description_nl: 'En konsekvensbedömning avseende dataskydd ska genomföras vid behandling av personuppgifter med hög risk.', category: 'Administrativa åtgärder', subcategory: 'Dataskydd', level: 'Grundläggande', iso_mapping: '5.34', implementation_guidance: 'Genomför DPIA enligt artikel 35 GDPR. Dokumentera risker och åtgärder.', verification_guidance: 'Kontrollera att DPIA genomförts för behandlingar med hög risk.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA15', title: 'Security architecture review', title_nl: 'Granskning av säkerhetsarkitektur', description: 'The security architecture shall be reviewed periodically to ensure it remains appropriate for current threats.', description_nl: 'Säkerhetsarkitekturen ska granskas periodiskt för att säkerställa att den förblir lämplig för aktuella hot.', category: 'Administrativa åtgärder', subcategory: 'Arkitektur', level: 'Grundläggande', iso_mapping: '5.8', implementation_guidance: 'Genomför årlig granskning av säkerhetsarkitekturen. Uppdatera baserat på nya hot och verksamhetsförändringar.', verification_guidance: 'Kontrollera att arkitekturgranskning genomförs och att resultat dokumenteras.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA16', title: 'Legal and regulatory compliance tracking', title_nl: 'Uppföljning av rättslig och regulatorisk efterlevnad', description: 'Compliance with applicable laws and regulations affecting information security shall be tracked and verified.', description_nl: 'Efterlevnad av tillämpliga lagar och förordningar som påverkar informationssäkerhet ska följas upp och verifieras.', category: 'Administrativa åtgärder', subcategory: 'Efterlevnad', level: 'Grundläggande', iso_mapping: '5.31', implementation_guidance: 'Inventera tillämpliga krav. Genomför regelbundna efterlevnadskontroller. Dokumentera avvikelser och åtgärder.', verification_guidance: 'Granska efterlevnadsregister och kontrollera att det är aktuellt.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA17', title: 'Acceptable use policy', title_nl: 'Policy för acceptabel användning', description: 'An acceptable use policy for IT resources shall be established and communicated to all personnel.', description_nl: 'En policy för acceptabel användning av IT-resurser ska upprättas och kommuniceras till all personal.', category: 'Administrativa åtgärder', subcategory: 'Policy', level: 'Grundläggande', iso_mapping: '5.10', implementation_guidance: 'Upprätta en policy som beskriver tillåten och otillåten användning av IT-resurser. Kräv kvittens.', verification_guidance: 'Kontrollera att policyn finns och att anställda har kvitterat den.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GA18', title: 'Secure development practices', title_nl: 'Säkra utvecklingsrutiner', description: 'Software development shall follow secure coding practices with code review, testing, and vulnerability scanning.', description_nl: 'Programvaruutveckling ska följa säkra kodningsrutiner med kodgranskning, testning och sårbarhetsskanning.', category: 'Administrativa åtgärder', subcategory: 'Utveckling', level: 'Grundläggande', iso_mapping: '8.25', implementation_guidance: 'Implementera SSDLC. Kräv kodgranskning. Kör SAST och DAST i CI/CD-pipelinen.', verification_guidance: 'Kontrollera att SSDLC-processen följs och att automatiserade tester körs.', source_url: 'https://www.informationssakerhet.se/metodstod/' },

  // ── Fysiska åtgärder — Additional ─────────────────────────────────────────
  { control_number: 'GF8', title: 'Clean desk and screen lock', title_nl: 'Rent skrivbord och skärmlåsning', description: 'A clean desk policy and automatic screen lock shall be enforced to protect sensitive information.', description_nl: 'En policy för rent skrivbord och automatisk skärmlåsning ska tillämpas för att skydda känslig information.', category: 'Fysiska åtgärder', subcategory: 'Arbetsmiljö', level: 'Grundläggande', iso_mapping: '7.7', implementation_guidance: 'Tillämpa automatisk skärmlåsning efter inaktivitet. Kommunicera policy för rent skrivbord.', verification_guidance: 'Kontrollera att skärmlåsning är konfigurerad och att policyn följs.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
  { control_number: 'GF9', title: 'Redundant network connectivity', title_nl: 'Redundant nätverksanslutning', description: 'Critical facilities shall have redundant network connections from different providers or paths.', description_nl: 'Kritiska anläggningar ska ha redundanta nätverksanslutningar från olika leverantörer eller vägar.', category: 'Fysiska åtgärder', subcategory: 'Redundans', level: 'Grundläggande', iso_mapping: '7.11', implementation_guidance: 'Säkerställ redundant internetanslutning med olika vägar. Testa failover regelbundet.', verification_guidance: 'Kontrollera att redundanta anslutningar finns och att failover fungerar.', source_url: 'https://www.informationssakerhet.se/metodstod/' },
];

async function main(): Promise<void> {
  console.log('MSB Grundlaggande Ingestion Script');
  console.log('====================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} controls validated.`);

  const output = {
    framework: {
      id: 'msb-grundlaggande',
      name: 'Basic Security Measures',
      name_nl: 'Grundläggande säkerhetsåtgärder',
      issuing_body: 'Myndigheten för samhällsskydd och beredskap (MSB)',
      version: '2024',
      effective_date: '2024-01-01',
      scope: 'Fundamental security measures for Swedish organizations organized as technical, administrative, and physical controls',
      scope_sectors: ['government', 'digital_infrastructure'],
      structure_description: 'Organized by type: technical (GT), administrative (GA), and physical (GF) measures. Each measure targets a basic security hygiene practice.',
      source_url: 'https://www.informationssakerhet.se/metodstod/',
      license: 'Public sector publication',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
