// scripts/ingest-cert-se.ts
// CERT-SE Tekniska rekommendationer
// Authority: CERT-SE (under MSB)

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'cert-se-rekommendationer.json');

const controls = [
  { control_number: 'CSE-1', title: 'Network perimeter hardening', title_nl: 'Härdning av nätverksperimeter', description: 'External network perimeters shall be hardened with properly configured firewalls, IDS/IPS, and minimal exposed services.', description_nl: 'Externna nätverksperimetrar ska härdas med korrekt konfigurerade brandväggar, IDS/IPS och minimalt antal exponerade tjänster.', category: 'Nätverkssäkerhet', subcategory: 'Perimeter', level: 'Teknisk', iso_mapping: '8.20', implementation_guidance: 'Minimera exponerade tjänster. Konfigurera brandväggar med deny-all som standardregel. Aktivera IDS/IPS.', verification_guidance: 'Genomför extern portskanning och kontrollera att bara nödvändiga tjänster är exponerade.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-2', title: 'Email authentication (SPF/DKIM/DMARC)', title_nl: 'E-postautentisering (SPF/DKIM/DMARC)', description: 'All organizational domains shall have SPF, DKIM, and DMARC configured to prevent email spoofing.', description_nl: 'Alla organisationens domäner ska ha SPF, DKIM och DMARC konfigurerat för att förhindra e-postförfalskning.', category: 'E-postsäkerhet', subcategory: 'Autentisering', level: 'Teknisk', iso_mapping: '8.20', implementation_guidance: 'Konfigurera SPF med -all. Implementera DKIM-signering. Ställ in DMARC med p=reject. Övervaka DMARC-rapporter.', verification_guidance: 'Verifiera DNS-poster för SPF, DKIM och DMARC. Kontrollera DMARC-policy.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-3', title: 'DNSSEC implementation', title_nl: 'DNSSEC-implementering', description: 'DNSSEC shall be enabled for all organizational domains to protect against DNS spoofing.', description_nl: 'DNSSEC ska aktiveras för alla organisationens domäner för att skydda mot DNS-förfalskning.', category: 'DNS-säkerhet', subcategory: 'DNSSEC', level: 'Teknisk', iso_mapping: '8.20', implementation_guidance: 'Aktivera DNSSEC-signering för alla domäner. Verifiera kedjans integritet. Övervaka nyckelrotation.', verification_guidance: 'Kontrollera DNSSEC-status med dig eller online-verktyg.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-4', title: 'TLS best practices', title_nl: 'TLS-konfiguration enligt bästa praxis', description: 'TLS shall be configured with version 1.2 or higher, strong cipher suites, HSTS, and valid certificates.', description_nl: 'TLS ska konfigureras med version 1.2 eller högre, starka krypteringssviter, HSTS och giltiga certifikat.', category: 'Webbsäkerhet', subcategory: 'TLS', level: 'Teknisk', iso_mapping: '8.24', implementation_guidance: 'Använd TLS 1.2/1.3 med AEAD-sviter. Aktivera HSTS med lång max-age. Använd certifikat från betrodd CA.', verification_guidance: 'Testa med SSL Labs, testssl.sh eller likvärdigt verktyg. Sikta på A+ betyg.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-5', title: 'Web application security headers', title_nl: 'Säkerhetsrubriker för webbapplikationer', description: 'Web applications shall implement security headers: Content-Security-Policy, X-Frame-Options, X-Content-Type-Options, and Referrer-Policy.', description_nl: 'Webbapplikationer ska implementera säkerhetsrubriker: Content-Security-Policy, X-Frame-Options, X-Content-Type-Options och Referrer-Policy.', category: 'Webbsäkerhet', subcategory: 'HTTP-rubriker', level: 'Teknisk', iso_mapping: '8.26', implementation_guidance: 'Konfigurera CSP med restriktiv policy. Sätt X-Frame-Options till DENY. Aktivera alla rekommenderade säkerhetsrubriker.', verification_guidance: 'Skanna webbapplikationer med securityheaders.com eller likvärdigt verktyg.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-6', title: 'Multi-factor authentication for privileged access', title_nl: 'Flerfaktorsautentisering för privilegierad åtkomst', description: 'Multi-factor authentication shall be required for all administrative and privileged access to systems.', description_nl: 'Flerfaktorsautentisering ska krävas för all administrativ och privilegierad åtkomst till system.', category: 'Autentisering', subcategory: 'MFA', level: 'Teknisk', iso_mapping: '8.5', implementation_guidance: 'Kräv MFA (FIDO2/WebAuthn, TOTP eller smartkort) för alla administrativa konton, SSH-åtkomst och VPN.', verification_guidance: 'Kontrollera att MFA är aktiverat och inte kan kringgås för administrativa konton.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-7', title: 'Vulnerability management process', title_nl: 'Process för sårbarhetshantering', description: 'A vulnerability management process shall be in place with defined SLAs for remediation based on severity.', description_nl: 'En process för sårbarhetshantering ska finnas med definierade tidsramar för åtgärd baserat på allvarlighetsgrad.', category: 'Sårbarhetshantering', subcategory: 'Process', level: 'Teknisk', iso_mapping: '8.8', implementation_guidance: 'Definiera SLA: kritisk 72h, hög 14 dagar, medium 30 dagar, låg 90 dagar. Skanna veckovis.', verification_guidance: 'Granska skanningsrapporter och kontrollera att SLA följs.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-8', title: 'Ransomware protection', title_nl: 'Skydd mot utpressningsprogram', description: 'Organizations shall implement layered defenses against ransomware including offline backups, network segmentation, and email filtering.', description_nl: 'Organisationer ska implementera flerskiktat skydd mot utpressningsprogram inklusive offlinebackuper, nätverkssegmentering och e-postfiltrering.', category: 'Hotskydd', subcategory: 'Ransomware', level: 'Teknisk', iso_mapping: '8.7', implementation_guidance: 'Upprätthåll offlinebackuper (3-2-1-regeln). Segmentera nätverk. Filtrera e-postbilagor. Begränsa makron.', verification_guidance: 'Verifiera att offlinebackuper finns och att de kan återställas. Kontrollera nätverkssegmentering.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-9', title: 'Phishing protection', title_nl: 'Skydd mot nätfiske', description: 'Technical controls against phishing shall be implemented including email filtering, URL reputation checking, and user awareness training.', description_nl: 'Tekniska kontroller mot nätfiske ska implementeras inklusive e-postfiltrering, URL-rykteskontroll och användarutbildning.', category: 'Hotskydd', subcategory: 'Nätfiske', level: 'Teknisk', iso_mapping: '8.7', implementation_guidance: 'Implementera e-postfiltrering med sandboxning av bilagor. Genomför regelbundna nätfiskeövningar.', verification_guidance: 'Granska filtreringsstatistik och resultat från nätfiskeövningar.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-10', title: 'Secure Active Directory configuration', title_nl: 'Säker Active Directory-konfiguration', description: 'Active Directory shall be hardened with tiered administration, group policy enforcement, and regular privileged account audits.', description_nl: 'Active Directory ska härdas med nivåindelad administration, grupprincipstillämpning och regelbundna granskningar av privilegierade konton.', category: 'Identitet', subcategory: 'AD-härdning', level: 'Teknisk', iso_mapping: '8.2', implementation_guidance: 'Implementera Microsofts Tiered Administration-modell. Begränsa Domain Admin-konton. Aktivera LAPS.', verification_guidance: 'Granska AD-konfiguration och kontrollera att nivåindelning tillämpas.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-11', title: 'Log retention and analysis', title_nl: 'Logglagring och analys', description: 'Security logs shall be retained for a minimum period and analyzed regularly for anomalies.', description_nl: 'Säkerhetsloggar ska lagras under en minimiperiod och analyseras regelbundet för avvikelser.', category: 'Loggning', subcategory: 'Lagring', level: 'Teknisk', iso_mapping: '8.15', implementation_guidance: 'Lagra loggar minst 12 månader. Implementera automatiserad logganalys med SIEM. Definiera larmregler.', verification_guidance: 'Kontrollera att loggar lagras enligt krav och att larm fungerar.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-12', title: 'Incident response readiness', title_nl: 'Beredskap för incidenthantering', description: 'Organizations shall maintain incident response capabilities with defined procedures, trained personnel, and tested communication channels.', description_nl: 'Organisationer ska upprätthålla incidenthanteringsförmåga med definierade rutiner, utbildad personal och testade kommunikationskanaler.', category: 'Incidenthantering', subcategory: 'Beredskap', level: 'Teknisk', iso_mapping: '5.24', implementation_guidance: 'Upprätta och öva incidenthanteringsplan. Säkerställ att CERT-SE:s kontaktuppgifter är kända.', verification_guidance: 'Kontrollera att övningar genomförs och att kontaktuppgifter är aktuella.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-13', title: 'Supply chain security for software', title_nl: 'Leveranskedjansäkerhet för programvara', description: 'Software supply chain risks shall be managed through verification of software integrity and origin.', description_nl: 'Risker i programvaruleveranskedjan ska hanteras genom verifiering av programvarans integritet och ursprung.', category: 'Leveranskedja', subcategory: 'Programvara', level: 'Teknisk', iso_mapping: '5.21', implementation_guidance: 'Verifiera signaturer och checksummor vid programvaruinstallation. Inventera tredjepartsberoenden.', verification_guidance: 'Kontrollera att signaturer verifieras och att beroendeinventering genomförs.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-14', title: 'Secure remote work', title_nl: 'Säkert distansarbete', description: 'Remote work shall be conducted using organization-managed devices through encrypted connections with multi-factor authentication.', description_nl: 'Distansarbete ska ske med organisationshanterade enheter genom krypterade anslutningar med flerfaktorsautentisering.', category: 'Autentisering', subcategory: 'Distansarbete', level: 'Teknisk', iso_mapping: '6.7', implementation_guidance: 'Kräv VPN eller zero-trust-åtkomst med MFA. Använd bara organisationshanterade enheter.', verification_guidance: 'Kontrollera att distansarbetskonfigurationer uppfyller kraven.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-15', title: 'Cloud security configuration', title_nl: 'Säker molnkonfiguration', description: 'Cloud services shall be configured according to security best practices with proper access controls and monitoring.', description_nl: 'Molntjänster ska konfigureras enligt säkerhetspraxis med korrekt åtkomstkontroll och övervakning.', category: 'Molnsäkerhet', subcategory: 'Konfiguration', level: 'Teknisk', iso_mapping: '5.23', implementation_guidance: 'Följ CSA:s och leverantörens härdningsguider. Aktivera molnloggning. Begränsa API-nycklar.', verification_guidance: 'Genomför konfigurationsgranskningar av molntjänster.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-16', title: 'IoT and OT security', title_nl: 'IoT- och OT-säkerhet', description: 'IoT and operational technology devices shall be isolated in separate network segments with restricted access.', description_nl: 'IoT- och driftteknikenheter ska isoleras i separata nätverkssegment med begränsad åtkomst.', category: 'Nätverkssäkerhet', subcategory: 'IoT/OT', level: 'Teknisk', iso_mapping: '8.22', implementation_guidance: 'Segmentera IoT/OT-enheter i dedicerade VLAN. Begränsa kommunikation till nödvändiga flöden.', verification_guidance: 'Kontrollera nätverkssegmentering och trafikflöden för IoT/OT-enheter.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-17', title: 'Backup offline copy', title_nl: 'Offlinekopia av säkerhetskopiering', description: 'At least one backup copy shall be stored offline or air-gapped to protect against ransomware destruction of backups.', description_nl: 'Minst en säkerhetskopia ska lagras offline eller luftgapad för att skydda mot utpressningsprograms förstörelse av säkerhetskopior.', category: 'Hotskydd', subcategory: 'Backup', level: 'Teknisk', iso_mapping: '8.13', implementation_guidance: 'Implementera 3-2-1-backupstrategi med minst en offlinekopia. Testa återställning regelbundet.', verification_guidance: 'Verifiera att offlinekopior finns och att återställning fungerar.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-18', title: 'Password policy and credential management', title_nl: 'Lösenordspolicy och hantering av autentiseringsuppgifter', description: 'A password policy aligned with current best practices shall be enforced, preferring passwordless or MFA approaches.', description_nl: 'En lösenordspolicy i linje med aktuell praxis ska tillämpas, med företräde för lösenordslös eller MFA-baserad autentisering.', category: 'Autentisering', subcategory: 'Lösenord', level: 'Teknisk', iso_mapping: '5.17', implementation_guidance: 'Prioritera lösenordslös autentisering (FIDO2). Om lösenord krävs: minst 14 tecken, ingen periodisk rotation, kontroll mot läckta listor.', verification_guidance: 'Granska lösenordspolicy och kontrollera att den tillämpas tekniskt.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-19', title: 'DNS-over-HTTPS and DNS-over-TLS', title_nl: 'DNS-over-HTTPS och DNS-over-TLS', description: 'Organizations shall evaluate and consider deploying encrypted DNS (DoH/DoT) to protect DNS query privacy.', description_nl: 'Organisationer ska utvärdera och överväga att införa krypterad DNS (DoH/DoT) för att skydda DNS-frågornas integritet.', category: 'DNS-säkerhet', subcategory: 'Kryptering', level: 'Teknisk', iso_mapping: '8.20', implementation_guidance: 'Utvärdera DoH/DoT för interna resolvers. Konfigurera klienter för krypterad DNS. Övervaka DNS-trafik.', verification_guidance: 'Kontrollera att krypterad DNS är konfigurerad och fungerar.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-20', title: 'Zero trust network architecture', title_nl: 'Nätverksarkitektur med nollförtroende', description: 'Organizations shall plan and move toward a zero trust architecture where no network location is implicitly trusted.', description_nl: 'Organisationer ska planera och gå mot en nollförtroendearkitektur där ingen nätverksplats implicit betros.', category: 'Nätverkssäkerhet', subcategory: 'Arkitektur', level: 'Teknisk', iso_mapping: '8.20', implementation_guidance: 'Identifiera skyddsvärda resurser. Implementera mikrosegmentering. Tillämpa identitetsbaserad åtkomstkontroll.', verification_guidance: 'Granska nätverksarkitekturen och kontrollera att nollförtroende-principer tillämpas.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-21', title: 'Container and orchestration security', title_nl: 'Container- och orkestreringsäkerhet', description: 'Container runtimes and orchestration platforms shall be hardened with image scanning, least-privilege pods, and network policies.', description_nl: 'Containermiljöer och orkestreringsplattformar ska härdas med bildskanningar, minsta-behörighets-poddar och nätverkspolicyer.', category: 'Molnsäkerhet', subcategory: 'Container', level: 'Teknisk', iso_mapping: '8.9', implementation_guidance: 'Skanna containerbilder. Kör som icke-root. Tillämpa Kubernetes network policies. Begränsa privilegier.', verification_guidance: 'Kontrollera att containerbilder skannas och att härdningsriktlinjer tillämpas.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-22', title: 'Privileged access management', title_nl: 'Hantering av privilegierad åtkomst', description: 'Privileged accounts shall be managed through a PAM solution with session recording and just-in-time access.', description_nl: 'Privilegierade konton ska hanteras genom en PAM-lösning med sessionsinspelning och just-in-time-åtkomst.', category: 'Identitet', subcategory: 'PAM', level: 'Teknisk', iso_mapping: '8.2', implementation_guidance: 'Implementera PAM-lösning för administrativa konton. Aktivera sessionsinspelning. Tillämpa JIT-åtkomst.', verification_guidance: 'Kontrollera att PAM-lösning är implementerad och att sessioner loggas.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-23', title: 'Security information and event management', title_nl: 'SIEM-lösning', description: 'Organizations shall deploy a SIEM solution to correlate security events across systems.', description_nl: 'Organisationer ska implementera en SIEM-lösning för att korrelera säkerhetshändelser från olika system.', category: 'Loggning', subcategory: 'SIEM', level: 'Teknisk', iso_mapping: '8.16', implementation_guidance: 'Implementera SIEM med korrelationsregler för vanliga attackmönster. Integrera loggar från alla kritiska system.', verification_guidance: 'Kontrollera att SIEM-lösning finns och att relevanta loggar integreras.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-24', title: 'DDoS protection', title_nl: 'DDoS-skydd', description: 'Internet-facing services shall have DDoS mitigation capabilities through network or application-level protection.', description_nl: 'Internetexponerade tjänster ska ha DDoS-skyddsförmåga genom nätverks- eller applikationsnivåskydd.', category: 'Nätverkssäkerhet', subcategory: 'DDoS', level: 'Teknisk', iso_mapping: '8.20', implementation_guidance: 'Implementera DDoS-skydd via CDN, WAF eller dedikerad DDoS-skyddstjänst. Definiera eskaleringsrutiner.', verification_guidance: 'Kontrollera att DDoS-skydd är konfigurerat och att eskaleringsrutiner finns.', source_url: 'https://www.cert.se/rekommendationer/' },
  { control_number: 'CSE-25', title: 'Secure software update mechanism', title_nl: 'Säker programuppdateringsmekanism', description: 'Software update mechanisms shall verify integrity and authenticity before applying updates.', description_nl: 'Mekanismer för programuppdateringar ska verifiera integritet och autenticitet innan uppdateringar tillämpas.', category: 'Leveranskedja', subcategory: 'Uppdatering', level: 'Teknisk', iso_mapping: '8.19', implementation_guidance: 'Verifiera digitala signaturer vid uppdatering. Använd HTTPS för nedladdning. Testa uppdateringar i staging.', verification_guidance: 'Kontrollera att signaturverifiering sker vid uppdateringar.', source_url: 'https://www.cert.se/rekommendationer/' },
];

async function main(): Promise<void> {
  console.log('CERT-SE Rekommendationer Ingestion Script');
  console.log('==========================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} recommendations.`);

  const output = {
    framework: {
      id: 'cert-se-rekommendationer',
      name: 'CERT-SE Technical Recommendations',
      name_nl: 'CERT-SE tekniska rekommendationer',
      issuing_body: 'CERT-SE (Myndigheten för samhällsskydd och beredskap)',
      version: '2024',
      effective_date: '2024-01-01',
      scope: 'Technical security recommendations for Swedish organizations covering network security, email security, web security, authentication, and incident response',
      scope_sectors: ['government', 'digital_infrastructure'],
      structure_description: 'Organized by technical domain: network security, email security, DNS, web security, authentication, vulnerability management, threat protection, logging, incident response, and cloud security.',
      source_url: 'https://www.cert.se/rekommendationer/',
      license: 'Public sector publication',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
