// scripts/ingest-msb-metodstod.ts
// MSB Systematiskt informationssäkerhetsarbete (Metodstöd)
// Source: https://www.informationssakerhet.se/metodstod/
// Authority: Myndigheten för samhällsskydd och beredskap (MSB)
//
// MSB's methodology for systematic information security work, based on ISO 27001.
// Covers 9 areas: ledning, organisation, riskhantering, klassificering,
// tekniska åtgärder, administrativa åtgärder, incidenthantering,
// kontinuitetshantering, uppföljning.

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'msb-metodstod.json');

interface Control {
  control_number: string;
  title: string | null;
  title_nl: string;
  description: string | null;
  description_nl: string;
  category: string;
  subcategory: string | null;
  level: string | null;
  iso_mapping: string | null;
  implementation_guidance: string | null;
  verification_guidance: string | null;
  source_url: string | null;
}

const controls: Control[] = [
  // ── Ledning och styrning (Management and governance) ─────────────────────
  {
    control_number: 'L1',
    title: 'Management commitment to information security',
    title_nl: 'Ledningens engagemang för informationssäkerhet',
    description: 'Top management shall demonstrate leadership and commitment to information security by establishing an information security policy, ensuring information security objectives are set, and providing necessary resources.',
    description_nl: 'Ledningen ska visa ledarskap och engagemang för informationssäkerhet genom att upprätta en informationssäkerhetspolicy, säkerställa att mål för informationssäkerhet fastställs och tillhandahålla nödvändiga resurser.',
    category: 'Ledning och styrning',
    subcategory: 'Ledningsengagemang',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Ledningen bör formellt godkänna informationssäkerhetspolicyn och regelbundet följa upp säkerhetsarbetet. Inkludera informationssäkerhet som en stående punkt på ledningsgruppens agenda.',
    verification_guidance: 'Kontrollera att ledningen har undertecknat policyn, att resurser tilldelats och att regelbundna uppföljningsmöten genomförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L2',
    title: 'Information security policy',
    title_nl: 'Informationssäkerhetspolicy',
    description: 'An information security policy shall be established, approved by management, published, and communicated to all employees and relevant external parties.',
    description_nl: 'En informationssäkerhetspolicy ska upprättas, godkännas av ledningen, publiceras och kommuniceras till alla anställda och relevanta externa parter.',
    category: 'Ledning och styrning',
    subcategory: 'Policy',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Policyn ska ange organisationens övergripande inriktning för informationssäkerhet, vara anpassad till verksamhetens behov och vara tillgänglig för alla berörda.',
    verification_guidance: 'Verifiera att policydokumentet finns, är daterat, godkänt av ledningen och tillgängligt för alla medarbetare.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L3',
    title: 'Information security roles and responsibilities',
    title_nl: 'Roller och ansvar för informationssäkerhet',
    description: 'Information security roles and responsibilities shall be defined and allocated. The organization shall appoint a CISO or equivalent function.',
    description_nl: 'Roller och ansvar för informationssäkerhet ska definieras och tilldelas. Organisationen ska utse en CISO eller motsvarande funktion.',
    category: 'Ledning och styrning',
    subcategory: 'Roller',
    level: null,
    iso_mapping: '5.2',
    implementation_guidance: 'Definiera tydliga roller som informationssäkerhetsansvarig (CISO), informationsägare, systemägare och IT-säkerhetsansvarig. Dokumentera ansvar i befattningsbeskrivningar.',
    verification_guidance: 'Kontrollera att rollbeskrivningar finns dokumenterade och att personerna som tilldelats rollerna är informerade om sitt ansvar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L4',
    title: 'Resource allocation for information security',
    title_nl: 'Resurstilldelning för informationssäkerhet',
    description: 'Adequate resources shall be allocated for information security work, including personnel, budget, and time.',
    description_nl: 'Tillräckliga resurser ska tilldelas för informationssäkerhetsarbetet, inklusive personal, budget och tid.',
    category: 'Ledning och styrning',
    subcategory: 'Resurser',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Säkerställ att det finns en dedikerad budget för informationssäkerhet, att personal har tillräcklig tid avsatt och att nödvändig kompetens finns tillgänglig.',
    verification_guidance: 'Granska budgetdokument och resursplaner. Verifiera att säkerhetsansvariga har tillräckligt med tid avsatt.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L5',
    title: 'Information security in governance framework',
    title_nl: 'Informationssäkerhet i styrningsramverket',
    description: 'Information security shall be integrated into the organization\'s governance framework, including strategic planning and decision-making processes.',
    description_nl: 'Informationssäkerhet ska integreras i organisationens styrningsramverk, inklusive strategisk planering och beslutsprocesser.',
    category: 'Ledning och styrning',
    subcategory: 'Styrning',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Integrera informationssäkerhet i befintliga styrprocesser som verksamhetsplanering, budgetarbete och interna revisioner.',
    verification_guidance: 'Kontrollera att informationssäkerhet ingår i verksamhetsplaner och att säkerhetsaspekter beaktas vid större beslut.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L6',
    title: 'Legal and regulatory compliance for information security',
    title_nl: 'Efterlevnad av lagar och förordningar inom informationssäkerhet',
    description: 'The organization shall identify and comply with applicable legal, regulatory, and contractual requirements related to information security.',
    description_nl: 'Organisationen ska identifiera och efterleva tillämpliga lagar, förordningar och avtalsmässiga krav relaterade till informationssäkerhet.',
    category: 'Ledning och styrning',
    subcategory: 'Regelefterlevnad',
    level: null,
    iso_mapping: '5.31',
    implementation_guidance: 'Kartlägg tillämpliga krav från NIS2-direktivet, dataskyddsförordningen (GDPR), säkerhetsskyddslagen, och MSBFS-föreskrifter. Upprätta ett kravregister.',
    verification_guidance: 'Granska kravregistret och verifiera att det är uppdaterat. Kontrollera att relevanta lagar och förordningar är identifierade.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L7',
    title: 'Contact with authorities',
    title_nl: 'Kontakt med myndigheter',
    description: 'Appropriate contacts with relevant authorities shall be maintained, including MSB, CERT-SE, and supervisory bodies.',
    description_nl: 'Lämpliga kontakter med relevanta myndigheter ska upprätthållas, inklusive MSB, CERT-SE och tillsynsmyndigheter.',
    category: 'Ledning och styrning',
    subcategory: 'Extern kontakt',
    level: null,
    iso_mapping: '5.5',
    implementation_guidance: 'Upprätta en kontaktlista för relevanta myndigheter och organisationer. Utse ansvariga för kontakten med respektive myndighet.',
    verification_guidance: 'Verifiera att kontaktlistan finns och är uppdaterad. Kontrollera att rapporteringsvägar till MSB och CERT-SE är kända.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L8',
    title: 'Information security in project management',
    title_nl: 'Informationssäkerhet i projektledning',
    description: 'Information security shall be addressed in project management, regardless of the type of project.',
    description_nl: 'Informationssäkerhet ska beaktas i projektledning, oavsett typ av projekt.',
    category: 'Ledning och styrning',
    subcategory: 'Projekt',
    level: null,
    iso_mapping: '5.8',
    implementation_guidance: 'Inkludera säkerhetskrav i projektmodellen. Genomför riskbedömning i tidiga projektskeden och säkerhetsavstämning vid projektavslut.',
    verification_guidance: 'Granska projektdokumentation för att verifiera att säkerhetsaspekter beaktas.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L9',
    title: 'Segregation of duties',
    title_nl: 'Uppdelning av arbetsuppgifter',
    description: 'Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse.',
    description_nl: 'Motstridiga arbetsuppgifter och ansvarsområden ska separeras för att minska risken för obehörig eller oavsiktlig ändring eller missbruk.',
    category: 'Ledning och styrning',
    subcategory: 'Ansvarsfördelning',
    level: null,
    iso_mapping: '5.3',
    implementation_guidance: 'Identifiera kritiska processer där uppdelning av ansvar behövs. Dokumentera vilka roller som inte får kombineras.',
    verification_guidance: 'Granska behörighetsmatriser och rollfördelning. Verifiera att inga konflikterande kombinationer förekommer.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L10',
    title: 'Management review of information security',
    title_nl: 'Ledningens genomgång av informationssäkerhet',
    description: 'Management shall review the information security management system at planned intervals to ensure its continued suitability, adequacy, and effectiveness.',
    description_nl: 'Ledningen ska genomgå informationssäkerhetsarbetet vid planerade intervaller för att säkerställa dess fortsatta lämplighet, tillräcklighet och effektivitet.',
    category: 'Ledning och styrning',
    subcategory: 'Uppföljning',
    level: null,
    iso_mapping: '5.36',
    implementation_guidance: 'Planera ledningens genomgång minst en gång per år. Inkludera resultat av revisioner, incidentstatistik och statusuppdateringar.',
    verification_guidance: 'Kontrollera att protokoll från ledningens genomgång finns dokumenterade och att åtgärder har följts upp.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L11',
    title: 'Information security objectives',
    title_nl: 'Mål för informationssäkerhet',
    description: 'Information security objectives shall be established at relevant functions and levels, consistent with the information security policy.',
    description_nl: 'Mål för informationssäkerhet ska upprättas för relevanta funktioner och nivåer, i enlighet med informationssäkerhetspolicyn.',
    category: 'Ledning och styrning',
    subcategory: 'Mål',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Formulera mätbara mål som är kopplade till policyn. Följ upp målen regelbundet och redovisa resultat till ledningen.',
    verification_guidance: 'Verifiera att dokumenterade mål finns och att de följs upp med mätetal.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Organisation ─────────────────────────────────────────────────────────
  {
    control_number: 'O1',
    title: 'Information security organization',
    title_nl: 'Informationssäkerhetsorganisation',
    description: 'An information security organization shall be established with clear reporting lines and authority to coordinate security activities.',
    description_nl: 'En informationssäkerhetsorganisation ska upprättas med tydliga rapporteringsvägar och befogenhet att samordna säkerhetsaktiviteter.',
    category: 'Organisation',
    subcategory: 'Organisationsstruktur',
    level: null,
    iso_mapping: '5.2',
    implementation_guidance: 'Upprätta en säkerhetsorganisation med roller som CISO, informationsägare och säkerhetssamordnare. Definiera rapporteringslinjer.',
    verification_guidance: 'Granska organisationsschema och kontrollera att säkerhetsorganisationen är dokumenterad.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O2',
    title: 'Information security competence',
    title_nl: 'Kompetens inom informationssäkerhet',
    description: 'The organization shall ensure that persons working with information security have appropriate competence through education, training, or experience.',
    description_nl: 'Organisationen ska säkerställa att personer som arbetar med informationssäkerhet har lämplig kompetens genom utbildning, träning eller erfarenhet.',
    category: 'Organisation',
    subcategory: 'Kompetens',
    level: null,
    iso_mapping: '6.3',
    implementation_guidance: 'Kartlägg kompetensbehov för informationssäkerhet. Upprätta en utbildningsplan och genomför regelbundna kompetenshöjande insatser.',
    verification_guidance: 'Kontrollera att utbildningsplaner finns och att personal har genomgått relevanta utbildningar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O3',
    title: 'Information security awareness',
    title_nl: 'Säkerhetsmedvetenhet',
    description: 'All employees shall receive appropriate information security awareness training relevant to their work function.',
    description_nl: 'Alla anställda ska genomgå lämplig säkerhetsmedvetenhetsutbildning anpassad till deras arbetsuppgifter.',
    category: 'Organisation',
    subcategory: 'Medvetenhet',
    level: null,
    iso_mapping: '6.3',
    implementation_guidance: 'Genomför regelbundna medvetenhetsutbildningar. Anpassa innehållet till olika målgrupper inom organisationen. Inkludera övningar med nätfisketest.',
    verification_guidance: 'Granska utbildningsregister och deltagarstatistik. Verifiera att utbildningen är regelbunden.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O4',
    title: 'Communication of information security',
    title_nl: 'Kommunikation av informationssäkerhet',
    description: 'The organization shall determine the need for internal and external communications relevant to information security.',
    description_nl: 'Organisationen ska fastställa behovet av intern och extern kommunikation som är relevant för informationssäkerhet.',
    category: 'Organisation',
    subcategory: 'Kommunikation',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Upprätta en kommunikationsplan för informationssäkerhet som omfattar kanaler, frekvens och mottagare.',
    verification_guidance: 'Kontrollera att kommunikationsplanen finns och att informationen når alla berörda.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O5',
    title: 'Documented information for the security management system',
    title_nl: 'Dokumenterad information för säkerhetsledningssystemet',
    description: 'The organization shall maintain documented information required by the information security management system, including policies, procedures, and records.',
    description_nl: 'Organisationen ska upprätthålla dokumenterad information som krävs av säkerhetsledningssystemet, inklusive policyer, rutiner och register.',
    category: 'Organisation',
    subcategory: 'Dokumentation',
    level: null,
    iso_mapping: '5.37',
    implementation_guidance: 'Upprätta en dokumentstruktur med policyer, riktlinjer, rutiner och instruktioner. Versionhantera dokument och säkerställ tillgänglighet.',
    verification_guidance: 'Granska dokumentstrukturen. Kontrollera versionering och att dokument är aktuella.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O6',
    title: 'Screening of personnel',
    title_nl: 'Bakgrundskontroll av personal',
    description: 'Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations, and proportional to the information they will access.',
    description_nl: 'Bakgrundskontroller av alla kandidater till anställning ska genomföras i enlighet med relevanta lagar, förordningar och i proportion till den information de kommer att ha tillgång till.',
    category: 'Organisation',
    subcategory: 'Personal',
    level: null,
    iso_mapping: '6.1',
    implementation_guidance: 'Genomför bakgrundskontroller vid nyanställning som motsvarar befattningens krav. Beakta krav från säkerhetsskyddslagen vid behov.',
    verification_guidance: 'Verifiera att rutiner för bakgrundskontroller finns dokumenterade och följs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O7',
    title: 'Terms and conditions of employment',
    title_nl: 'Anställningsvillkor',
    description: 'Employment agreements shall state the employee\'s and the organization\'s responsibilities for information security.',
    description_nl: 'Anställningsavtal ska ange den anställdes och organisationens ansvar för informationssäkerhet.',
    category: 'Organisation',
    subcategory: 'Personal',
    level: null,
    iso_mapping: '6.2',
    implementation_guidance: 'Inkludera säkerhetsklausuler i anställningsavtal. Säkerställ att sekretessavtal undertecknas.',
    verification_guidance: 'Granska anställningsavtalsmallar och kontrollera att säkerhetsklausuler ingår.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O8',
    title: 'Supplier information security',
    title_nl: 'Informationssäkerhet hos leverantörer',
    description: 'Information security requirements for mitigating the risks associated with supplier access shall be established and agreed with each supplier.',
    description_nl: 'Krav på informationssäkerhet för att minska riskerna med leverantörers tillgång ska upprättas och avtalas med varje leverantör.',
    category: 'Organisation',
    subcategory: 'Leverantörer',
    level: null,
    iso_mapping: '5.19',
    implementation_guidance: 'Upprätta krav på informationssäkerhet i leverantörsavtal. Genomför leverantörsbedömningar och regelbundna uppföljningar.',
    verification_guidance: 'Granska leverantörsavtal för säkerhetsklausuler och kontrollera uppföljningsrutiner.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O9',
    title: 'Remote working security',
    title_nl: 'Säkerhet vid distansarbete',
    description: 'Security measures shall be implemented when personnel are working remotely to protect information accessed, processed, or stored outside the organization premises.',
    description_nl: 'Säkerhetsåtgärder ska vidtas vid distansarbete för att skydda information som behandlas eller lagras utanför organisationens lokaler.',
    category: 'Organisation',
    subcategory: 'Distansarbete',
    level: null,
    iso_mapping: '6.7',
    implementation_guidance: 'Upprätta riktlinjer för distansarbete som omfattar krav på VPN, kryptering, och säker hantering av information i hemmiljö.',
    verification_guidance: 'Kontrollera att riktlinjer finns och att tekniska skydd som VPN är implementerade.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'O10',
    title: 'Cloud service security',
    title_nl: 'Säkerhet vid molntjänster',
    description: 'Processes for acquisition, use, management, and exit from cloud services shall be established in accordance with information security requirements.',
    description_nl: 'Processer för anskaffning, användning, hantering och avslut av molntjänster ska upprättas i enlighet med informationssäkerhetskrav.',
    category: 'Organisation',
    subcategory: 'Molntjänster',
    level: null,
    iso_mapping: '5.23',
    implementation_guidance: 'Upprätta krav och utvärderingsprocesser för molntjänster. Bedöm risker kopplade till datalokaliserring, jurisdiktion och leverantörsinlåsning.',
    verification_guidance: 'Granska avtal och riskbedömningar för använda molntjänster.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Riskhantering (Risk management) ──────────────────────────────────────
  {
    control_number: 'R1',
    title: 'Risk assessment process',
    title_nl: 'Process för riskbedömning',
    description: 'The organization shall define and apply an information security risk assessment process that identifies, analyzes, and evaluates risks.',
    description_nl: 'Organisationen ska definiera och tillämpa en process för riskbedömning av informationssäkerhet som identifierar, analyserar och utvärderar risker.',
    category: 'Riskhantering',
    subcategory: 'Riskbedömning',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Upprätta en riskbedömningsmetod som inkluderar identifiering av informationstillgångar, hot, sårbarheter och konsekvenser. Använd en konsekvent bedömningsskala.',
    verification_guidance: 'Granska riskbedömningsmetoden och kontrollera att den tillämpas regelbundet.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'R2',
    title: 'Risk treatment',
    title_nl: 'Riskbehandling',
    description: 'A risk treatment plan shall be developed to address identified risks, including selection of appropriate controls.',
    description_nl: 'En riskbehandlingsplan ska upprättas för att hantera identifierade risker, inklusive val av lämpliga säkerhetsåtgärder.',
    category: 'Riskhantering',
    subcategory: 'Riskbehandling',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Upprätta en riskbehandlingsplan som dokumenterar valda åtgärder, ansvariga och tidplaner. Prioritera åtgärder baserat på risknivå.',
    verification_guidance: 'Kontrollera att riskbehandlingsplanen finns och att åtgärder genomförs enligt plan.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'R3',
    title: 'Risk acceptance',
    title_nl: 'Riskacceptans',
    description: 'Residual risks shall be formally accepted by appropriate management levels with documented justification.',
    description_nl: 'Kvarvarande risker ska formellt accepteras av lämplig ledningsnivå med dokumenterad motivering.',
    category: 'Riskhantering',
    subcategory: 'Riskacceptans',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Definiera acceptanskriterier och beslutsprocess för kvarvarande risker. Dokumentera vilka risker som accepteras och av vem.',
    verification_guidance: 'Granska riskregistret och kontrollera att accepterade risker är dokumenterade med godkännande.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'R4',
    title: 'Threat intelligence',
    title_nl: 'Hotinformation',
    description: 'Information relating to information security threats shall be collected and analyzed to produce relevant threat intelligence.',
    description_nl: 'Information om informationssäkerhetshot ska samlas in och analyseras för att producera relevant hotinformation.',
    category: 'Riskhantering',
    subcategory: 'Hotbild',
    level: null,
    iso_mapping: '5.7',
    implementation_guidance: 'Prenumerera på hotrapporter från CERT-SE och andra relevanta källor. Analysera hotinformation i relation till organisationens tillgångar.',
    verification_guidance: 'Kontrollera att organisationen har tillgång till hotinformation och att den beaktas i riskbedömningar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'R5',
    title: 'Asset inventory',
    title_nl: 'Tillgångsregister',
    description: 'Information and other associated assets shall be identified and an inventory of these assets maintained.',
    description_nl: 'Informationstillgångar och andra relaterade tillgångar ska identifieras och ett tillgångsregister ska upprätthållas.',
    category: 'Riskhantering',
    subcategory: 'Tillgångar',
    level: null,
    iso_mapping: '5.9',
    implementation_guidance: 'Upprätta och upprätthåll ett register över informationstillgångar. Inkludera tillgångens ägare, klassificering och beroenden.',
    verification_guidance: 'Granska tillgångsregistret och kontrollera att det är komplett och aktuellt.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'R6',
    title: 'Risk assessment periodic review',
    title_nl: 'Regelbunden översyn av riskbedömning',
    description: 'Risk assessments shall be reviewed and updated at planned intervals or when significant changes occur.',
    description_nl: 'Riskbedömningar ska granskas och uppdateras vid planerade intervaller eller vid väsentliga förändringar.',
    category: 'Riskhantering',
    subcategory: 'Uppföljning',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Genomför översyn av riskbedömningar minst årligen. Utlös ny bedömning vid större organisatoriska eller tekniska förändringar.',
    verification_guidance: 'Kontrollera att riskbedömningar uppdateras regelbundet och att förändringar dokumenteras.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'R7',
    title: 'Supply chain risk management',
    title_nl: 'Riskhantering i leveranskedjan',
    description: 'Risks related to the ICT supply chain shall be managed by agreeing on and monitoring information security requirements with suppliers.',
    description_nl: 'Risker relaterade till leveranskedjan för IT ska hanteras genom att avtala om och övervaka informationssäkerhetskrav med leverantörer.',
    category: 'Riskhantering',
    subcategory: 'Leveranskedja',
    level: null,
    iso_mapping: '5.21',
    implementation_guidance: 'Bedöm risker i leveranskedjan, inklusive programvaruleverantörer och molntjänstleverantörer. Ställ krav i avtal och genomför uppföljningar.',
    verification_guidance: 'Granska leverantörsavtal och uppföljningsprotokoll för IT-leveranskedjan.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Klassificering (Classification) ──────────────────────────────────────
  {
    control_number: 'K1',
    title: 'Information classification',
    title_nl: 'Informationsklassificering',
    description: 'Information shall be classified in terms of legal requirements, value, criticality, and sensitivity to unauthorized disclosure or modification.',
    description_nl: 'Information ska klassificeras med hänsyn till rättsliga krav, värde, kritikalitet och känslighet för obehörigt röjande eller ändring.',
    category: 'Klassificering',
    subcategory: 'Klassificering',
    level: null,
    iso_mapping: '5.12',
    implementation_guidance: 'Upprätta en klassificeringsmodell med nivåer baserade på konfidentialitet, riktighet och tillgänglighet. Tillämpa MSB:s rekommenderade modell.',
    verification_guidance: 'Kontrollera att en klassificeringsmodell finns och att information klassificeras i praktiken.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'K2',
    title: 'Information handling rules',
    title_nl: 'Regler för informationshantering',
    description: 'Procedures for handling information shall be developed and implemented in accordance with the classification scheme.',
    description_nl: 'Rutiner för informationshantering ska utvecklas och tillämpas i enlighet med klassificeringsmodellen.',
    category: 'Klassificering',
    subcategory: 'Hanteringsregler',
    level: null,
    iso_mapping: '5.10',
    implementation_guidance: 'Upprätta hanteringsregler per klassificeringsnivå som anger hur information ska lagras, överföras, kopieras och förstöras.',
    verification_guidance: 'Granska hanteringsregler och kontrollera att de är kända av medarbetarna.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'K3',
    title: 'Information labeling',
    title_nl: 'Märkning av information',
    description: 'An appropriate set of procedures for information labeling shall be developed and implemented in accordance with the classification scheme.',
    description_nl: 'Lämpliga rutiner för märkning av information ska utvecklas och tillämpas i enlighet med klassificeringsmodellen.',
    category: 'Klassificering',
    subcategory: 'Märkning',
    level: null,
    iso_mapping: '5.13',
    implementation_guidance: 'Upprätta rutiner för märkning av dokument, e-post och lagringsmedia. Inkludera digital och fysisk märkning.',
    verification_guidance: 'Kontrollera att märkningsrutiner följs genom stickprov på dokument och e-post.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'K4',
    title: 'Information transfer security',
    title_nl: 'Säker informationsöverföring',
    description: 'Formal transfer policies, procedures, and controls shall be in place to protect information transferred through all types of communication channels.',
    description_nl: 'Formella regler, rutiner och kontroller ska finnas för att skydda information som överförs genom alla typer av kommunikationskanaler.',
    category: 'Klassificering',
    subcategory: 'Överföring',
    level: null,
    iso_mapping: '5.14',
    implementation_guidance: 'Upprätta regler för säker informationsöverföring. Använd kryptering vid överföring av känslig information. Definiera godkända överföringsmetoder.',
    verification_guidance: 'Kontrollera att regler för informationsöverföring finns och att kryptering används vid behov.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'K5',
    title: 'Return of assets at employment termination',
    title_nl: 'Återlämning av tillgångar vid anställningens upphörande',
    description: 'All employees and external party users shall return all organizational assets in their possession upon termination of employment or contract.',
    description_nl: 'Alla anställda och externa parter ska återlämna alla organisationens tillgångar vid anställningens eller avtalets upphörande.',
    category: 'Klassificering',
    subcategory: 'Återlämning',
    level: null,
    iso_mapping: '5.11',
    implementation_guidance: 'Upprätta en checklista för återlämning av tillgångar vid avslut. Inkludera IT-utrustning, behörigheter och informationsbärare.',
    verification_guidance: 'Granska avslutschecklistan och verifiera att den används vid personalförändringar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Tekniska åtgärder (Technical measures) ───────────────────────────────
  {
    control_number: 'T1',
    title: 'Access control policy',
    title_nl: 'Åtkomstkontrollpolicy',
    description: 'An access control policy shall be established and implemented based on business and information security requirements.',
    description_nl: 'En åtkomstkontrollpolicy ska upprättas och tillämpas baserat på verksamhetens och informationssäkerhetens krav.',
    category: 'Tekniska åtgärder',
    subcategory: 'Åtkomstkontroll',
    level: null,
    iso_mapping: '5.15',
    implementation_guidance: 'Upprätta en policy som definierar regler för tilldelning, granskning och borttagning av behörigheter. Tillämpa principen om minsta möjliga behörighet.',
    verification_guidance: 'Granska behörighetspolicyn och kontrollera att den tillämpas. Genomför behörighetsgranskningar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T2',
    title: 'Network security',
    title_nl: 'Nätverkssäkerhet',
    description: 'Networks shall be managed and controlled to protect information in systems and applications. Network segmentation shall be implemented.',
    description_nl: 'Nätverk ska hanteras och kontrolleras för att skydda information i system och applikationer. Nätverkssegmentering ska implementeras.',
    category: 'Tekniska åtgärder',
    subcategory: 'Nätverk',
    level: null,
    iso_mapping: '8.20',
    implementation_guidance: 'Implementera nätverkssegmentering, brandväggar och intrångsdetektering. Använd separata nät för olika säkerhetsnivåer.',
    verification_guidance: 'Granska nätverksarkitektur och brandväggsregler. Verifiera segmentering med skanningar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T3',
    title: 'Encryption and cryptographic controls',
    title_nl: 'Kryptering och kryptografiska kontroller',
    description: 'A policy on the use of cryptographic controls for protection of information shall be developed and implemented.',
    description_nl: 'En policy för användning av kryptografiska kontroller för att skydda information ska utvecklas och tillämpas.',
    category: 'Tekniska åtgärder',
    subcategory: 'Kryptering',
    level: null,
    iso_mapping: '8.24',
    implementation_guidance: 'Upprätta en krypteringspolicy som anger vilka algoritmer och nyckellängder som ska användas. Kryptera känslig data i vila och under överföring.',
    verification_guidance: 'Kontrollera att kryptering används enligt policyn. Granska konfigurationer och certifikat.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T4',
    title: 'Logging and monitoring',
    title_nl: 'Loggning och övervakning',
    description: 'Event logs recording user activities, exceptions, faults, and information security events shall be produced, kept, protected, and regularly reviewed.',
    description_nl: 'Händelseloggar som registrerar användaraktiviteter, undantag, fel och informationssäkerhetshändelser ska produceras, förvaras, skyddas och regelbundet granskas.',
    category: 'Tekniska åtgärder',
    subcategory: 'Loggning',
    level: null,
    iso_mapping: '8.15',
    implementation_guidance: 'Implementera centraliserad loggning med skydd mot manipulation. Logga inloggningar, behörighetsändringar, systemhändelser och säkerhetsincidenter.',
    verification_guidance: 'Granska loggningskonfigurationer och kontrollera att loggar granskas regelbundet.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T5',
    title: 'Identity management',
    title_nl: 'Identitetshantering',
    description: 'The full life cycle of identities shall be managed, including registration, authentication, and deprovisioning.',
    description_nl: 'Hela livscykeln för identiteter ska hanteras, inklusive registrering, autentisering och avregistrering.',
    category: 'Tekniska åtgärder',
    subcategory: 'Identiteter',
    level: null,
    iso_mapping: '5.16',
    implementation_guidance: 'Implementera en process för identitetshantering som omfattar skapande, granskning och borttagning av användarkonton.',
    verification_guidance: 'Granska processen för identitetshantering och kontrollera att avregistrering sker vid behov.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T6',
    title: 'Strong authentication',
    title_nl: 'Stark autentisering',
    description: 'Multi-factor authentication shall be implemented for access to critical systems and remote access.',
    description_nl: 'Flerfaktorsautentisering ska implementeras för åtkomst till kritiska system och vid fjärråtkomst.',
    category: 'Tekniska åtgärder',
    subcategory: 'Autentisering',
    level: null,
    iso_mapping: '8.5',
    implementation_guidance: 'Implementera flerfaktorsautentisering (MFA) för alla administrativa konton, fjärråtkomst och åtkomst till känsliga system.',
    verification_guidance: 'Kontrollera att MFA är aktiverat för definierade system. Testa autentiseringsprocessen.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T7',
    title: 'Privileged access management',
    title_nl: 'Hantering av privilegierad åtkomst',
    description: 'The allocation and use of privileged access rights shall be restricted and controlled.',
    description_nl: 'Tilldelning och användning av privilegierade åtkomsträttigheter ska begränsas och kontrolleras.',
    category: 'Tekniska åtgärder',
    subcategory: 'Behörigheter',
    level: null,
    iso_mapping: '8.2',
    implementation_guidance: 'Begränsa antalet privilegierade konton. Implementera just-in-time-åtkomst och använd separata administrativa konton.',
    verification_guidance: 'Granska lista över privilegierade konton och kontrollera att de begränsas till behov.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T8',
    title: 'Vulnerability management',
    title_nl: 'Sårbarhetshantering',
    description: 'Information about technical vulnerabilities of information systems in use shall be obtained and appropriate measures taken to address the associated risk.',
    description_nl: 'Information om tekniska sårbarheter i använda informationssystem ska inhämtas och lämpliga åtgärder vidtas för att hantera risken.',
    category: 'Tekniska åtgärder',
    subcategory: 'Sårbarheter',
    level: null,
    iso_mapping: '8.8',
    implementation_guidance: 'Implementera en process för sårbarhetshantering med regelbundna skanningar. Upprätta tidsramar för åtgärd baserat på allvarlighetsgrad.',
    verification_guidance: 'Granska sårbarhetsrapporter och kontrollera att åtgärder genomförs inom uppsatta tidsramar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T9',
    title: 'Malware protection',
    title_nl: 'Skydd mot skadlig kod',
    description: 'Protection against malware shall be implemented and supported by appropriate user awareness.',
    description_nl: 'Skydd mot skadlig kod ska implementeras och stödjas av lämplig användarmedvetenhet.',
    category: 'Tekniska åtgärder',
    subcategory: 'Skadlig kod',
    level: null,
    iso_mapping: '8.7',
    implementation_guidance: 'Installera och uppdatera skydd mot skadlig kod på alla ändpunkter och servrar. Kombinera med användarutbildning.',
    verification_guidance: 'Kontrollera att skyddet är installerat, uppdaterat och aktivt på alla enheter.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T10',
    title: 'Backup',
    title_nl: 'Säkerhetskopiering',
    description: 'Backup copies of information, software, and system images shall be taken and tested regularly.',
    description_nl: 'Säkerhetskopior av information, programvara och systemavbilder ska tas och testas regelbundet.',
    category: 'Tekniska åtgärder',
    subcategory: 'Säkerhetskopiering',
    level: null,
    iso_mapping: '8.13',
    implementation_guidance: 'Upprätta en plan för säkerhetskopiering som anger frekvens, lagringsplats och testning. Genomför regelbundna återställningstester.',
    verification_guidance: 'Granska säkerhetskopieringsplanen och kontrollera att kopior tas och att återställningstester genomförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T11',
    title: 'Patch management',
    title_nl: 'Patchhantering',
    description: 'Security patches and software updates shall be applied in a timely manner following a defined process.',
    description_nl: 'Säkerhetsuppdateringar och programuppdateringar ska tillämpas i tid enligt en definierad process.',
    category: 'Tekniska åtgärder',
    subcategory: 'Patchhantering',
    level: null,
    iso_mapping: '8.8',
    implementation_guidance: 'Upprätta en patchhanteringsprocess med tidsramar baserade på sårbarhetens allvarlighetsgrad. Testa uppdateringar före driftsättning.',
    verification_guidance: 'Granska patchstatus och kontrollera att uppdateringar appliceras inom uppsatta tidsramar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T12',
    title: 'Secure configuration management',
    title_nl: 'Säker konfigurationshantering',
    description: 'Security configurations for hardware, software, services, and networks shall be established, documented, implemented, monitored, and reviewed.',
    description_nl: 'Säkerhetskonfigurationer för hårdvara, programvara, tjänster och nätverk ska upprättas, dokumenteras, implementeras, övervakas och granskas.',
    category: 'Tekniska åtgärder',
    subcategory: 'Konfiguration',
    level: null,
    iso_mapping: '8.9',
    implementation_guidance: 'Upprätta härdningsriktlinjer baserade på CIS Benchmarks eller motsvarande. Dokumentera och granska konfigurationer regelbundet.',
    verification_guidance: 'Jämför konfigurationer mot härdningsriktlinjer och kontrollera avvikelser.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T13',
    title: 'Secure development practices',
    title_nl: 'Säker utveckling',
    description: 'Rules for the secure development of software and systems shall be established and applied.',
    description_nl: 'Regler för säker utveckling av programvara och system ska upprättas och tillämpas.',
    category: 'Tekniska åtgärder',
    subcategory: 'Utveckling',
    level: null,
    iso_mapping: '8.25',
    implementation_guidance: 'Integrera säkerhet i utvecklingsprocessen (SDLC). Genomför kodgranskning och säkerhetstester.',
    verification_guidance: 'Granska utvecklingsprocessen och kontrollera att säkerhetsgranskning genomförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T14',
    title: 'Web filtering',
    title_nl: 'Webbfiltrering',
    description: 'Access to external websites shall be managed to reduce exposure to malicious content.',
    description_nl: 'Åtkomst till externa webbplatser ska hanteras för att minska exponering mot skadligt innehåll.',
    category: 'Tekniska åtgärder',
    subcategory: 'Webbfiltrering',
    level: null,
    iso_mapping: '8.23',
    implementation_guidance: 'Implementera webbfiltrering som blockerar kända skadliga webbplatser. Logga webbåtkomst för analys.',
    verification_guidance: 'Kontrollera att webbfiltrering är aktiv och att blockeringslistor uppdateras.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T15',
    title: 'Data leakage prevention',
    title_nl: 'Skydd mot dataläckage',
    description: 'Data leakage prevention measures shall be applied to systems, networks, and devices that process, store, or transmit sensitive information.',
    description_nl: 'Åtgärder mot dataläckage ska tillämpas på system, nätverk och enheter som behandlar, lagrar eller överför känslig information.',
    category: 'Tekniska åtgärder',
    subcategory: 'Dataläckage',
    level: null,
    iso_mapping: '8.12',
    implementation_guidance: 'Implementera DLP-verktyg för att upptäcka och förhindra oavsiktlig eller obehörig överföring av känslig data.',
    verification_guidance: 'Kontrollera att DLP-verktyg är konfigurerade och att incidenter följs upp.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Administrativa åtgärder (Administrative measures) ────────────────────
  {
    control_number: 'A1',
    title: 'Information security procedures and instructions',
    title_nl: 'Rutiner och instruktioner för informationssäkerhet',
    description: 'Operating procedures shall be documented and made available to all persons who need them.',
    description_nl: 'Rutiner för drift ska dokumenteras och göras tillgängliga för alla berörda personer.',
    category: 'Administrativa åtgärder',
    subcategory: 'Rutiner',
    level: null,
    iso_mapping: '5.37',
    implementation_guidance: 'Dokumentera rutiner för daglig drift, incidenthantering och säkerhetsadministration. Håll rutinerna uppdaterade.',
    verification_guidance: 'Granska rutinerna och kontrollera att de är aktuella och tillgängliga.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A2',
    title: 'Change management',
    title_nl: 'Ändringshantering',
    description: 'Changes to the organization, business processes, information systems, and security measures shall be controlled.',
    description_nl: 'Ändringar i organisationen, verksamhetsprocesser, informationssystem och säkerhetsåtgärder ska kontrolleras.',
    category: 'Administrativa åtgärder',
    subcategory: 'Ändringshantering',
    level: null,
    iso_mapping: '8.32',
    implementation_guidance: 'Implementera en ändringshanteringsprocess som inkluderar riskbedömning, godkännande och verifiering av ändringar.',
    verification_guidance: 'Granska ändringsloggen och kontrollera att processen följs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A3',
    title: 'Capacity management',
    title_nl: 'Kapacitetshantering',
    description: 'The use of resources shall be monitored and tuned, and projections made of future capacity requirements.',
    description_nl: 'Resursanvändningen ska övervakas och finjusteras, och prognoser för framtida kapacitetsbehov ska göras.',
    category: 'Administrativa åtgärder',
    subcategory: 'Kapacitet',
    level: null,
    iso_mapping: '8.6',
    implementation_guidance: 'Övervaka kapacitetsanvändning i kritiska system. Planera för framtida behov och upprätta tröskelvärden.',
    verification_guidance: 'Granska kapacitetsrapporter och kontrollera att prognoser uppdateras.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A4',
    title: 'Environment separation',
    title_nl: 'Separation av miljöer',
    description: 'Development, testing, and operational environments shall be separated to reduce risks of unauthorized access or changes.',
    description_nl: 'Utvecklings-, test- och produktionsmiljöer ska separeras för att minska risken för obehörig åtkomst eller ändringar.',
    category: 'Administrativa åtgärder',
    subcategory: 'Miljöseparation',
    level: null,
    iso_mapping: '8.31',
    implementation_guidance: 'Upprätthåll strikt separation mellan utveckling, test och produktion. Använd inte produktionsdata i testmiljöer utan maskering.',
    verification_guidance: 'Kontrollera att separering upprätthålls och att produktionsdata inte finns i testmiljöer.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A5',
    title: 'Information deletion and media disposal',
    title_nl: 'Informationsradering och mediehantering',
    description: 'Information stored in systems, devices, or any storage media shall be deleted when no longer required.',
    description_nl: 'Information som lagras i system, enheter eller andra lagringsmedia ska raderas när den inte längre behövs.',
    category: 'Administrativa åtgärder',
    subcategory: 'Radering',
    level: null,
    iso_mapping: '8.10',
    implementation_guidance: 'Upprätta rutiner för säker radering och destruktion av media. Använd godkända raderingsmetoder.',
    verification_guidance: 'Kontrollera att raderingsrutiner följs och att destruktionsprotokoll upprättas.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A6',
    title: 'Privacy and protection of personal data',
    title_nl: 'Skydd av personuppgifter',
    description: 'The privacy and protection of personal data shall be ensured in accordance with applicable legislation and regulations.',
    description_nl: 'Skydd av personuppgifter ska säkerställas i enlighet med tillämplig lagstiftning och regelverk.',
    category: 'Administrativa åtgärder',
    subcategory: 'Personuppgifter',
    level: null,
    iso_mapping: '5.34',
    implementation_guidance: 'Säkerställ efterlevnad av GDPR och dataskyddsförordningen. Genomför konsekvensbedömningar och implementera dataskydd som standard.',
    verification_guidance: 'Granska registerförteckningen och kontrollera att konsekvensbedömningar genomförts.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A7',
    title: 'Independent review of information security',
    title_nl: 'Oberoende granskning av informationssäkerhet',
    description: 'The organization\'s approach to managing information security shall be independently reviewed at planned intervals.',
    description_nl: 'Organisationens angreppssätt för att hantera informationssäkerhet ska granskas oberoende vid planerade intervaller.',
    category: 'Administrativa åtgärder',
    subcategory: 'Revision',
    level: null,
    iso_mapping: '5.35',
    implementation_guidance: 'Genomför oberoende revisioner av informationssäkerhet minst vartannat år. Anlita extern revisor eller internrevision.',
    verification_guidance: 'Kontrollera att revisionsrapporter finns och att åtgärder från revisionerna genomförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A8',
    title: 'Intellectual property rights',
    title_nl: 'Immateriella rättigheter',
    description: 'Appropriate procedures shall be implemented to ensure compliance with legal, regulatory, and contractual requirements related to intellectual property rights.',
    description_nl: 'Lämpliga rutiner ska implementeras för att säkerställa efterlevnad av lagar, förordningar och avtalsmässiga krav relaterade till immateriella rättigheter.',
    category: 'Administrativa åtgärder',
    subcategory: 'Juridik',
    level: null,
    iso_mapping: '5.32',
    implementation_guidance: 'Upprätta rutiner för licenshantering och kontroll av programvarulicenser.',
    verification_guidance: 'Granska licensregister och kontrollera att programvara används enligt licens.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A9',
    title: 'Records protection',
    title_nl: 'Skydd av handlingar och arkiv',
    description: 'Records shall be protected from loss, destruction, falsification, unauthorized access, and unauthorized release.',
    description_nl: 'Handlingar ska skyddas mot förlust, förstörelse, förfalskning, obehörig åtkomst och obehörigt röjande.',
    category: 'Administrativa åtgärder',
    subcategory: 'Arkivering',
    level: null,
    iso_mapping: '5.33',
    implementation_guidance: 'Implementera rutiner för arkivering och gallring av handlingar i enlighet med arkivlagen och organisationens krav.',
    verification_guidance: 'Granska arkiveringsrutiner och kontrollera att handlingar skyddas enligt klassificering.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Incidenthantering (Incident management) ─────────────────────────────
  {
    control_number: 'I1',
    title: 'Incident management planning',
    title_nl: 'Planering för incidenthantering',
    description: 'Management responsibilities and procedures shall be established to ensure a consistent and effective approach to incident management.',
    description_nl: 'Ledningens ansvar och rutiner ska upprättas för att säkerställa en konsekvent och effektiv hantering av incidenter.',
    category: 'Incidenthantering',
    subcategory: 'Planering',
    level: null,
    iso_mapping: '5.24',
    implementation_guidance: 'Upprätta en incidenthanteringsplan som definierar roller, eskaleringsvägar och kommunikationsprocedurer.',
    verification_guidance: 'Kontrollera att incidenthanteringsplanen finns och att den är kommunicerad till berörda.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'I2',
    title: 'Incident detection and reporting',
    title_nl: 'Upptäckt och rapportering av incidenter',
    description: 'Information security events shall be reported through appropriate management channels as quickly as possible.',
    description_nl: 'Informationssäkerhetshändelser ska rapporteras genom lämpliga ledningskanaler så snabbt som möjligt.',
    category: 'Incidenthantering',
    subcategory: 'Rapportering',
    level: null,
    iso_mapping: '6.8',
    implementation_guidance: 'Upprätta en rapporteringskanal för säkerhetshändelser. Utbilda personal i att identifiera och rapportera incidenter.',
    verification_guidance: 'Kontrollera att rapporteringskanalen är känd och att incidenter rapporteras.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'I3',
    title: 'Incident assessment and decision',
    title_nl: 'Bedömning och beslut vid incidenter',
    description: 'Information security events shall be assessed and classified as information security incidents based on severity criteria.',
    description_nl: 'Informationssäkerhetshändelser ska bedömas och klassificeras som informationssäkerhetsincidenter baserat på allvarlighetskriterier.',
    category: 'Incidenthantering',
    subcategory: 'Bedömning',
    level: null,
    iso_mapping: '5.25',
    implementation_guidance: 'Definiera klassificeringskriterier för incidenter baserat på påverkan på konfidentialitet, riktighet och tillgänglighet.',
    verification_guidance: 'Granska incidentloggen och kontrollera att klassificering sker konsekvent.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'I4',
    title: 'Incident response',
    title_nl: 'Incidentrespons',
    description: 'Information security incidents shall be responded to according to documented procedures.',
    description_nl: 'Informationssäkerhetsincidenter ska hanteras enligt dokumenterade rutiner.',
    category: 'Incidenthantering',
    subcategory: 'Respons',
    level: null,
    iso_mapping: '5.26',
    implementation_guidance: 'Upprätta detaljerade responserutiner per incidenttyp. Inkludera tekniska åtgärder, kommunikationsplaner och dokumentationskrav.',
    verification_guidance: 'Kontrollera att responserutiner finns och att de har testats genom övningar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'I5',
    title: 'Incident reporting to authorities',
    title_nl: 'Rapportering av incidenter till myndigheter',
    description: 'IT security incidents shall be reported to MSB/CERT-SE in accordance with MSBFS 2020:7 and applicable regulations.',
    description_nl: 'IT-säkerhetsincidenter ska rapporteras till MSB/CERT-SE i enlighet med MSBFS 2020:7 och tillämpliga föreskrifter.',
    category: 'Incidenthantering',
    subcategory: 'Myndighetsrapportering',
    level: null,
    iso_mapping: '5.5',
    implementation_guidance: 'Upprätta rutiner för rapportering till CERT-SE. Säkerställ att rapporteringsvägar och tidsfrister är kända. Beakta MSBFS 2020:7.',
    verification_guidance: 'Kontrollera att rapporteringsrutiner finns och att ansvariga känner till CERT-SE:s rapporteringskrav.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'I6',
    title: 'Learning from incidents',
    title_nl: 'Lärande av incidenter',
    description: 'Knowledge gained from information security incidents shall be used to strengthen the overall security posture.',
    description_nl: 'Kunskap från informationssäkerhetsincidenter ska användas för att stärka det övergripande säkerhetsarbetet.',
    category: 'Incidenthantering',
    subcategory: 'Lärande',
    level: null,
    iso_mapping: '5.27',
    implementation_guidance: 'Genomför grundorsaksanalys efter incidenter. Dokumentera lärdomar och implementera förbättringsåtgärder.',
    verification_guidance: 'Granska incidentrapporter och kontrollera att lärdomar har dokumenterats och lett till förbättringar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'I7',
    title: 'Evidence collection',
    title_nl: 'Bevishantering',
    description: 'Procedures for the identification, collection, acquisition, and preservation of evidence relating to information security events shall be defined and applied.',
    description_nl: 'Rutiner för identifiering, insamling och säkring av bevis relaterade till informationssäkerhetshändelser ska definieras och tillämpas.',
    category: 'Incidenthantering',
    subcategory: 'Bevishantering',
    level: null,
    iso_mapping: '5.28',
    implementation_guidance: 'Upprätta rutiner för bevishantering som säkerställer beviskedjans integritet. Utbilda personal i säker bevishantering.',
    verification_guidance: 'Kontrollera att rutiner för bevishantering finns dokumenterade.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Kontinuitetshantering (Business continuity) ──────────────────────────
  {
    control_number: 'BC1',
    title: 'Business continuity planning',
    title_nl: 'Kontinuitetsplanering',
    description: 'The organization shall plan how to maintain information security at an appropriate level during adverse situations.',
    description_nl: 'Organisationen ska planera hur informationssäkerheten ska upprätthållas på en lämplig nivå under ogynnsamma förhållanden.',
    category: 'Kontinuitetshantering',
    subcategory: 'Planering',
    level: null,
    iso_mapping: '5.29',
    implementation_guidance: 'Upprätta kontinuitetsplaner som inkluderar krav på informationssäkerhet. Definiera prioriterade verksamhetsprocesser och maximal acceptabel avbrottstid.',
    verification_guidance: 'Kontrollera att kontinuitetsplaner finns och att de beaktar informationssäkerhet.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'BC2',
    title: 'ICT readiness for business continuity',
    title_nl: 'IT-beredskap för verksamhetskontinuitet',
    description: 'ICT readiness shall be planned, implemented, maintained, and tested based on business continuity objectives.',
    description_nl: 'IT-beredskap ska planeras, implementeras, upprätthållas och testas baserat på mål för verksamhetskontinuitet.',
    category: 'Kontinuitetshantering',
    subcategory: 'IT-beredskap',
    level: null,
    iso_mapping: '5.30',
    implementation_guidance: 'Implementera redundans och reservlösningar för kritiska IT-system. Definiera RTO och RPO för varje system.',
    verification_guidance: 'Kontrollera att RTO och RPO är definierade och att reservlösningar finns för kritiska system.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'BC3',
    title: 'Business continuity testing',
    title_nl: 'Test av kontinuitetsplaner',
    description: 'Business continuity plans shall be tested at planned intervals and after significant changes.',
    description_nl: 'Kontinuitetsplaner ska testas vid planerade intervaller och efter väsentliga förändringar.',
    category: 'Kontinuitetshantering',
    subcategory: 'Testning',
    level: null,
    iso_mapping: '5.30',
    implementation_guidance: 'Genomför regelbundna tester av kontinuitetsplaner, inklusive tabletop-övningar och fullskaliga tester av IT-återställning.',
    verification_guidance: 'Granska testprotokoll och kontrollera att tester genomförs regelbundet.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'BC4',
    title: 'Redundancy of critical infrastructure',
    title_nl: 'Redundans för kritisk infrastruktur',
    description: 'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.',
    description_nl: 'Informationsbehandlingsanläggningar ska implementeras med tillräcklig redundans för att uppfylla tillgänglighetskrav.',
    category: 'Kontinuitetshantering',
    subcategory: 'Redundans',
    level: null,
    iso_mapping: '8.14',
    implementation_guidance: 'Implementera redundans för kritiska nätverkskomponenter, lagring och servrar. Verifiera automatisk failover.',
    verification_guidance: 'Testa failover-mekanismer och kontrollera att redundans fungerar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Uppföljning och förbättring (Monitoring and improvement) ─────────────
  {
    control_number: 'U1',
    title: 'Information security monitoring',
    title_nl: 'Övervakning av informationssäkerhet',
    description: 'The organization shall determine what needs to be monitored and measured, including information security processes and controls.',
    description_nl: 'Organisationen ska fastställa vad som behöver övervakas och mätas, inklusive informationssäkerhetsprocesser och kontroller.',
    category: 'Uppföljning och förbättring',
    subcategory: 'Övervakning',
    level: null,
    iso_mapping: '8.16',
    implementation_guidance: 'Definiera nyckeltal (KPI:er) för informationssäkerhet. Övervaka efterlevnad av policyer och kontroller.',
    verification_guidance: 'Kontrollera att nyckeltal finns definierade och att uppföljning genomförs regelbundet.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'U2',
    title: 'Internal audit',
    title_nl: 'Intern revision',
    description: 'Internal audits shall be conducted at planned intervals to verify that the information security management system conforms to requirements.',
    description_nl: 'Interna revisioner ska genomföras vid planerade intervaller för att verifiera att informationssäkerhetsledningssystemet uppfyller kraven.',
    category: 'Uppföljning och förbättring',
    subcategory: 'Revision',
    level: null,
    iso_mapping: '5.35',
    implementation_guidance: 'Planera och genomför interna revisioner av informationssäkerhet. Använd kvalificerade revisorer och dokumentera resultat.',
    verification_guidance: 'Granska revisionsplaner och kontrollera att revisioner genomförs och att avvikelser hanteras.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'U3',
    title: 'Compliance monitoring',
    title_nl: 'Efterlevnadskontroll',
    description: 'Compliance with information security policies, rules, standards, and regulations shall be regularly reviewed.',
    description_nl: 'Efterlevnad av informationssäkerhetspolicyer, regler, standarder och föreskrifter ska regelbundet granskas.',
    category: 'Uppföljning och förbättring',
    subcategory: 'Efterlevnad',
    level: null,
    iso_mapping: '5.36',
    implementation_guidance: 'Genomför regelbundna kontroller av efterlevnad. Rapportera avvikelser och genomför korrigerande åtgärder.',
    verification_guidance: 'Granska efterlevnadsrapporter och kontrollera att avvikelser hanteras.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'U4',
    title: 'Nonconformity and corrective action',
    title_nl: 'Avvikelser och korrigerande åtgärder',
    description: 'When a nonconformity occurs, the organization shall take action to control and correct it and deal with the consequences.',
    description_nl: 'Vid avvikelser ska organisationen vidta åtgärder för att kontrollera och korrigera dem samt hantera konsekvenserna.',
    category: 'Uppföljning och förbättring',
    subcategory: 'Avvikelser',
    level: null,
    iso_mapping: '5.36',
    implementation_guidance: 'Upprätta en process för hantering av avvikelser. Dokumentera avvikelser, orsaksanalys och korrigerande åtgärder.',
    verification_guidance: 'Granska avvikelseregistret och kontrollera att korrigerande åtgärder genomförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'U5',
    title: 'Continual improvement',
    title_nl: 'Ständig förbättring',
    description: 'The suitability, adequacy, and effectiveness of the information security management system shall be continually improved.',
    description_nl: 'Informationssäkerhetsledningssystemets lämplighet, tillräcklighet och effektivitet ska ständigt förbättras.',
    category: 'Uppföljning och förbättring',
    subcategory: 'Förbättring',
    level: null,
    iso_mapping: '5.36',
    implementation_guidance: 'Använd resultat från revisioner, incidenter och mätningar som underlag för förbättringar. Uppdatera policyer och rutiner regelbundet.',
    verification_guidance: 'Kontrollera att förbättringsåtgärder dokumenteras och genomförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'U6',
    title: 'Security testing',
    title_nl: 'Säkerhetstestning',
    description: 'Information systems shall be regularly tested for security vulnerabilities through penetration testing and security assessments.',
    description_nl: 'Informationssystem ska regelbundet testas för säkerhetssårbarheter genom penetrationstester och säkerhetsbedömningar.',
    category: 'Uppföljning och förbättring',
    subcategory: 'Testning',
    level: null,
    iso_mapping: '8.34',
    implementation_guidance: 'Genomför regelbundna penetrationstester och säkerhetsbedömningar. Prioritera tester baserat på riskbedömning.',
    verification_guidance: 'Granska testrapporter och kontrollera att identifierade sårbarheter åtgärdas.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Fysisk säkerhet (Physical security) ──────────────────────────────────
  {
    control_number: 'F1',
    title: 'Physical security perimeters',
    title_nl: 'Fysiska säkerhetszoner',
    description: 'Security perimeters shall be defined and used to protect areas that contain information and information processing facilities.',
    description_nl: 'Säkerhetszoner ska definieras och användas för att skydda områden som innehåller information och informationsbehandlingsanläggningar.',
    category: 'Fysisk säkerhet',
    subcategory: 'Zoner',
    level: null,
    iso_mapping: '7.1',
    implementation_guidance: 'Definiera säkerhetszoner med lämpliga fysiska skydd. Kontrollera tillträde till känsliga områden.',
    verification_guidance: 'Kontrollera att säkerhetszoner är definierade och att tillträdesskydd fungerar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'F2',
    title: 'Physical entry controls',
    title_nl: 'Fysisk tillträdeskontroll',
    description: 'Secure areas shall be protected by appropriate entry controls to ensure only authorized personnel are allowed access.',
    description_nl: 'Säkra områden ska skyddas av lämpliga tillträdeskontroller för att säkerställa att endast behörig personal ges tillträde.',
    category: 'Fysisk säkerhet',
    subcategory: 'Tillträde',
    level: null,
    iso_mapping: '7.2',
    implementation_guidance: 'Implementera passersystem och besöksrutiner. Logga tillträde till känsliga utrymmen.',
    verification_guidance: 'Granska passersystemloggar och kontrollera att besöksrutiner följs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'F3',
    title: 'Environmental threats protection',
    title_nl: 'Skydd mot miljöhot',
    description: 'Protection against physical and environmental threats such as fire, flood, and power failure shall be designed and implemented.',
    description_nl: 'Skydd mot fysiska och miljömässiga hot som brand, översvämning och strömavbrott ska utformas och implementeras.',
    category: 'Fysisk säkerhet',
    subcategory: 'Miljöhot',
    level: null,
    iso_mapping: '7.5',
    implementation_guidance: 'Installera brandlarm, vattendetektorer och avbrottsfri strömförsörjning (UPS) i serverrum och andra kritiska utrymmen.',
    verification_guidance: 'Kontrollera att skyddssystemen är installerade, testade och funktionella.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'F4',
    title: 'Equipment maintenance',
    title_nl: 'Underhåll av utrustning',
    description: 'Equipment shall be correctly maintained to ensure its continued availability and integrity.',
    description_nl: 'Utrustning ska underhållas korrekt för att säkerställa fortsatt tillgänglighet och riktighet.',
    category: 'Fysisk säkerhet',
    subcategory: 'Underhåll',
    level: null,
    iso_mapping: '7.13',
    implementation_guidance: 'Upprätta underhållsscheman för kritisk utrustning. Säkerställ att underhåll utförs av behörig personal.',
    verification_guidance: 'Granska underhållsloggar och kontrollera att schemalagt underhåll genomförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'F5',
    title: 'Clear desk and clear screen',
    title_nl: 'Rent skrivbord och ren skärm',
    description: 'A clear desk policy for papers and removable storage media and a clear screen policy for information processing facilities shall be adopted.',
    description_nl: 'En policy för rent skrivbord för papper och flyttbara lagringsmedia samt ren skärm för informationsbehandlingsanläggningar ska tillämpas.',
    category: 'Fysisk säkerhet',
    subcategory: 'Rent skrivbord',
    level: null,
    iso_mapping: '7.7',
    implementation_guidance: 'Inför policy för rent skrivbord och automatisk skärmlåsning. Utbilda personal i att inte lämna känslig information synlig.',
    verification_guidance: 'Genomför stickprovskontroller av arbetsplatser och kontrollera skärmlåsningsinställningar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Ledning — Additional ──────────────────────────────────────────────────
  {
    control_number: 'L12',
    title: 'Board-level security reporting',
    title_nl: 'Styrelserapportering om säkerhet',
    description: 'Information security status and risks shall be reported to the board or equivalent governing body at regular intervals.',
    description_nl: 'Informationssäkerhetens status och risker ska rapporteras till styrelsen eller motsvarande ledningsorgan med regelbundna intervall.',
    category: 'Ledning och styrning',
    subcategory: 'Rapportering',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Upprätta kvartalsvis rapportering till ledningsgrupp/styrelse om informationssäkerhetens status.',
    verification_guidance: 'Kontrollera att rapportering genomförs och att den inkluderar riskbild och åtgärdsstatus.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'L13',
    title: 'Security budget allocation',
    title_nl: 'Budgetallokering för säkerhet',
    description: 'Adequate budget shall be allocated for information security activities based on risk assessment results.',
    description_nl: 'Tillräcklig budget ska allokeras för informationssäkerhetsaktiviteter baserat på resultat av riskbedömningar.',
    category: 'Ledning och styrning',
    subcategory: 'Resurser',
    level: null,
    iso_mapping: '5.1',
    implementation_guidance: 'Koppla säkerhetsbudget till identifierade risker. Allokera resurser för prioriterade åtgärder.',
    verification_guidance: 'Kontrollera att säkerhetsbudget finns och att den baseras på riskbedömning.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Riskhantering — Additional ────────────────────────────────────────────
  {
    control_number: 'R8',
    title: 'Threat intelligence integration in risk assessment',
    title_nl: 'Integration av hotinformation i riskbedömning',
    description: 'Threat intelligence shall be considered as input to the risk assessment process to identify current and emerging threats.',
    description_nl: 'Hotinformation ska beaktas som underlag i riskbedömningsprocessen för att identifiera aktuella och framväxande hot.',
    category: 'Riskhantering',
    subcategory: 'Hotinformation',
    level: null,
    iso_mapping: '5.7',
    implementation_guidance: 'Prenumerera på CERT-SE:s varningar. Inkludera hotinformation i riskanalyser. Uppdatera riskbild löpande.',
    verification_guidance: 'Kontrollera att hotinformation beaktas vid riskbedömningar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'R9',
    title: 'Supply chain risk assessment',
    title_nl: 'Riskbedömning av leveranskedjan',
    description: 'Risks related to the ICT supply chain shall be identified, assessed, and managed.',
    description_nl: 'Risker relaterade till IKT-leveranskedjan ska identifieras, bedömas och hanteras.',
    category: 'Riskhantering',
    subcategory: 'Leveranskedja',
    level: null,
    iso_mapping: '5.21',
    implementation_guidance: 'Inkludera leveranskedjerisker i riskbedömningen. Kartlägg kritiska beroenden. Upprätta alternativplaner.',
    verification_guidance: 'Kontrollera att leveranskedjerisker bedöms och att kritiska beroenden identifierats.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Tekniska åtgärder — Additional ────────────────────────────────────────
  {
    control_number: 'T16',
    title: 'Data loss prevention',
    title_nl: 'Förebyggande av dataläckage (DLP)',
    description: 'Technical controls shall be implemented to detect and prevent unauthorized transfer of sensitive data.',
    description_nl: 'Tekniska kontroller ska implementeras för att upptäcka och förhindra obehörig överföring av känsliga uppgifter.',
    category: 'Tekniska åtgärder',
    subcategory: 'DLP',
    level: null,
    iso_mapping: '8.12',
    implementation_guidance: 'Implementera DLP-verktyg för e-post, USB och molnlagring. Definiera policyer baserade på klassificering.',
    verification_guidance: 'Kontrollera att DLP-kontroller är aktiva och att incidenter rapporteras.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T17',
    title: 'Network traffic monitoring',
    title_nl: 'Övervakning av nätverkstrafik',
    description: 'Network traffic shall be monitored for anomalous patterns that may indicate security incidents.',
    description_nl: 'Nätverkstrafik ska övervakas för avvikande mönster som kan indikera säkerhetsincidenter.',
    category: 'Tekniska åtgärder',
    subcategory: 'Övervakning',
    level: null,
    iso_mapping: '8.16',
    implementation_guidance: 'Implementera NDR (Network Detection and Response). Övervaka DNS-frågor, oväntade utgående anslutningar och laterala förflyttningar.',
    verification_guidance: 'Kontrollera att nätverksövervakning är aktiv och att larm granskas.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T18',
    title: 'Secure email gateway',
    title_nl: 'Säker e-postgateway',
    description: 'Email traffic shall pass through a security gateway providing spam filtering, malware scanning, and attachment sandboxing.',
    description_nl: 'E-posttrafik ska passera genom en säkerhetsgateway med spamfiltrering, skanning av skadlig kod och sandboxning av bilagor.',
    category: 'Tekniska åtgärder',
    subcategory: 'E-post',
    level: null,
    iso_mapping: '8.23',
    implementation_guidance: 'Implementera e-postsäkerhetsgateway. Aktivera sandboxning av bilagor och URL-skanning.',
    verification_guidance: 'Kontrollera att e-postgateway är aktiv och att filtrering fungerar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T19',
    title: 'Security event correlation',
    title_nl: 'Korrelering av säkerhetshändelser',
    description: 'Security events from multiple sources shall be correlated to detect complex attack patterns.',
    description_nl: 'Säkerhetshändelser från flera källor ska korreleras för att upptäcka sammansatta attackmönster.',
    category: 'Tekniska åtgärder',
    subcategory: 'SIEM',
    level: null,
    iso_mapping: '8.16',
    implementation_guidance: 'Integrera loggar i SIEM. Skapa korrelationsregler för vanliga attackscenarier (brute force, lateral movement, exfiltrering).',
    verification_guidance: 'Kontrollera att korrelationsregler finns och att de genererar relevanta larm.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'T20',
    title: 'API security',
    title_nl: 'API-säkerhet',
    description: 'APIs shall be secured with authentication, authorization, rate limiting, input validation, and logging.',
    description_nl: 'API:er ska säkras med autentisering, behörighetskontroll, hastighetsbegränsning, indatavalidering och loggning.',
    category: 'Tekniska åtgärder',
    subcategory: 'API',
    level: null,
    iso_mapping: '8.26',
    implementation_guidance: 'Tillämpa OAuth 2.0. Validera all indata. Implementera rate limiting. Logga alla API-anrop.',
    verification_guidance: 'Genomför API-säkerhetstester och kontrollera att skyddsmekanismer fungerar.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Administrativa åtgärder — Additional ──────────────────────────────────
  {
    control_number: 'A10',
    title: 'Secure procurement',
    title_nl: 'Säker upphandling',
    description: 'Information security requirements shall be included in procurement specifications for IT systems and services.',
    description_nl: 'Informationssäkerhetskrav ska ingå i kravspecifikationer vid upphandling av IT-system och tjänster.',
    category: 'Administrativa åtgärder',
    subcategory: 'Upphandling',
    level: null,
    iso_mapping: '5.19',
    implementation_guidance: 'Ta fram säkerhetskrav vid upphandling. Inkludera krav i avtal. Granska leverantörers säkerhetsarbete.',
    verification_guidance: 'Kontrollera att säkerhetskrav ingår i upphandlingsunderlag.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A11',
    title: 'Data processing agreements',
    title_nl: 'Personuppgiftsbiträdesavtal',
    description: 'Data processing agreements compliant with GDPR shall be established with all processors of personal data.',
    description_nl: 'Personuppgiftsbiträdesavtal i enlighet med GDPR ska upprättas med alla som behandlar personuppgifter.',
    category: 'Administrativa åtgärder',
    subcategory: 'GDPR',
    level: null,
    iso_mapping: '5.34',
    implementation_guidance: 'Upprätta PUB-avtal med alla leverantörer som behandlar personuppgifter. Granska avtal regelbundet.',
    verification_guidance: 'Kontrollera att PUB-avtal finns med alla relevanta leverantörer.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'A12',
    title: 'Information security in project management',
    title_nl: 'Informationssäkerhet i projektledning',
    description: 'Information security requirements shall be addressed in all projects regardless of type.',
    description_nl: 'Informationssäkerhetskrav ska beaktas i alla projekt oavsett typ.',
    category: 'Administrativa åtgärder',
    subcategory: 'Projekt',
    level: null,
    iso_mapping: '5.8',
    implementation_guidance: 'Inkludera informationssäkerhet i projektmodell. Genomför säkerhetsbedömning i projektets initieringsfas.',
    verification_guidance: 'Kontrollera att informationssäkerhet beaktas i projektdokumentation.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Incidenthantering — Additional ────────────────────────────────────────
  {
    control_number: 'I8',
    title: 'Digital forensics readiness',
    title_nl: 'Beredskap för digital forensik',
    description: 'The organization shall maintain capability for digital forensic investigation of security incidents.',
    description_nl: 'Organisationen ska upprätthålla förmåga för digital forensisk utredning av säkerhetsincidenter.',
    category: 'Incidenthantering',
    subcategory: 'Forensik',
    level: null,
    iso_mapping: '5.28',
    implementation_guidance: 'Säkerställ att loggar och bevis kan samlas in på ett forensiskt korrekt sätt. Utbilda personal.',
    verification_guidance: 'Kontrollera att forensisk beredskap finns och att personal är utbildad.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Kontinuitetshantering — Additional ────────────────────────────────────
  {
    control_number: 'BC5',
    title: 'IT disaster recovery plan',
    title_nl: 'IT-katastrofåterställningsplan',
    description: 'An IT disaster recovery plan shall be maintained to restore critical IT services within defined timeframes.',
    description_nl: 'En IT-katastrofåterställningsplan ska upprätthållas för att återställa kritiska IT-tjänster inom definierade tidsramar.',
    category: 'Kontinuitetshantering',
    subcategory: 'DR-plan',
    level: null,
    iso_mapping: '5.30',
    implementation_guidance: 'Upprätta DR-plan med RTO/RPO för alla kritiska system. Testa återställning årligen.',
    verification_guidance: 'Kontrollera att DR-plan finns och att tester genomförts.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'BC6',
    title: 'Crisis communication plan',
    title_nl: 'Kriskommunikationsplan',
    description: 'A crisis communication plan shall be maintained for internal and external communication during security incidents.',
    description_nl: 'En kriskommunikationsplan ska upprätthållas för intern och extern kommunikation vid säkerhetsincidenter.',
    category: 'Kontinuitetshantering',
    subcategory: 'Kommunikation',
    level: null,
    iso_mapping: '5.26',
    implementation_guidance: 'Upprätta kriskommunikationsplan med mallar, kontaktlistor och eskaleringsvägar.',
    verification_guidance: 'Kontrollera att kriskommunikationsplan finns och att den har testats.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Uppföljning — Additional ──────────────────────────────────────────────
  {
    control_number: 'U7',
    title: 'Key performance indicators for information security',
    title_nl: 'Nyckeltal för informationssäkerhet',
    description: 'Measurable key performance indicators shall be defined and tracked to evaluate information security effectiveness.',
    description_nl: 'Mätbara nyckeltal ska definieras och följas upp för att utvärdera informationssäkerhetens effektivitet.',
    category: 'Uppföljning och förbättring',
    subcategory: 'Mätning',
    level: null,
    iso_mapping: '5.36',
    implementation_guidance: 'Definiera KPI:er (patchnivå, incidenttider, utbildningsgrad). Rapportera kvartalsvis.',
    verification_guidance: 'Kontrollera att KPI:er definieras, mäts och rapporteras.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'U8',
    title: 'Benchmarking with peer organizations',
    title_nl: 'Jämförelse med jämbördiga organisationer',
    description: 'Information security maturity shall be benchmarked against peer organizations or recognized maturity models.',
    description_nl: 'Informationssäkerhetens mognad ska jämföras med jämbördiga organisationer eller erkända mognadsmodeller.',
    category: 'Uppföljning och förbättring',
    subcategory: 'Jämförelse',
    level: null,
    iso_mapping: '5.36',
    implementation_guidance: 'Genomför årlig mognadsbedömning. Jämför med MSB:s mognadsnivåer eller CMMI.',
    verification_guidance: 'Kontrollera att mognadsbedömning genomförs och att resultat jämförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },

  // ── Fysisk säkerhet — Additional ──────────────────────────────────────────
  {
    control_number: 'F6',
    title: 'Perimeter security',
    title_nl: 'Perimetersäkerhet',
    description: 'Physical perimeters of the facility shall be protected with appropriate barriers and access points.',
    description_nl: 'Fysiska perimetrar för anläggningen ska skyddas med lämpliga barriärer och åtkomstpunkter.',
    category: 'Fysisk säkerhet',
    subcategory: 'Perimeter',
    level: null,
    iso_mapping: '7.1',
    implementation_guidance: 'Installera staket, belysning och kameror vid perimetern. Begränsa antal entréer.',
    verification_guidance: 'Inspektera perimeterskydd och kontrollera att det är intakt.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
  {
    control_number: 'F7',
    title: 'Equipment maintenance and inspection',
    title_nl: 'Underhåll och inspektion av utrustning',
    description: 'Physical security equipment (cameras, alarms, locks) shall be maintained and inspected at regular intervals.',
    description_nl: 'Fysisk säkerhetsutrustning (kameror, larm, lås) ska underhållas och inspekteras med regelbundna intervall.',
    category: 'Fysisk säkerhet',
    subcategory: 'Underhåll',
    level: null,
    iso_mapping: '7.13',
    implementation_guidance: 'Upprätta underhållsschema för säkerhetsutrustning. Dokumentera inspektioner.',
    verification_guidance: 'Granska underhållsloggar och kontrollera att inspektioner genomförs.',
    source_url: 'https://www.informationssakerhet.se/metodstod/',
  },
];

async function main(): Promise<void> {
  console.log('MSB Metodstod Ingestion Script');
  console.log('================================');
  console.log('Source: https://www.informationssakerhet.se/metodstod/');
  console.log('');

  mkdirSync(DATA_DIR, { recursive: true });

  // Validate
  let validationErrors = 0;
  for (const ctrl of controls) {
    if (!ctrl.control_number) { console.error(`  Missing control_number`); validationErrors++; }
    if (!ctrl.title_nl) { console.error(`  Missing title_nl for ${ctrl.control_number}`); validationErrors++; }
    if (!ctrl.description_nl) { console.error(`  Missing description_nl for ${ctrl.control_number}`); validationErrors++; }
  }
  if (validationErrors > 0) { console.error(`${validationErrors} validation errors.`); process.exit(1); }

  console.log(`  ${controls.length} controls validated.`);

  // Category distribution
  const cats: Record<string, number> = {};
  for (const c of controls) { cats[c.category] = (cats[c.category] || 0) + 1; }
  console.log('\nCategory distribution:');
  for (const [cat, count] of Object.entries(cats).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${cat}: ${count}`);
  }

  const output = {
    framework: {
      id: 'msb-metodstod',
      name: 'Systematic Information Security Work',
      name_nl: 'Systematiskt informationssäkerhetsarbete',
      issuing_body: 'Myndigheten för samhällsskydd och beredskap (MSB)',
      version: '2024',
      effective_date: '2024-01-01',
      scope: 'Methodology support for systematic information security work in Swedish organizations, based on ISO 27001',
      scope_sectors: ['government'],
      structure_description: 'Organized by 10 areas: management (L), organization (O), risk management (R), classification (K), technical measures (T), administrative measures (A), incident management (I), business continuity (BC), monitoring and improvement (U), physical security (F).',
      source_url: 'https://www.informationssakerhet.se/metodstod/',
      license: 'Public sector publication',
      language: 'sv',
    },
    controls,
    metadata: {
      ingested_at: new Date().toISOString(),
      source_url: 'https://www.informationssakerhet.se/metodstod/',
      total_controls: controls.length,
    },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`\nOutput written to ${OUTPUT_FILE}`);
  console.log(`File size: ${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB`);
  console.log('Done.');
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
