// scripts/ingest-digg.ts
// DIGG Vägledning för digital säkerhet (Digital Security Guidance)
// Authority: Myndigheten för digital förvaltning (DIGG)

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'digg-digital-sakerhet.json');

const controls = [
  { control_number: 'DS1', title: 'Secure digital service design', title_nl: 'Säker utformning av digitala tjänster', description: 'Digital services shall be designed with security built in from the start, following security-by-design principles.', description_nl: 'Digitala tjänster ska utformas med inbyggd säkerhet från start, enligt principen säkerhet genom design.', category: 'Digitala tjänster', subcategory: 'Design', level: null, iso_mapping: '8.25', implementation_guidance: 'Inkludera säkerhetskrav i kravspecifikationer. Genomför hotmodellering tidigt i designfasen.', verification_guidance: 'Granska designdokumentation och kontrollera att säkerhetskrav ingår.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS2', title: 'API security requirements', title_nl: 'Säkerhetskrav för API:er', description: 'APIs shall implement authentication, authorization, input validation, rate limiting, and logging.', description_nl: 'API:er ska implementera autentisering, behörighetskontroll, indatavalidering, begränsning av anrop och loggning.', category: 'Digitala tjänster', subcategory: 'API-säkerhet', level: null, iso_mapping: '8.26', implementation_guidance: 'Tillämpa OAuth 2.0/OpenID Connect för autentisering. Validera all indata. Implementera hastighetsbegränsning.', verification_guidance: 'Genomför API-säkerhetstester och kontrollera autentiseringsmekanismer.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS3', title: 'Identity management with e-legitimation', title_nl: 'Identitetshantering med e-legitimation', description: 'Digital services requiring identity verification shall support Swedish e-legitimation (BankID, Freja eID) via Sweden Connect.', description_nl: 'Digitala tjänster som kräver identitetsverifiering ska stödja svensk e-legitimation (BankID, Freja eID) via Sweden Connect.', category: 'Identitet', subcategory: 'e-legitimation', level: null, iso_mapping: '5.16', implementation_guidance: 'Integrera med Sweden Connect-ramverket för e-legitimation. Stöd tillitsnivåer enligt tillitsramverket.', verification_guidance: 'Kontrollera att e-legitimationsintegration fungerar och att rätt tillitsnivå tillämpas.', source_url: 'https://www.digg.se/digitala-tjanster/e-legitimering' },
  { control_number: 'DS4', title: 'Federated identity and single sign-on', title_nl: 'Federerad identitet och enkel inloggning', description: 'Public sector digital services shall support federated identity management for cross-agency authentication.', description_nl: 'Offentliga digitala tjänster ska stödja federerad identitetshantering för autentisering mellan myndigheter.', category: 'Identitet', subcategory: 'Federation', level: null, iso_mapping: '5.16', implementation_guidance: 'Implementera SAML 2.0 eller OpenID Connect för federerad identitetshantering.', verification_guidance: 'Testa federerad inloggning och verifiera att attribut överförs korrekt.', source_url: 'https://www.digg.se/digitala-tjanster/e-legitimering' },
  { control_number: 'DS5', title: 'Data protection in digital services', title_nl: 'Dataskydd i digitala tjänster', description: 'Digital services processing personal data shall implement data protection by design and by default.', description_nl: 'Digitala tjänster som behandlar personuppgifter ska implementera dataskydd som standard och inbyggt dataskydd.', category: 'Dataskydd', subcategory: 'Privacy by design', level: null, iso_mapping: '5.34', implementation_guidance: 'Genomför konsekvensbedömning (DPIA) för nya tjänster. Minimera personuppgiftsbehandling.', verification_guidance: 'Kontrollera att DPIA har genomförts och att dataminimering tillämpas.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS6', title: 'Accessibility and security balance', title_nl: 'Balans mellan tillgänglighet och säkerhet', description: 'Security measures shall not compromise the accessibility of digital services. Both requirements shall be addressed simultaneously.', description_nl: 'Säkerhetsåtgärder ska inte äventyra tillgängligheten i digitala tjänster. Båda kraven ska uppfyllas samtidigt.', category: 'Digitala tjänster', subcategory: 'Tillgänglighet', level: null, iso_mapping: null, implementation_guidance: 'Testa att säkerhetsmekanismer (t.ex. CAPTCHA) inte hindrar tillgänglighet. Erbjud alternativa autentiseringsmetoder.', verification_guidance: 'Genomför tillgänglighetstester av säkerhetsmekanismer.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS7', title: 'Secure information exchange between agencies', title_nl: 'Säker informationsöverföring mellan myndigheter', description: 'Information exchange between government agencies shall use secure, standardized protocols and formats.', description_nl: 'Informationsutbyte mellan myndigheter ska ske via säkra, standardiserade protokoll och format.', category: 'Informationsutbyte', subcategory: 'Myndighetsutbyte', level: null, iso_mapping: '5.14', implementation_guidance: 'Använd Säker Digital Kommunikation (SDK) eller motsvarande för myndighetsutbyte. Kryptera data i transit.', verification_guidance: 'Kontrollera att SDK eller likvärdigt protokoll används för myndighetskommunikation.', source_url: 'https://www.digg.se/digitala-tjanster/sdk' },
  { control_number: 'DS8', title: 'Open data security', title_nl: 'Säkerhet vid öppna data', description: 'Open data publications shall be reviewed to ensure no sensitive information is inadvertently disclosed.', description_nl: 'Publicering av öppna data ska granskas för att säkerställa att känslig information inte oavsiktligt röjs.', category: 'Informationsutbyte', subcategory: 'Öppna data', level: null, iso_mapping: '5.12', implementation_guidance: 'Granska dataset innan publicering. Avidentifiera personuppgifter och ta bort känslig information.', verification_guidance: 'Kontrollera att granskningsprocess finns för öppna data.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS9', title: 'Cloud service assessment for public sector', title_nl: 'Bedömning av molntjänster för offentlig sektor', description: 'Cloud services used by public sector agencies shall be assessed for security, data residency, and legal compliance.', description_nl: 'Molntjänster som används av offentliga myndigheter ska bedömas avseende säkerhet, datalokaliserring och rättslig efterlevnad.', category: 'Molntjänster', subcategory: 'Bedömning', level: null, iso_mapping: '5.23', implementation_guidance: 'Genomför säkerhetsbedömning innan upphandling av molntjänster. Beakta Schrems II och datasuveränitet.', verification_guidance: 'Granska bedömningar av använda molntjänster och kontrollera att de uppfyller kraven.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS10', title: 'Digital service continuity', title_nl: 'Kontinuitet för digitala tjänster', description: 'Digital services shall have continuity plans ensuring availability during disruptions.', description_nl: 'Digitala tjänster ska ha kontinuitetsplaner som säkerställer tillgänglighet vid störningar.', category: 'Digitala tjänster', subcategory: 'Kontinuitet', level: null, iso_mapping: '5.29', implementation_guidance: 'Upprätta kontinuitetsplaner för digitala tjänster. Definiera SLA-mål och redundanslösningar.', verification_guidance: 'Kontrollera att kontinuitetsplaner finns och har testats.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS11', title: 'Logging of digital service access', title_nl: 'Loggning av åtkomst till digitala tjänster', description: 'Access to digital services shall be logged in a manner that enables detection of unauthorized use.', description_nl: 'Åtkomst till digitala tjänster ska loggas på ett sätt som möjliggör upptäckt av obehörig användning.', category: 'Digitala tjänster', subcategory: 'Loggning', level: null, iso_mapping: '8.15', implementation_guidance: 'Logga autentisering, behörighetsändringar och dataåtkomst. Skydda loggar mot manipulation.', verification_guidance: 'Granska loggkonfigurationer och kontrollera att relevanta händelser loggas.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS12', title: 'Security testing of digital services', title_nl: 'Säkerhetstestning av digitala tjänster', description: 'Digital services shall undergo security testing before deployment and regularly thereafter.', description_nl: 'Digitala tjänster ska genomgå säkerhetstestning innan driftsättning och regelbundet därefter.', category: 'Digitala tjänster', subcategory: 'Testning', level: null, iso_mapping: '8.29', implementation_guidance: 'Genomför penetrationstester och DAST-skanningar före lansering. Repetera minst årligen.', verification_guidance: 'Granska testrapporter och kontrollera att identifierade brister åtgärdats.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS13', title: 'Secure development framework for public services', title_nl: 'Ramverk för säker utveckling av offentliga tjänster', description: 'Development of public digital services shall follow a secure development lifecycle with code review and automated testing.', description_nl: 'Utveckling av offentliga digitala tjänster ska följa en säker utvecklingslivscykel med kodgranskning och automatiserad testning.', category: 'Digitala tjänster', subcategory: 'Utveckling', level: null, iso_mapping: '8.25', implementation_guidance: 'Implementera SSDLC med statisk och dynamisk kodanalys. Kräv kodgranskning för alla ändringar.', verification_guidance: 'Kontrollera att SSDLC-processen följs och att automatiserade tester körs.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS14', title: 'Consent and transparency management', title_nl: 'Samtyckes- och transparenshantering', description: 'Digital services shall implement transparent consent management where applicable.', description_nl: 'Digitala tjänster ska implementera transparent samtyckehantering där det är tillämpligt.', category: 'Dataskydd', subcategory: 'Samtycke', level: null, iso_mapping: '5.34', implementation_guidance: 'Implementera tydlig information om databehandling och samtyckesfunktioner där så krävs.', verification_guidance: 'Kontrollera att samtyckesinformation presenteras tydligt.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS15', title: 'Incident notification for digital services', title_nl: 'Incidentmeddelande för digitala tjänster', description: 'Users of digital services shall be notified in a timely manner of security incidents that may affect them.', description_nl: 'Användare av digitala tjänster ska underrättas inom rimlig tid om säkerhetsincidenter som kan påverka dem.', category: 'Incidenthantering', subcategory: 'Meddelande', level: null, iso_mapping: '5.26', implementation_guidance: 'Upprätta rutiner för att informera användare vid säkerhetsincidenter. Definiera tidsramar och kommunikationskanaler.', verification_guidance: 'Kontrollera att incidentmeddelanderutiner finns dokumenterade.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS16', title: 'Digital mailbox security', title_nl: 'Säkerhet för digital brevlåda', description: 'Government digital mailbox integrations shall verify recipient identity and encrypt contents in transit and at rest.', description_nl: 'Integrationer med statlig digital brevlåda ska verifiera mottagarens identitet och kryptera innehåll vid överföring och lagring.', category: 'Informationsutbyte', subcategory: 'Digital brevlåda', level: null, iso_mapping: '8.24', implementation_guidance: 'Integrera med Mina meddelanden. Kryptera meddelanden. Verifiera mottagaridentitet via personnummer.', verification_guidance: 'Kontrollera att kryptering och identitetsverifiering fungerar i brevlådeintegrationer.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS17', title: 'Automated decision-making transparency', title_nl: 'Transparens vid automatiserade beslut', description: 'Automated decisions affecting individuals shall be explainable, logged, and subject to human review on request.', description_nl: 'Automatiserade beslut som påverkar enskilda ska vara förklarbara, loggade och kunna överprövas av människa på begäran.', category: 'Digitala tjänster', subcategory: 'Automatisering', level: null, iso_mapping: null, implementation_guidance: 'Logga beslutsunderlag för automatiserade beslut. Tillhandahåll förklaringstext. Erbjud manuell överprövning.', verification_guidance: 'Kontrollera att automatiserade beslut loggas och att överprövningsmöjlighet erbjuds.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS18', title: 'Cross-border data transfer assessment', title_nl: 'Bedömning av gränsöverskridande dataöverföringar', description: 'Transfers of personal data outside the EU/EEA shall be assessed for legal basis and technical protection measures.', description_nl: 'Överföringar av personuppgifter utanför EU/EES ska bedömas avseende rättslig grund och tekniska skyddsåtgärder.', category: 'Dataskydd', subcategory: 'Tredjelandsöverföring', level: null, iso_mapping: '5.34', implementation_guidance: 'Genomför Transfer Impact Assessment (TIA) innan tredjelandsöverföringar. Tillämpa supplementary measures vid behov.', verification_guidance: 'Kontrollera att TIA genomförts för alla tredjelandsöverföringar.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS19', title: 'Digital service monitoring and SLA', title_nl: 'Övervakning och SLA för digitala tjänster', description: 'Digital services shall have defined SLAs and automated monitoring with alerting for availability degradation.', description_nl: 'Digitala tjänster ska ha definierade SLA:er och automatiserad övervakning med varning vid försämrad tillgänglighet.', category: 'Digitala tjänster', subcategory: 'Övervakning', level: null, iso_mapping: '5.37', implementation_guidance: 'Definiera SLA-mål (tillgänglighet, svarstid). Implementera syntetisk övervakning. Konfigurera larm.', verification_guidance: 'Granska SLA-rapporter och kontrollera att larmsystem fungerar.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS20', title: 'Secure document signing', title_nl: 'Säker dokumentsignering', description: 'Digital document signing in public services shall use qualified electronic signatures compliant with eIDAS.', description_nl: 'Digital dokumentsignering i offentliga tjänster ska använda kvalificerade elektroniska signaturer i enlighet med eIDAS.', category: 'Identitet', subcategory: 'Signering', level: null, iso_mapping: '5.16', implementation_guidance: 'Integrera med kvalificerad signeringstjänst. Stöd eIDAS-nivåer. Verifiera certifikat vid signering.', verification_guidance: 'Kontrollera att signaturer valideras korrekt och att eIDAS-efterlevnad uppfylls.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS21', title: 'Public sector API catalog registration', title_nl: 'Registrering i offentlig API-katalog', description: 'APIs provided by government agencies shall be registered in the national API catalog for discoverability and reuse.', description_nl: 'API:er som tillhandahålls av myndigheter ska registreras i den nationella API-katalogen för upptäckbarhet och återanvändning.', category: 'Digitala tjänster', subcategory: 'API-katalog', level: null, iso_mapping: null, implementation_guidance: 'Registrera API:er i Sveriges dataportal. Beskriv med OpenAPI-specifikation. Inkludera säkerhetsinformation.', verification_guidance: 'Kontrollera att API:er finns registrerade och att dokumentationen är komplett.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS22', title: 'Secure microservice communication', title_nl: 'Säker kommunikation mellan mikrotjänster', description: 'Inter-service communication in digital platforms shall use mutual TLS or equivalent authentication.', description_nl: 'Kommunikation mellan tjänster i digitala plattformar ska använda ömsesidig TLS eller likvärdig autentisering.', category: 'Digitala tjänster', subcategory: 'Arkitektur', level: null, iso_mapping: '8.24', implementation_guidance: 'Implementera mTLS eller service mesh för intern tjänstekommunikation. Validera certifikat.', verification_guidance: 'Kontrollera att intern kommunikation är krypterad och autentiserad.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS23', title: 'Data portability and interoperability', title_nl: 'Dataportabilitet och interoperabilitet', description: 'Digital services shall support data portability through standardized formats and open interfaces.', description_nl: 'Digitala tjänster ska stödja dataportabilitet genom standardiserade format och öppna gränssnitt.', category: 'Informationsutbyte', subcategory: 'Portabilitet', level: null, iso_mapping: null, implementation_guidance: 'Använd öppna standarder (JSON, XML). Tillhandahåll exportfunktioner. Dokumentera dataformat.', verification_guidance: 'Kontrollera att exportfunktioner finns och att format är standardiserade.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS24', title: 'Vulnerability disclosure policy', title_nl: 'Policy för sårbarhetsrapportering', description: 'Digital services shall have a published vulnerability disclosure policy enabling responsible reporting by external parties.', description_nl: 'Digitala tjänster ska ha en publicerad policy för sårbarhetsrapportering som möjliggör ansvarsfull rapportering av externa parter.', category: 'Digitala tjänster', subcategory: 'Säkerhet', level: null, iso_mapping: '8.8', implementation_guidance: 'Publicera en security.txt och VDP. Definiera kontaktvägar och svarsprocesser.', verification_guidance: 'Kontrollera att VDP finns publicerad och att security.txt är korrekt.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
  { control_number: 'DS25', title: 'Dependency and third-party library management', title_nl: 'Hantering av beroenden och tredjepartsbibliotek', description: 'Third-party libraries and dependencies in digital services shall be inventoried and monitored for known vulnerabilities.', description_nl: 'Tredjepartsbibliotek och beroenden i digitala tjänster ska inventeras och övervakas för kända sårbarheter.', category: 'Digitala tjänster', subcategory: 'Utveckling', level: null, iso_mapping: '8.28', implementation_guidance: 'Generera SBOM. Använd SCA-verktyg (Software Composition Analysis) i CI/CD-pipelinen.', verification_guidance: 'Kontrollera att SBOM finns och att SCA-verktyg körs automatiskt.', source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet' },
];

async function main(): Promise<void> {
  console.log('DIGG Digital Sakerhet Ingestion Script');
  console.log('========================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} controls.`);

  const output = {
    framework: {
      id: 'digg-digital-sakerhet',
      name: 'Digital Security Guidance',
      name_nl: 'Vägledning för digital säkerhet',
      issuing_body: 'Myndigheten för digital förvaltning (DIGG)',
      version: '2024',
      effective_date: '2024-01-01',
      scope: 'Security guidance for Swedish government digital services including API security, e-legitimation, and data protection',
      scope_sectors: ['government', 'digital_infrastructure'],
      structure_description: 'Organized by topic: digital services (DS1-DS15) covering design, API security, identity management, data protection, and cloud services.',
      source_url: 'https://www.digg.se/digitala-tjanster/digital-sakerhet',
      license: 'Public sector publication',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
