// scripts/ingest-hslf-fs.ts
// Socialstyrelsens foreskrifter om informationshantering (HSLF-FS) + PDL sakerhetskrav
// Authority: Socialstyrelsen / E-halsomyndigheten

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'hslf-fs-informationshantering.json');

const controls = [
  // -- Patientdatalagen sakerhetskrav (PDL security requirements) --
  { control_number: 'HV-1', title: 'Patient data access logging', title_nl: 'Loggning av atkomst till patientdata', description: 'All access to patient records shall be logged with user identity, timestamp, and action performed.', description_nl: 'All atkomst till patientjournaler ska loggas med anvandaridentitet, tidpunkt och utford atgard.', category: 'Patientdatalagen', subcategory: 'Loggning', level: 'Foreskrift', iso_mapping: '8.15', implementation_guidance: 'Implementera detaljerad loggning av all atkomst till patientdata. Logga vem, nar, vad och varfor.', verification_guidance: 'Kontrollera att loggning ar aktiv for alla patientdatasystem.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-2', title: 'Log review of patient data access', title_nl: 'Loggkontroll av atkomst till patientdata', description: 'Logs of patient data access shall be reviewed systematically to detect unauthorized access.', description_nl: 'Loggar over atkomst till patientdata ska granskas systematiskt for att upptacka obehorigad atkomst.', category: 'Patientdatalagen', subcategory: 'Loggkontroll', level: 'Foreskrift', iso_mapping: '8.15', implementation_guidance: 'Genomfor loggkontroller minst kvartalsvis. Anvand stickprovsmetod eller automatiserad avvikelsedetektering.', verification_guidance: 'Kontrollera att loggkontroller genomfors regelbundet.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-3', title: 'Inner confidentiality (inre sekretess)', title_nl: 'Inre sekretess', description: 'Access to patient data shall be restricted to healthcare personnel who need it for their current care assignment.', description_nl: 'Atkomst till patientdata ska begransas till vardpersonal som behover den for sitt aktuella varduppdrag.', category: 'Patientdatalagen', subcategory: 'Behorighetsstyrning', level: 'Foreskrift', iso_mapping: '5.15', implementation_guidance: 'Implementera behorighetsstyrning baserad pa vardrelation. Begransa atkomst till den vardenhet patienten ar registrerad vid.', verification_guidance: 'Kontrollera att behorighetsstyrning tilllampas och att atkomsten begransas till vardrelationen.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-4', title: 'Patient consent for information sharing (sammanhallen journalforing)', title_nl: 'Patientsamtycke for informationsdelning', description: 'Sharing patient data between care providers requires patient consent unless emergency exception applies.', description_nl: 'Delning av patientdata mellan vardgivare kraver patientsamtycke om inte nodsituation foreligger.', category: 'Patientdatalagen', subcategory: 'Samtycke', level: 'Foreskrift', iso_mapping: '5.34', implementation_guidance: 'Implementera samtyckeshantering i journalsystem. Dokumentera samtycke eller undantag.', verification_guidance: 'Kontrollera att samtyckeshantering fungerar och att samtycke dokumenteras.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-5', title: 'Patient blocking rights (sparr)', title_nl: 'Patients sparratt', description: 'Patients shall be able to block access to their records from specific care providers.', description_nl: 'Patienter ska kunna sparra atkomst till sina journaler fran specifika vardgivare.', category: 'Patientdatalagen', subcategory: 'Sparr', level: 'Foreskrift', iso_mapping: '5.34', implementation_guidance: 'Implementera sparrfunktion i journalsystem. Sakerstall att sparrregler respekteras i sammanhallen journalforing.', verification_guidance: 'Kontrollera att sparrfunktionen ar implementerad och fungerar korrekt.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },

  // -- HSLF-FS Informationshantering (Information handling regulations) --
  { control_number: 'HV-6', title: 'Information security management for healthcare', title_nl: 'Ledningssystem for informationssakerhet i halso- och sjukvarden', description: 'Healthcare organizations shall establish an information security management system covering patient data.', description_nl: 'Halso- och sjukvardsorganisationer ska uppractta ett ledningssystem for informationssakerhet som omfattar patientdata.', category: 'HSLF-FS', subcategory: 'Ledningssystem', level: 'Foreskrift', iso_mapping: '5.1', implementation_guidance: 'Uppractta ledningssystem for informationssakerhet. Integrera med verksamhetens kvalitetsledningssystem.', verification_guidance: 'Kontrollera att ledningssystem for informationssakerhet ar implementerat.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-7', title: 'Electronic patient record requirements', title_nl: 'Krav pa elektronisk patientjournal', description: 'Electronic patient records shall meet requirements for availability, integrity, and traceability.', description_nl: 'Elektroniska patientjournaler ska uppfylla krav pa tillganglighet, riktighet och sparbarhet.', category: 'HSLF-FS', subcategory: 'Journalsystem', level: 'Foreskrift', iso_mapping: '8.25', implementation_guidance: 'Sakerstall att journalsystem uppfyller Socialstyrelsens krav. Verifiera sparbarhet och riktighet.', verification_guidance: 'Kontrollera att journalsystem uppfyller foreskrivna krav.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-8', title: 'Authentication for healthcare systems', title_nl: 'Autentisering for vardssystem', description: 'Healthcare personnel shall authenticate using strong authentication (SITHS cards or equivalent) for accessing patient data.', description_nl: 'Vardpersonal ska autentisera sig med stark autentisering (SITHS-kort eller likvardigt) for att fa tillgang till patientdata.', category: 'HSLF-FS', subcategory: 'Autentisering', level: 'Foreskrift', iso_mapping: '8.5', implementation_guidance: 'Implementera stark autentisering med SITHS-kort eller eIDAS-nivakvivalent. Krav MFA for fjaurratkomst.', verification_guidance: 'Kontrollera att stark autentisering tilllampas for tillgang till patientdata.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-9', title: 'Healthcare data classification', title_nl: 'Klassificering av halso- och sjukvardsdata', description: 'Healthcare data shall be classified by sensitivity level with corresponding handling rules.', description_nl: 'Halso- och sjukvardsdata ska klassificeras efter kanslighetsniva med motsvarande hanteringsregler.', category: 'HSLF-FS', subcategory: 'Klassificering', level: 'Foreskrift', iso_mapping: '5.12', implementation_guidance: 'Klassificera patientdata. Beakta kansliga uppgifter (psykiatri, missbruk, sexuell halsa, genetik).', verification_guidance: 'Kontrollera att klassificering genomforts for patientdata.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-10', title: 'Archival requirements for healthcare records', title_nl: 'Arkivkrav for patientjournaler', description: 'Patient records shall be archived for at least 10 years after the last entry, with secure long-term preservation.', description_nl: 'Patientjournaler ska arkiveras i minst 10 ar efter sista anteckningen, med saker langtidsbevaring.', category: 'HSLF-FS', subcategory: 'Arkiv', level: 'Foreskrift', iso_mapping: '5.37', implementation_guidance: 'Sakerstall arkivering av patientjournaler i minst 10 ar. Anvand godkanda format for langtidsbevaring.', verification_guidance: 'Kontrollera att arkiveringskraven uppfylls.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },

  // -- Inera Sakerhetstjanster (Inera security services) --
  { control_number: 'HV-11', title: 'SITHS certificate requirements', title_nl: 'Krav pa SITHS-certifikat', description: 'Healthcare personnel accessing shared services shall use SITHS certificates for authentication and signing.', description_nl: 'Vardpersonal som anvander gemensamma tjanster ska anvanda SITHS-certifikat for autentisering och signering.', category: 'Inera sakerhetstjanster', subcategory: 'SITHS', level: 'Krav', iso_mapping: '5.16', implementation_guidance: 'Utfarda SITHS-certifikat till vardpersonal. Hantera certifikatlivscykel (utfardande, fornyelse, aterkallelse).', verification_guidance: 'Kontrollera att SITHS-certifikat anvands for authentication till gemensamma tjanster.', source_url: 'https://www.inera.se/tjanster/siths/' },
  { control_number: 'HV-12', title: 'HSA directory requirements', title_nl: 'Krav pa HSA-katalogen', description: 'Healthcare personnel and organizational units shall be registered in the HSA directory with correct attributes.', description_nl: 'Vardpersonal och organisatoriska enheter ska vara registrerade i HSA-katalogen med korrekta attribut.', category: 'Inera sakerhetstjanster', subcategory: 'HSA', level: 'Krav', iso_mapping: '5.16', implementation_guidance: 'Underhall HSA-registreringar. Sakerstall att personaluppgifter och organisationsdata ar korrekta.', verification_guidance: 'Kontrollera att HSA-registreringar ar aktuella och korrekta.', source_url: 'https://www.inera.se/tjanster/hsa/' },
  { control_number: 'HV-13', title: 'National Patient Overview (NPO) security', title_nl: 'Sakerhet for Nationell patientoversikt (NPO)', description: 'Access to the National Patient Overview shall comply with consent requirements and access logging.', description_nl: 'Atkomst till Nationell patientoversikt ska folja samtyckeskrav och atkomstloggning.', category: 'Inera sakerhetstjanster', subcategory: 'NPO', level: 'Krav', iso_mapping: '5.15', implementation_guidance: 'Implementera samtyckeskontroll for NPO-atkomst. Logga all atkomst. Informera patienter om NPO.', verification_guidance: 'Kontrollera att samtyckeskontroll och loggning fungerar for NPO.', source_url: 'https://www.inera.se/tjanster/npo/' },
  { control_number: 'HV-14', title: 'Secure messaging in healthcare (SDK)', title_nl: 'Saker meddelandeoverforing i varden (SDK)', description: 'Electronic messaging between healthcare providers shall use secure channels (SDK or equivalent).', description_nl: 'Elektronisk meddelandeoverforing mellan vardgivare ska anvanda sakra kanaler (SDK eller likvardig).', category: 'Inera sakerhetstjanster', subcategory: 'SDK', level: 'Krav', iso_mapping: '5.14', implementation_guidance: 'Anvand Saker digital kommunikation (SDK) for meddelandeoverforing. Kryptera meddelanden.', verification_guidance: 'Kontrollera att saker meddelandeoverforing anvands mellan vardgivare.', source_url: 'https://www.inera.se/tjanster/sdk/' },

  // -- E-halsomyndighetens krav --
  { control_number: 'HV-15', title: 'National medication list requirements', title_nl: 'Krav pa nationell lakemedelslista', description: 'Systems connecting to the national medication list shall meet E-halsomyndighetens security requirements.', description_nl: 'System som ansluts till nationella lakemedelslistan ska uppfylla E-halsomyndighetens sakerhetskrav.', category: 'E-halsomyndigheten', subcategory: 'Lakemedelslista', level: 'Krav', iso_mapping: '8.25', implementation_guidance: 'Uppfyll E-halsomyndighetens anslutningskrav. Implementera krav pa autentisering, loggning och integritetskontroll.', verification_guidance: 'Kontrollera att anslutningskraven uppfylls.', source_url: 'https://www.ehalsomyndigheten.se/' },
  { control_number: 'HV-16', title: 'Prescription security requirements', title_nl: 'Sakerhetskrav for recepthantering', description: 'Electronic prescriptions shall be signed with qualified electronic signatures and transmitted securely.', description_nl: 'Elektroniska recept ska signeras med kvalificerade elektroniska signaturer och overford sakert.', category: 'E-halsomyndigheten', subcategory: 'Recept', level: 'Krav', iso_mapping: '5.16', implementation_guidance: 'Anvand kvalificerade elektroniska signaturer (SITHS) for receptsignering. Sakerstall saker overforing.', verification_guidance: 'Kontrollera att receptsignering uppfyller kraven.', source_url: 'https://www.ehalsomyndigheten.se/' },
  { control_number: 'HV-17', title: 'Health data interoperability security', title_nl: 'Sakerhet vid interoperabilitet av halsodata', description: 'Interoperability interfaces for health data exchange shall implement authentication, encryption, and audit logging.', description_nl: 'Interoperabilitetsgranssnitt for utbyte av halsodata ska implementera autentisering, kryptering och revisionsloggning.', category: 'E-halsomyndigheten', subcategory: 'Interoperabilitet', level: 'Krav', iso_mapping: '8.26', implementation_guidance: 'Implementera mTLS for tjanst-till-tjanst-kommunikation. Validera meddelanden. Logga alla overforingar.', verification_guidance: 'Kontrollera att sakerhetskrav for interoperabilitet ar uppfyllda.', source_url: 'https://www.ehalsomyndigheten.se/' },
  { control_number: 'HV-18', title: 'Medical device cybersecurity', title_nl: 'Cybersakerhet for medicintekniska produkter', description: 'Network-connected medical devices shall be inventoried, segmented, and maintained with current security patches.', description_nl: 'Natverksanslutna medicintekniska produkter ska inventeras, segmenteras och underhallas med aktuella sakerhetsuppdateringar.', category: 'E-halsomyndigheten', subcategory: 'Medicinteknik', level: 'Krav', iso_mapping: '8.22', implementation_guidance: 'Inventera alla natverksanslutna medicintekniska produkter. Placera i dedikerade natverkssegment. Underhall firmware.', verification_guidance: 'Kontrollera att medicintekniska produkter ar inventerade och segmenterade.', source_url: 'https://www.ehalsomyndigheten.se/' },

  // -- Tillagg: Fordjupad halso- och sjukvard --
  { control_number: 'HV-19', title: 'Telemedicine security requirements', title_nl: 'Sakerhetskrav for telemedicin', description: 'Telemedicine services shall use encrypted video and audio with patient identity verification before consultation.', description_nl: 'Telemedicintjanster ska anvanda krypterad video och ljud med patientidentitetsverifiering fore konsultation.', category: 'HSLF-FS', subcategory: 'Telemedicin', level: 'Foreskrift', iso_mapping: '8.24', implementation_guidance: 'Anvand krypterade videoplattformar. Verifiera patientens identitet med e-legitimation eller tva-faktor-identifiering fore konsultation.', verification_guidance: 'Kontrollera att telemedicintjanster anvander kryptering och identitetsverifiering.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-20', title: 'Patient data portability and export', title_nl: 'Portabilitet och export av patientdata', description: 'Systems shall support standardized export of patient data for portability and care provider transition.', description_nl: 'System ska stodja standardiserad export av patientdata for portabilitet och vardgivarbyte.', category: 'HSLF-FS', subcategory: 'Portabilitet', level: 'Foreskrift', iso_mapping: '5.34', implementation_guidance: 'Implementera export i standardformat (CDA, FHIR). Sakerstall att exporterad data ar komplett och korrekt.', verification_guidance: 'Kontrollera att dataexport fungerar och att standardformat anvands.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-21', title: 'Emergency access (break-the-glass)', title_nl: 'Nodatkomst (break-the-glass)', description: 'Emergency access procedures shall allow authorized personnel to override normal access controls in life-threatening situations.', description_nl: 'Nodatkomstrutiner ska mojliggora for behorig personal att overskrida normala atkomstkontroller i livshotande situationer.', category: 'Patientdatalagen', subcategory: 'Nodatkomst', level: 'Foreskrift', iso_mapping: '5.15', implementation_guidance: 'Implementera break-the-glass-funktion med sarskild loggning. Krav efterhandsbedomning av varje nodatkomst.', verification_guidance: 'Kontrollera att nodatkomstfunktion finns och att alla anvandningar granskas i efterhand.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-22', title: 'Healthcare network segmentation', title_nl: 'Natverkssegmentering for halso- och sjukvarden', description: 'Healthcare networks shall be segmented separating patient data systems, medical devices, administrative systems, and guest networks.', description_nl: 'Halso- och sjukvardsnatverk ska segmenteras med separering av patientdatasystem, medicintekniska produkter, administrativa system och gastnatverk.', category: 'HSLF-FS', subcategory: 'Natverkssegmentering', level: 'Foreskrift', iso_mapping: '8.22', implementation_guidance: 'Segmentera natverket i zoner: patientdata, medicinteknik, administration och gast. Tilllampa brandvaggsregler mellan zoner.', verification_guidance: 'Kontrollera att natverkssegmentering ar implementerad.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-23', title: 'Research data pseudonymization', title_nl: 'Pseudonymisering av forskningsdata', description: 'Patient data used for research purposes shall be pseudonymized with the key stored separately under strict access control.', description_nl: 'Patientdata som anvands for forskningsandamal ska pseudonymiseras med nyckeln lagrad separat under strikt atkomstkontroll.', category: 'Patientdatalagen', subcategory: 'Forskning', level: 'Foreskrift', iso_mapping: '8.11', implementation_guidance: 'Pseudonymisera patientdata fore utlamnande for forskning. Lagra kopplingsnyckel under strikt atkomstkontroll hos vardgivaren.', verification_guidance: 'Kontrollera att forskningsdata ar pseudonymiserad och att kopplingsnyckel ar skyddad.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-24', title: 'Mobile device management in healthcare', title_nl: 'Hantering av mobila enheter i varden', description: 'Mobile devices used for accessing patient data shall be managed with MDM including encryption, remote wipe, and application control.', description_nl: 'Mobila enheter som anvands for atkomst till patientdata ska hanteras med MDM inklusive kryptering, fjaarradering och applikationskontroll.', category: 'HSLF-FS', subcategory: 'Mobila enheter', level: 'Foreskrift', iso_mapping: '8.1', implementation_guidance: 'Implementera MDM for alla mobila enheter med patientdata. Kryptera enheter. Konfigurera fjarradering.', verification_guidance: 'Kontrollera att MDM ar implementerat for mobila enheter i varden.', source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/' },
  { control_number: 'HV-25', title: 'Clinical decision support system integrity', title_nl: 'Integritet for kliniskt beslutsstodssystem', description: 'Clinical decision support systems shall be validated for accuracy and maintained to prevent incorrect medical recommendations.', description_nl: 'Kliniska beslutsstodssystem ska valideras for korrekthet och underhallas for att forhindra felaktiga medicinska rekommendationer.', category: 'E-halsomyndigheten', subcategory: 'Beslutsstod', level: 'Krav', iso_mapping: '8.25', implementation_guidance: 'Validera beslutsstodssystem for klinisk korrekthet. Underhall kunskapsbasen. Logga alla anvandningar.', verification_guidance: 'Kontrollera att kliniska beslutsstodssystem ar validerade och underhallna.', source_url: 'https://www.ehalsomyndigheten.se/' },
];

async function main(): Promise<void> {
  console.log('HSLF-FS Informationshantering Ingestion Script');
  console.log('================================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} requirements.`);

  const output = {
    framework: {
      id: 'hslf-fs-informationshantering',
      name: 'Healthcare Information Handling Requirements',
      name_nl: 'Foreskrifter om informationshantering i halso- och sjukvarden',
      issuing_body: 'Socialstyrelsen / E-halsomyndigheten / Inera',
      version: '2024',
      effective_date: '2016-01-01',
      scope: 'Information security requirements for Swedish healthcare including patient data law (PDL), HSLF-FS regulations, Inera security services (SITHS, HSA, NPO), and E-halsomyndighetens requirements',
      scope_sectors: ['healthcare'],
      structure_description: 'Organized by source: Patient Data Act requirements (HV-1 to HV-5, HV-21, HV-23), HSLF-FS regulations (HV-6 to HV-10, HV-19, HV-20, HV-22, HV-24), Inera security services (HV-11 to HV-14), and E-halsomyndigheten requirements (HV-15 to HV-18, HV-25).',
      source_url: 'https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/',
      license: 'Swedish government regulation (public)',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
