// scripts/ingest-energi-transport.ts
// Energimyndighetens and Transportstyrelsens cybersecurity requirements
// Authority: Energimyndigheten / Transportstyrelsen

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'energi-transport-sakerhet.json');

const controls = [
  // -- Energimyndighetens krav (Energy sector) --
  { control_number: 'ES-1', title: 'OT/SCADA network segmentation', title_nl: 'OT/SCADA-natverkssegmentering', description: 'Operational technology networks controlling energy systems shall be segmented from corporate IT networks.', description_nl: 'Operativa tekniknatverk som styr energisystem ska segmenteras fran foretagens IT-natverk.', category: 'Energisektor', subcategory: 'Segmentering', level: 'Krav', iso_mapping: '8.22', implementation_guidance: 'Implementera DMZ mellan IT- och OT-natverk. Begransa trafik till definierade och dokumenterade floden.', verification_guidance: 'Kontrollera att IT/OT-segmentering ar implementerad och korrekt konfigurerad.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-2', title: 'Energy system access control', title_nl: 'Atkomstkontroll for energisystem', description: 'Access to energy control systems shall use multi-factor authentication with individual accounts.', description_nl: 'Atkomst till energistyrningssystem ska anvanda flerfaktorsautentisering med individuella konton.', category: 'Energisektor', subcategory: 'Atkomstkontroll', level: 'Krav', iso_mapping: '8.5', implementation_guidance: 'Implementera MFA for atkomst till SCADA/DCS-system. Forbbjud delade konton. Logga all atkomst.', verification_guidance: 'Kontrollera att MFA ar implementerat och att delade konton eliminerats.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-3', title: 'Incident reporting for energy sector', title_nl: 'Incidentrapportering for energisektorn', description: 'Cybersecurity incidents affecting energy supply shall be reported to the Swedish Energy Agency and CERT-SE.', description_nl: 'Cybersakerhetsincidenter som paverkar energiforsorjningen ska rapporteras till Energimyndigheten och CERT-SE.', category: 'Energisektor', subcategory: 'Incidentrapportering', level: 'Krav', iso_mapping: '5.24', implementation_guidance: 'Uppractta rapporteringsrutiner for energisektorincidenter. Rapportera till Energimyndigheten och CERT-SE.', verification_guidance: 'Kontrollera att incidentrapporteringsrutiner ar upprattade.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-4', title: 'Energy system patch management', title_nl: 'Patchhantering for energisystem', description: 'Security patches for energy control systems shall be tested and applied according to a defined schedule.', description_nl: 'Sakerhetsuppdateringar for energistyrningssystem ska testas och tilllampas enligt en definierad tidsplan.', category: 'Energisektor', subcategory: 'Patchhantering', level: 'Krav', iso_mapping: '8.8', implementation_guidance: 'Uppractta patchhanteringsprocess for OT-system. Testa patchar i testmiljo innan tillllampning pa produktion.', verification_guidance: 'Kontrollera att patchhanteringsprocess finns for OT-system.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-5', title: 'Energy sector business continuity', title_nl: 'Driftkontinuitet for energisektorn', description: 'Energy operators shall maintain business continuity plans ensuring continued energy supply during cyber incidents.', description_nl: 'Energioperatorer ska underhalla driftkontinuitetsplaner som sakerstaller fortsatt energiforsorjning under cyberincidenter.', category: 'Energisektor', subcategory: 'Kontinuitet', level: 'Krav', iso_mapping: '5.29', implementation_guidance: 'Uppractta driftkontinuitetsplaner for cyberincidenter. Inkludera manuell styrning som reservlosning.', verification_guidance: 'Kontrollera att driftkontinuitetsplaner finns och ar testade.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-6', title: 'Energy sector supply chain assessment', title_nl: 'Leveranskedjebedomning for energisektorn', description: 'Critical suppliers of energy systems and components shall be assessed for cybersecurity risks.', description_nl: 'Kritiska leverantorer av energisystem och komponenter ska bedommas avseende cybersakerhetsrisker.', category: 'Energisektor', subcategory: 'Leveranskedja', level: 'Krav', iso_mapping: '5.19', implementation_guidance: 'Inventera kritiska leverantorer. Bedome cybersakerhetsrisker i leveranskedjan. Inkludera krav i avtal.', verification_guidance: 'Kontrollera att leverantorsbedomningar genomfors.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-7', title: 'Physical security for energy infrastructure', title_nl: 'Fysisk sakerhet for energiinfrastruktur', description: 'Physical security measures for energy facilities shall include access control, monitoring, and intrusion detection.', description_nl: 'Fysiska sakerhetsatgarder for energianlaggningar ska inkludera tilltradsekontroll, overvakning och inbrottsdetektering.', category: 'Energisektor', subcategory: 'Fysisk sakerhet', level: 'Krav', iso_mapping: '7.2', implementation_guidance: 'Implementera passersystem, kameraovervakning och inbrottslarm vid energianlaggningar.', verification_guidance: 'Kontrollera att fysisk sakerhet ar implementerad vid energianlaggningar.', source_url: 'https://www.energimyndigheten.se/' },

  // -- Transportstyrelsen IT-sakerhet (Transport sector) --
  { control_number: 'TS-1', title: 'Transport control system security', title_nl: 'Sakerhet for transportstyrningssystem', description: 'IT systems controlling transport infrastructure shall meet cybersecurity requirements proportionate to their criticality.', description_nl: 'IT-system som styr transportinfrastruktur ska uppfylla cybersakerhetskrav i proportion till deras kritikalitet.', category: 'Transportsektor', subcategory: 'Styrningssystem', level: 'Krav', iso_mapping: '8.9', implementation_guidance: 'Klassificera transportstyrningssystem efter kritikalitet. Tilllampa sakerhetsatgarder baserat pa klassificering.', verification_guidance: 'Kontrollera att sakerhetsatgarder ar implementerade for transportstyrningssystem.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-2', title: 'Maritime cybersecurity requirements', title_nl: 'Cybersakerhetskrav for sjofort', description: 'Ships and port facilities shall implement cybersecurity measures in accordance with IMO guidelines and ISM code.', description_nl: 'Fartyg och hamnanlaggningar ska implementera cybersakerhetsatgarder i enlighet med IMO:s riktlinjer och ISM-koden.', category: 'Transportsektor', subcategory: 'Sjofort', level: 'Krav', iso_mapping: '5.1', implementation_guidance: 'Integrera cybersakerhet i ISM-koden. Genomfor cyberriskbedomning for fartyg och hamnanlaggningar.', verification_guidance: 'Kontrollera att cybersakerhet ar integrerad i sjofartens sakerhetsarbete.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-3', title: 'Aviation cybersecurity (NIS2 scope)', title_nl: 'Cybersakerhet for luftfart (NIS2-omfang)', description: 'Air traffic management and airport systems shall implement cybersecurity risk management in line with NIS2.', description_nl: 'Flygledningssystem och flygplatssystem ska implementera cybersakerhetsriskhantering i linje med NIS2.', category: 'Transportsektor', subcategory: 'Luftfart', level: 'Krav', iso_mapping: '5.1', implementation_guidance: 'Tilllampa NIS2-krav for flygledning och flygplatsdrift. Genomfor sakerhetsbedommningar av ATM-system.', verification_guidance: 'Kontrollera att NIS2-krav ar implementerade for luftfartsverksamhet.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-4', title: 'Railway signaling system security', title_nl: 'Sakerhet for jarnvagssignaleringssystem', description: 'Railway signaling and control systems shall be protected against unauthorized access and manipulation.', description_nl: 'Jarnvagssignalerings- och styrningssystem ska skyddas mot obehorigad atkomst och manipulation.', category: 'Transportsektor', subcategory: 'Jarnvag', level: 'Krav', iso_mapping: '8.20', implementation_guidance: 'Segmentera signaleringsnatverk. Implementera atkomstkontroll och loggning for ERTMS/ETCS-system.', verification_guidance: 'Kontrollera att sakerhetsatgarder ar implementerade for jarnvagssignaleringssystem.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-5', title: 'Transport sector incident reporting', title_nl: 'Incidentrapportering for transportsektorn', description: 'Cybersecurity incidents affecting transport operations shall be reported to Transportstyrelsen and CERT-SE.', description_nl: 'Cybersakerhetsincidenter som paverkar transportverksamhet ska rapporteras till Transportstyrelsen och CERT-SE.', category: 'Transportsektor', subcategory: 'Incidentrapportering', level: 'Krav', iso_mapping: '5.24', implementation_guidance: 'Uppractta rutiner for incidentrapportering till Transportstyrelsen. Sakerstall att NIS2-tidsfrister foljs.', verification_guidance: 'Kontrollera att incidentrapporteringsrutiner ar upprattade for transportsektorn.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-6', title: 'Vehicle cybersecurity (connected vehicles)', title_nl: 'Cybersakerhet for fordon (uppkopplade fordon)', description: 'Connected vehicles and their backend systems shall implement cybersecurity measures per UNECE WP.29 R155/R156.', description_nl: 'Uppkopplade fordon och deras back-end-system ska implementera cybersakerhetsatgarder enligt UNECE WP.29 R155/R156.', category: 'Transportsektor', subcategory: 'Fordonscyber', level: 'Krav', iso_mapping: '8.25', implementation_guidance: 'Implementera cybersakerhetshanteringssystem enligt UNECE R155. Tilllampa saker uppdateringshantering enligt R156.', verification_guidance: 'Kontrollera att fordonscybersakerhetskrav uppfylls.', source_url: 'https://www.transportstyrelsen.se/' },

  // -- Tillagg: Energisektor fordjupning --
  { control_number: 'ES-8', title: 'SCADA protocol security', title_nl: 'SCADA-protokollsakerhet', description: 'Legacy SCADA protocols (Modbus, DNP3) shall be protected through network encapsulation or protocol-aware firewalls.', description_nl: 'Aldre SCADA-protokoll (Modbus, DNP3) ska skyddas genom natverksinkapsling eller protokollmedvetna brandvaggar.', category: 'Energisektor', subcategory: 'Protokollsakerhet', level: 'Krav', iso_mapping: '8.22', implementation_guidance: 'Implementera protokollmedvetna brandvaggar for Modbus/DNP3-trafik. Kryptera dar mojligt. Overvaka for anomalier.', verification_guidance: 'Kontrollera att SCADA-protokoll ar skyddade med lampliga brandvaggsregler.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-9', title: 'Energy sector personnel security awareness', title_nl: 'Sakerhetsmedvetenhet for energisektorpersonal', description: 'Personnel operating energy control systems shall receive cybersecurity training specific to OT environments.', description_nl: 'Personal som driver energistyrningssystem ska genomga cybersakerhetsutbildning specifik for OT-miljoer.', category: 'Energisektor', subcategory: 'Utbildning', level: 'Krav', iso_mapping: '6.3', implementation_guidance: 'Genomfor OT-specifik cybersakerhetsutbildning for driftpersonal. Inkludera hantering av USB-enheter, fjarrstyrning och incidentrapportering.', verification_guidance: 'Kontrollera att OT-utbildning genomfors for relevant personal.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-10', title: 'Backup power testing for energy facilities', title_nl: 'Testning av reservkraft for energianlaggningar', description: 'Backup power systems at energy facilities shall be tested quarterly under load to verify operational readiness.', description_nl: 'Reservkraftsystem vid energianlaggningar ska testas kvartalsvis under belastning for att verifiera driftberedskap.', category: 'Energisektor', subcategory: 'Reservkraft', level: 'Krav', iso_mapping: '7.11', implementation_guidance: 'Testa reservkraft kvartalsvis under realistisk belastning. Dokumentera testresultat och atgarder.', verification_guidance: 'Kontrollera att reservkraft testas regelbundet och att testprotokoll finns.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-11', title: 'Remote access control for energy systems', title_nl: 'Fjarratkomstkontroll for energisystem', description: 'Remote access to energy control systems shall use VPN with multi-factor authentication and session logging.', description_nl: 'Fjarratkomst till energistyrningssystem ska anvanda VPN med flerfaktorsautentisering och sessionsloggning.', category: 'Energisektor', subcategory: 'Fjarratkomst', level: 'Krav', iso_mapping: '8.5', implementation_guidance: 'Implementera VPN med MFA for all fjarratkomst till OT-system. Logga alla sessioner. Begransa tidsbaserade sessioner.', verification_guidance: 'Kontrollera att fjarratkomst ar skyddad med VPN och MFA.', source_url: 'https://www.energimyndigheten.se/' },
  { control_number: 'ES-12', title: 'Vulnerability scanning for energy OT networks', title_nl: 'Sarbarhetsscanning for energi-OT-natverk', description: 'OT networks in energy facilities shall be scanned for vulnerabilities using OT-safe scanning tools.', description_nl: 'OT-natverk i energianlaggningar ska skannas for sarbarheter med OT-sakra skanningsverktyg.', category: 'Energisektor', subcategory: 'Sarbarhetsscanning', level: 'Krav', iso_mapping: '8.8', implementation_guidance: 'Anvand passiva skanningsverktyg eller OT-validerade skanners. Skanna kvartalsvis. Avhjalp kritiska sarbarheter.', verification_guidance: 'Kontrollera att sarbarhetsscanning genomfors for OT-natverk.', source_url: 'https://www.energimyndigheten.se/' },

  // -- Tillagg: Transportsektor fordjupning --
  { control_number: 'TS-7', title: 'Road infrastructure control system security', title_nl: 'Sakerhet for vaginfrastrukturstyrningssystem', description: 'Traffic management systems, tunnel control systems, and bridge control systems shall implement cybersecurity measures.', description_nl: 'Trafikledningssystem, tunnelstyrningssystem och brostyrningssystem ska implementera cybersakerhetsatgarder.', category: 'Transportsektor', subcategory: 'Vaginfrastruktur', level: 'Krav', iso_mapping: '8.9', implementation_guidance: 'Segmentera styrningssystem for vaginfrastruktur. Implementera atkomstkontroll och overvakning.', verification_guidance: 'Kontrollera att cybersakerhetsatgarder ar implementerade for vaginfrastruktursystem.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-8', title: 'Transport sector business continuity', title_nl: 'Driftkontinuitet for transportsektorn', description: 'Transport operators shall maintain continuity plans ensuring safe degraded operation during cyber incidents.', description_nl: 'Transportoperatorer ska underhalla kontinuitetsplaner som sakerstaller saker degraderad drift under cyberincidenter.', category: 'Transportsektor', subcategory: 'Kontinuitet', level: 'Krav', iso_mapping: '5.29', implementation_guidance: 'Uppractta kontinuitetsplaner med manuella reservforfaranden. Prioritera trafiksakerhet vid degraderad drift.', verification_guidance: 'Kontrollera att kontinuitetsplaner finns och ar testade for transportsektorn.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-9', title: 'GNSS/GPS spoofing protection for transport', title_nl: 'Skydd mot GNSS/GPS-manipulation for transport', description: 'Transport systems relying on GNSS positioning shall implement spoofing detection and fallback navigation.', description_nl: 'Transportsystem som forlitar sig pa GNSS-positionering ska implementera manipulationsdetektering och reservnavigering.', category: 'Transportsektor', subcategory: 'Navigationsskydd', level: 'Krav', iso_mapping: '8.20', implementation_guidance: 'Implementera GNSS-anomalidetektering. Uppractta reservnavigeringsformagor. Overvaka for spoofingsignaler.', verification_guidance: 'Kontrollera att GNSS-skydd ar implementerat.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-10', title: 'Port facility cybersecurity plan', title_nl: 'Hamnanlaggnings cybersakerhetsplan', description: 'Port facilities shall integrate cybersecurity into their ISPS Code facility security plan.', description_nl: 'Hamnanlaggningar ska integrera cybersakerhet i sin ISPS-kod-sakerhetesplan for anlaggningen.', category: 'Transportsektor', subcategory: 'Hamnanlaggning', level: 'Krav', iso_mapping: '5.1', implementation_guidance: 'Integrera cybersakerhet i PFSP (Port Facility Security Plan). Inkludera IT/OT-system i sakerhetsbedomningen.', verification_guidance: 'Kontrollera att cybersakerhet ingar i hamnanlaggningens sakerhetsplan.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-11', title: 'Aviation ATC system integrity', title_nl: 'Integritet for flygtrafikledningssystem', description: 'Air traffic control systems shall have integrity protection ensuring commands cannot be tampered with.', description_nl: 'Flygtrafikledningssystem ska ha integritetsskydd som sakerstaller att kommandon inte kan manipuleras.', category: 'Transportsektor', subcategory: 'Luftfart', level: 'Krav', iso_mapping: '8.25', implementation_guidance: 'Implementera integritetskontroll for ATC-kommandon. Anvand signerade meddelanden dar mojligt.', verification_guidance: 'Kontrollera att integritetsskydd finns for flygtrafikledningssystem.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-12', title: 'Railway ERTMS cybersecurity', title_nl: 'Cybersakerhet for ERTMS-system', description: 'European Rail Traffic Management System (ERTMS) implementations shall comply with ERA cybersecurity guidelines.', description_nl: 'Implementeringar av European Rail Traffic Management System (ERTMS) ska folja ERA:s cybersakerhetsriktlinjer.', category: 'Transportsektor', subcategory: 'Jarnvag', level: 'Krav', iso_mapping: '8.9', implementation_guidance: 'Tilllampa ERA:s cybersakerhetsriktlinjer for ERTMS. Genomfor riskbedomning av ERTMS-komponenter.', verification_guidance: 'Kontrollera att ERTMS-cybersakerhet uppfyller ERA:s krav.', source_url: 'https://www.transportstyrelsen.se/' },
  { control_number: 'TS-13', title: 'Transport sector supply chain security', title_nl: 'Leveranskedjesakerhet for transportsektorn', description: 'Critical transport system suppliers shall be assessed for cybersecurity risks and required to meet minimum security standards.', description_nl: 'Kritiska leverantorer av transportsystem ska bedommas avseende cybersakerhetsrisker och kravas uppfylla minimisakerhetsstandarder.', category: 'Transportsektor', subcategory: 'Leveranskedja', level: 'Krav', iso_mapping: '5.19', implementation_guidance: 'Bedome leverantorer av kritiska transportsystem. Inkludera cybersakerhetskrav i avtal.', verification_guidance: 'Kontrollera att leverantorsbedomningar genomfors for transportsektorn.', source_url: 'https://www.transportstyrelsen.se/' },
];

async function main(): Promise<void> {
  console.log('Energi-Transport Sakerhet Ingestion Script');
  console.log('=============================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} requirements.`);

  const output = {
    framework: {
      id: 'energi-transport-sakerhet',
      name: 'Energy and Transport Sector Cybersecurity Requirements',
      name_nl: 'Cybersakerhetskrav for energi- och transportsektorn',
      issuing_body: 'Energimyndigheten / Transportstyrelsen',
      version: '2025',
      effective_date: '2025-01-01',
      scope: 'Cybersecurity requirements for Swedish energy operators (SCADA/OT security, incident reporting) and transport sector (maritime, aviation, railway, road) under NIS2',
      scope_sectors: ['energy', 'transport'],
      structure_description: 'Organized by sector: energy (ES-1 to ES-12) covering OT/SCADA, access control, incident reporting, supply chain, and remote access; transport (TS-1 to TS-13) covering maritime, aviation, railway, road infrastructure, and connected vehicles.',
      source_url: 'https://www.energimyndigheten.se/',
      license: 'Swedish government requirements (public)',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
