// scripts/ingest-fi-it-verksamhet.ts
// Finansinspektionen (FI) Foreskrifter om IT-verksamhet (FFFS)
// Authority: Finansinspektionen (FI)

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'fi-it-verksamhet.json');

const controls = [
  // -- Styrning och organisation (Governance and organization) --
  { control_number: 'FI-1', title: 'IT governance framework', title_nl: 'Ramverk for IT-styrning', description: 'Financial institutions shall establish an IT governance framework aligned with the overall business strategy.', description_nl: 'Finansiella institut ska uppractta ett ramverk for IT-styrning som ar i linje med den overgripande verksamhetsstrategin.', category: 'Styrning', subcategory: 'Ramverk', level: 'Foreskrift', iso_mapping: '5.1', implementation_guidance: 'Uppractta IT-strategi och IT-policy godkand av styrelsen. Inkludera riskaptit for IT-risker.', verification_guidance: 'Kontrollera att IT-styrningsramverk ar uppratttat och godkant av styrelsen.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-2', title: 'IT risk management', title_nl: 'IT-riskhantering', description: 'A structured IT risk management process shall be integrated into the institution\'s overall risk management.', description_nl: 'En strukturerad IT-riskhanteringsprocess ska integreras i institutets overgripande riskhantering.', category: 'Styrning', subcategory: 'Riskhantering', level: 'Foreskrift', iso_mapping: '5.1', implementation_guidance: 'Integrera IT-risker i den samlade riskhanteringen. Genomfor IT-riskbedomningar minst arligen.', verification_guidance: 'Kontrollera att IT-risker ingår i den samlade riskbilden.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-3', title: 'IT security officer appointment', title_nl: 'Utsedd IT-sakerhetsansvarig', description: 'An IT security officer with sufficient authority and competence shall be appointed.', description_nl: 'En IT-sakerhetsansvarig med tillracklig befogenhet och kompetens ska utses.', category: 'Styrning', subcategory: 'Roller', level: 'Foreskrift', iso_mapping: '5.2', implementation_guidance: 'Utse en IT-sakerhetsansvarig med rapportering till ledningen. Sakerstall oberoende fran IT-driften.', verification_guidance: 'Kontrollera att IT-sakerhetsansvarig ar utsedd och har tillrackliga befogenheter.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-4', title: 'Board oversight of IT risks', title_nl: 'Styrelsens overvakning av IT-risker', description: 'The board shall regularly review IT risks and the effectiveness of IT security measures.', description_nl: 'Styrelsen ska regelbundet granska IT-risker och effektiviteten i IT-sakerhetsatgarder.', category: 'Styrning', subcategory: 'Styrelseovervakning', level: 'Foreskrift', iso_mapping: '5.1', implementation_guidance: 'Rapportera IT-risker till styrelsen kvartalsvis. Inkludera riskbild, incidenter och atgardsplan.', verification_guidance: 'Kontrollera att styrelsen regelbundet grranskar IT-risker.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },

  // -- IT-system och utveckling (IT systems and development) --
  { control_number: 'FI-5', title: 'System development lifecycle security', title_nl: 'Sakerhet i systemutvecklingslivscykeln', description: 'Security requirements shall be integrated into all phases of the system development lifecycle.', description_nl: 'Sakerhetskrav ska integreras i alla faser av systemutvecklingslivscykeln.', category: 'System och utveckling', subcategory: 'Utveckling', level: 'Foreskrift', iso_mapping: '8.25', implementation_guidance: 'Tilllampa SSDLC. Genomfor kodgranskning, sakkerhetstestning och sarbarhetsanalys fore driftsattning.', verification_guidance: 'Kontrollera att sakerhetskrav ingår i utvecklingsprocessen.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-6', title: 'Test environment separation', title_nl: 'Separation av testmiljo', description: 'Test environments shall be separated from production and shall not contain real customer data.', description_nl: 'Testmiljoer ska vara separerade fran produktion och ska inte innehalla riktig kunddata.', category: 'System och utveckling', subcategory: 'Testmiljo', level: 'Foreskrift', iso_mapping: '8.31', implementation_guidance: 'Sakerstall separation mellan test- och produktionsmiljo. Anonymisera kunddata i testmiljoer.', verification_guidance: 'Kontrollera att testmiljoer ar separerade och att kunddata ar anonymiserad.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-7', title: 'Application security testing', title_nl: 'Sakkerhetstestning av applikationer', description: 'Applications shall undergo security testing including penetration testing before deployment.', description_nl: 'Applikationer ska genomga sakkerhetstestning inklusive penetrationstestning fore driftsattning.', category: 'System och utveckling', subcategory: 'Testning', level: 'Foreskrift', iso_mapping: '8.29', implementation_guidance: 'Genomfor penetrationstester av kritiska applikationer. Sakerstall att identifierade brister atgardas.', verification_guidance: 'Kontrollera att sakkerhetstestning genomfors och att brister atgardas.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },

  // -- Driftsakerhet (Operational security) --
  { control_number: 'FI-8', title: 'IT service continuity', title_nl: 'IT-tjanstekontinuitet', description: 'Continuity plans shall ensure critical financial services remain available during disruptions.', description_nl: 'Kontinuitetsplaner ska sakerstalla att kritiska finansiella tjanster forblir tillgangliga vid storningar.', category: 'Driftsakerhet', subcategory: 'Kontinuitet', level: 'Foreskrift', iso_mapping: '5.29', implementation_guidance: 'Uppractta IT-kontinuitetsplaner for kritiska system. Definiera RTO och RPO for betalningstjanster och karnbanksystem.', verification_guidance: 'Kontrollera att IT-kontinuitetsplaner finns och har testats.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-9', title: 'Access control for financial systems', title_nl: 'Atkomstkontroll for finansiella system', description: 'Access to financial systems shall be controlled using the principle of least privilege with segregation of duties.', description_nl: 'Atkomst till finansiella system ska kontrolleras med principen om minsta behorigbhet och arbetsfordelning.', category: 'Driftsakerhet', subcategory: 'Atkomstkontroll', level: 'Foreskrift', iso_mapping: '5.15', implementation_guidance: 'Implementera RBAC for finansiella system. Tilllampa arbetsfordelning (separation of duties) for kritiska transaktioner.', verification_guidance: 'Kontrollera att atkomstkontroller och arbetsfordelning tilllampas.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-10', title: 'Transaction monitoring and fraud detection', title_nl: 'Transaktionsovervakning och bedrageriupptackt', description: 'Systems for monitoring transactions and detecting fraudulent activity shall be implemented.', description_nl: 'System for att overvaka transaktioner och upptacka bedraglig verksamhet ska implementeras.', category: 'Driftsakerhet', subcategory: 'Overvakning', level: 'Foreskrift', iso_mapping: '8.16', implementation_guidance: 'Implementera realtidsovervakning av transaktioner. Konfigurera regler for anomalidetektering.', verification_guidance: 'Kontrollera att transaktionsovervakning ar aktiv och att larm hanteras.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-11', title: 'Encryption of financial data', title_nl: 'Kryptering av finansiella uppgifter', description: 'Financial data shall be encrypted in transit and at rest using approved cryptographic methods.', description_nl: 'Finansiella uppgifter ska krypteras vid overforing och lagring med godkanda kryptografiska metoder.', category: 'Driftsakerhet', subcategory: 'Kryptering', level: 'Foreskrift', iso_mapping: '8.24', implementation_guidance: 'Tilllampa TLS 1.2+ for all kommunikation. Kryptera databaser med finansiella uppgifter.', verification_guidance: 'Kontrollera att kryptering tilllampas pa finansiella data.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },

  // -- Utkontraktering (Outsourcing) --
  { control_number: 'FI-12', title: 'IT outsourcing risk assessment', title_nl: 'Riskbedomning vid IT-utkontraktering', description: 'A risk assessment shall be performed before outsourcing IT services, including assessment of the provider.', description_nl: 'En riskbedomning ska genomforas fore utkontraktering av IT-tjanster, inklusive bedomning av leverantoren.', category: 'Utkontraktering', subcategory: 'Riskbedomning', level: 'Foreskrift', iso_mapping: '5.19', implementation_guidance: 'Genomfor riskbedomning av IT-utkontraktering. Bedom leverantorens sakerhetsformaga, finansiella stabilitet och juridiska jurisdiktion.', verification_guidance: 'Kontrollera att riskbedomning genomfortas for alla IT-utkontrakteringar.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-13', title: 'Cloud service requirements for financial institutions', title_nl: 'Krav pa molntjanster for finansiella institut', description: 'Cloud services used by financial institutions shall meet regulatory requirements for data residency, audit rights, and exit strategies.', description_nl: 'Molntjanster som anvands av finansiella institut ska uppfylla regulatoriska krav avseende datalokaliserring, revisionsratt och exitstrategier.', category: 'Utkontraktering', subcategory: 'Molntjanster', level: 'Foreskrift', iso_mapping: '5.23', implementation_guidance: 'Sakerstall att molnleverantorer uppfyller FI:s krav. Krav revisionsrattigheter, dataresidency i EU/EES och exitplan.', verification_guidance: 'Kontrollera att molntjanster uppfyller regulatoriska krav.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-14', title: 'Outsourcing provider monitoring', title_nl: 'Overvakning av utkontraktelingsleverantorer', description: 'Outsourced IT service providers shall be monitored regularly for compliance with contractual security requirements.', description_nl: 'Utkontrakterade IT-tjansteleverantorer ska overvakas regelbundet avseende efterlevnad av avtalade sakerhetskrav.', category: 'Utkontraktering', subcategory: 'Uppfoljning', level: 'Foreskrift', iso_mapping: '5.22', implementation_guidance: 'Genomfor regelbundna leverantorsgranskningar. Krav revisionsrapporter (SOC 2 eller ISO 27001).', verification_guidance: 'Kontrollera att leverantorsgranskningar genomfors regelbundet.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },

  // -- Incidenthantering (Incident management) --
  { control_number: 'FI-15', title: 'IT incident reporting to FI', title_nl: 'IT-incidentrapportering till FI', description: 'Significant IT incidents affecting financial services shall be reported to FI within defined timeframes.', description_nl: 'Betydande IT-incidenter som paverkar finansiella tjanster ska rapporteras till FI inom definierade tidsramar.', category: 'Incidenthantering', subcategory: 'Rapportering', level: 'Foreskrift', iso_mapping: '5.24', implementation_guidance: 'Rapportera allvarliga IT-incidenter till FI inom 4 timmar. Lamna uppfoljningsrapport inom 3 vardagar.', verification_guidance: 'Kontrollera att incidentrapporteringsrutiner for FI ar upprattade.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-16', title: 'Cyber resilience testing', title_nl: 'Cyberresilienstestning', description: 'Financial institutions shall conduct regular cyber resilience testing including threat-led penetration testing (TLPT).', description_nl: 'Finansiella institut ska genomfora regelbunden cyberresilienstestning inklusive hotledd penetrationstestning (TLPT).', category: 'Incidenthantering', subcategory: 'Testning', level: 'Foreskrift', iso_mapping: '8.29', implementation_guidance: 'Genomfor TLPT baserat pa TIBER-SE ramverket. Testa med externa testare minst vart tredje ar.', verification_guidance: 'Kontrollera att cyberresilienstestning genomfors enligt krav.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },

  // -- DORA-implementering --
  { control_number: 'FI-17', title: 'ICT risk management framework (DORA)', title_nl: 'Ramverk for IKT-riskhantering (DORA)', description: 'Financial institutions shall establish an ICT risk management framework in accordance with DORA requirements.', description_nl: 'Finansiella institut ska uppractta ett ramverk for IKT-riskhantering i enlighet med DORA-kraven.', category: 'DORA', subcategory: 'Ramverk', level: 'Foreskrift', iso_mapping: '5.1', implementation_guidance: 'Implementera DORA:s fem pelare: IKT-riskhantering, incidentrapportering, testning, tredjepartsrisk och informationsdelning.', verification_guidance: 'Kontrollera att DORA-ramverket ar implementerat.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-18', title: 'ICT third-party risk register', title_nl: 'Register for IKT-tredjepartsrisker', description: 'A register of all ICT third-party service providers shall be maintained and reported to the supervisory authority.', description_nl: 'Ett register over alla IKT-tredjepartsleverantorer ska underhallas och rapporteras till tillsynsmyndigheten.', category: 'DORA', subcategory: 'Tredjepartsregister', level: 'Foreskrift', iso_mapping: '5.19', implementation_guidance: 'Uppractta register over IKT-leverantorer. Klassificera kritiska och viktiga leverantorer.', verification_guidance: 'Kontrollera att leverantorsregistret ar komplett och aktuellt.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-19', title: 'Major ICT incident reporting (DORA)', title_nl: 'Rapportering av allvarliga IKT-incidenter (DORA)', description: 'Major ICT-related incidents shall be reported to FI using DORA classification and timeline requirements.', description_nl: 'Allvarliga IKT-relaterade incidenter ska rapporteras till FI enligt DORA:s klassificerings- och tidskrav.', category: 'DORA', subcategory: 'Incidentrapportering', level: 'Foreskrift', iso_mapping: '5.24', implementation_guidance: 'Tilllampa DORA:s incidentklassificering. Rapportera initial anmalan inom 4 timmar, mellanrapport inom 72 timmar, slutrapport inom 1 manad.', verification_guidance: 'Kontrollera att DORA-incidentrapporteringsrutiner ar implementerade.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-20', title: 'Digital operational resilience testing (DORA)', title_nl: 'Testning av digital operativ resiliens (DORA)', description: 'Financial institutions shall conduct digital operational resilience testing programs including TLPT for systemically important entities.', description_nl: 'Finansiella institut ska genomfora testprogram for digital operativ resiliens inklusive TLPT for systemviktiga enheter.', category: 'DORA', subcategory: 'Resilienstestning', level: 'Foreskrift', iso_mapping: '8.29', implementation_guidance: 'Uppractta arligt testprogram. Genomfor TLPT vart tredje ar for systemviktiga institut. Dokumentera resultat och atgarder.', verification_guidance: 'Kontrollera att resilienstestprogram genomfors enligt DORA-krav.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },

  // -- Tillagg: Fordjupad finansiell sakerhhet --
  { control_number: 'FI-21', title: 'Payment service security (PSD2)', title_nl: 'Betalningssakerhet (PSD2)', description: 'Payment services shall implement strong customer authentication (SCA) and secure communication per PSD2 requirements.', description_nl: 'Betalningstjanster ska implementera stark kundautentisering (SCA) och saker kommunikation enligt PSD2-krav.', category: 'Driftsakerhet', subcategory: 'Betalningsakerhet', level: 'Foreskrift', iso_mapping: '8.5', implementation_guidance: 'Implementera SCA for alla betalningar over 30 EUR. Anvand dynamisk lankning. Skydda betalningsinformation.', verification_guidance: 'Kontrollera att SCA ar implementerat for betalningstjanster.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-22', title: 'AML/KYC system security', title_nl: 'Sakerhet for AML/KYC-system', description: 'Anti-money laundering and know-your-customer systems shall be protected with strict access controls and audit logging.', description_nl: 'System for penningtvattbekampning och kundkontroll ska skyddas med strikt atkomstkontroll och revisionsloggning.', category: 'Driftsakerhet', subcategory: 'AML/KYC', level: 'Foreskrift', iso_mapping: '8.15', implementation_guidance: 'Begransa atkomst till AML/KYC-system. Logga alla fragor och beslut. Implementera manipulationsskydd for loggarna.', verification_guidance: 'Kontrollera att AML/KYC-system har strikt atkomstkontroll och loggning.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-23', title: 'Critical function register', title_nl: 'Register over kritiska funktioner', description: 'A register of critical and important functions shall be maintained and updated to inform risk management.', description_nl: 'Ett register over kritiska och viktiga funktioner ska underhallas och uppdateras for att informera riskhantering.', category: 'Styrning', subcategory: 'Kritiska funktioner', level: 'Foreskrift', iso_mapping: '5.9', implementation_guidance: 'Identifiera och registrera alla kritiska funktioner. Koppla till IT-system och leverantorer. Uppdatera minst arligen.', verification_guidance: 'Kontrollera att registret over kritiska funktioner ar komplett och aktuellt.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-24', title: 'ICT concentration risk management', title_nl: 'Hantering av IKT-koncentrationsrisk', description: 'Concentration risk from dependence on single ICT providers shall be assessed and managed with diversification strategies.', description_nl: 'Koncentrationsrisk fran beroende av enskilda IKT-leverantorer ska bedommas och hanteras med diversifieringsstrategier.', category: 'DORA', subcategory: 'Koncentrationsrisk', level: 'Foreskrift', iso_mapping: '5.19', implementation_guidance: 'Bedome koncentrationsrisk for alla kritiska IKT-leverantorer. Uppractta exitstrategier. Overveag diversifiering.', verification_guidance: 'Kontrollera att koncentrationsriskbedomning ar genomford for IKT-leverantorer.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
  { control_number: 'FI-25', title: 'ICT information sharing arrangement', title_nl: 'Overenskommelse om IKT-informationsdelning', description: 'Financial institutions shall participate in information sharing arrangements to exchange cyber threat intelligence.', description_nl: 'Finansiella institut ska delta i informationsdelningsoverenskommelser for att utbyta cyberhotunderrattelser.', category: 'DORA', subcategory: 'Informationsdelning', level: 'Foreskrift', iso_mapping: '5.6', implementation_guidance: 'Delta i branschorgan for informationsdelning (t.ex. FS-ISAC eller nordiskt samarbete). Dela hotinformation med CERT-SE.', verification_guidance: 'Kontrollera att organisationen deltar i informationsdelning om cyberhot.', source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/' },
];

async function main(): Promise<void> {
  console.log('FI IT-verksamhet Ingestion Script');
  console.log('==================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} requirements.`);

  const output = {
    framework: {
      id: 'fi-it-verksamhet',
      name: 'Financial Sector IT Requirements (FFFS)',
      name_nl: 'Finansinspektionens foreskrifter om IT-verksamhet (FFFS)',
      issuing_body: 'Finansinspektionen (FI)',
      version: '2024',
      effective_date: '2014-12-01',
      scope: 'IT governance, security, and operational requirements for financial institutions under Swedish financial supervision, including DORA implementation',
      scope_sectors: ['finance'],
      structure_description: 'Organized by area: governance (FI-1 to FI-4, FI-23), systems and development (FI-5 to FI-7), operations (FI-8 to FI-11, FI-21, FI-22), outsourcing (FI-12 to FI-14), incident management (FI-15 to FI-16), and DORA (FI-17 to FI-20, FI-24, FI-25).',
      source_url: 'https://www.fi.se/sv/vara-register/sok-fffs/2014/20145/',
      license: 'Swedish government regulation (public)',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
