// scripts/ingest-msb-klassificering.ts
// MSB Vagledning for klassificering av information (Information Classification Guidance)
// Authority: Myndigheten for samhallsskydd och beredskap (MSB)

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'msb-klassificering.json');

const controls = [
  // -- Klassificeringsmodell (Classification model) --
  { control_number: 'KL-1', title: 'Establish classification model', title_nl: 'Uppractta klassificeringsmodell', description: 'The organization shall establish a classification model defining levels for confidentiality, integrity, and availability.', description_nl: 'Organisationen ska uppractta en klassificeringsmodell som definierar niver for konfidentialitet, riktighet och tillganglighet.', category: 'Klassificeringsmodell', subcategory: 'Modell', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Definiera en modell med minst 3-4 niver per sakerhetsdimension (t.ex. oppen, intern, konfidentiell, strikt konfidentiell).', verification_guidance: 'Kontrollera att klassificeringsmodellen ar dokumenterad och godkand av ledningen.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-2', title: 'Confidentiality classification levels', title_nl: 'Klassificeringsniver for konfidentialitet', description: 'Confidentiality levels shall be defined reflecting the harm from unauthorized disclosure.', description_nl: 'Konfidentialitetsniver ska definieras som avspeglar skadan vid obehorigat rojanade.', category: 'Klassificeringsmodell', subcategory: 'Konfidentialitet', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Definiera niver: t.ex. (1) Oppen, (2) Intern, (3) Konfidentiell, (4) Strikt konfidentiell. Beskriv konsekvenser per niva.', verification_guidance: 'Kontrollera att konfidentialitetsniverna ar definierade med tydliga konsekvensbeskrivningar.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-3', title: 'Integrity classification levels', title_nl: 'Klassificeringsniver for riktighet', description: 'Integrity levels shall be defined reflecting the harm from unauthorized modification of information.', description_nl: 'Riktighetsniver ska definieras som avspeglar skadan vid obehorigad andring av information.', category: 'Klassificeringsmodell', subcategory: 'Riktighet', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Definiera niver baserat pa konsekvensen av felaktig information, fran obetydlig till allvarlig samhallspaverkan.', verification_guidance: 'Kontrollera att riktighetsniverna ar definierade med konsekvensbeskrivningar.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-4', title: 'Availability classification levels', title_nl: 'Klassificeringsniver for tillganglighet', description: 'Availability levels shall be defined reflecting maximum acceptable downtime for information and services.', description_nl: 'Tillganglighetsniver ska definieras som avspeglar maximal acceptabel nedtid for information och tjanster.', category: 'Klassificeringsmodell', subcategory: 'Tillganglighet', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Definiera niver baserat pa tolerabel nedtid: t.ex. (1) veckor, (2) dagar, (3) timmar, (4) minuter.', verification_guidance: 'Kontrollera att tillganglighetsniverna ar definierade med tidsangivelser.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },

  // -- Genomfora klassificering (Perform classification) --
  { control_number: 'KL-5', title: 'Information asset inventory for classification', title_nl: 'Informationstillgangsinventering for klassificering', description: 'An inventory of information assets shall be created as the basis for classification.', description_nl: 'En inventering av informationstillgangar ska skapas som underlag for klassificering.', category: 'Genomforande', subcategory: 'Inventering', level: 'Vagledning', iso_mapping: '5.9', implementation_guidance: 'Identifiera alla informationstillgangar: system, register, databaser, dokument, kommunikationsfloden.', verification_guidance: 'Kontrollera att tillgangsinventering ar genomford och komplett.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-6', title: 'Classification execution per asset', title_nl: 'Klassificering per tillgang', description: 'Each information asset shall be classified against all three security dimensions using the defined model.', description_nl: 'Varje informationstillgang ska klassificeras mot alla tre sakerhetsdimensioner med den definierade modellen.', category: 'Genomforande', subcategory: 'Klassificering', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Klassificera varje tillgang avseende konfidentialitet, riktighet och tillganglighet. Dokumentera resultaten.', verification_guidance: 'Kontrollera att klassificeringsresultat finns for alla inventerade tillgangar.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-7', title: 'Classification owner responsibility', title_nl: 'Informationsagarens ansvar for klassificering', description: 'The information owner shall be responsible for the classification of their information assets.', description_nl: 'Informationsagaren ska ansvara for klassificering av sina informationstillgangar.', category: 'Genomforande', subcategory: 'Ansvar', level: 'Vagledning', iso_mapping: '5.9', implementation_guidance: 'Utse informationsagare for alla tillgangar. Sakerstall att de har kompetens att genomfora klassificering.', verification_guidance: 'Kontrollera att informationsagare ar utsedda och att de har genomfort klassificering.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-8', title: 'Consequence-based classification', title_nl: 'Konsekvenbaserad klassificering', description: 'Classification shall be based on assessment of consequences if confidentiality, integrity, or availability is compromised.', description_nl: 'Klassificering ska baseras pa bedomning av konsekvenser om konfidentialitet, riktighet eller tillganglighet aventyras.', category: 'Genomforande', subcategory: 'Konsekvensbedoming', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Bedom konsekvenser av forlust av respektive sakerhetsdimension. Anvand organisationens konsekvensskala.', verification_guidance: 'Kontrollera att klassificering baseras pa dokumenterade konsekvensbedominingar.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },

  // -- Hanteringsregler (Handling rules) --
  { control_number: 'KL-9', title: 'Handling rules per classification level', title_nl: 'Hanteringsregler per klassificeringsniva', description: 'Handling rules shall be defined for each classification level covering storage, transmission, access, and disposal.', description_nl: 'Hanteringsregler ska definieras for varje klassificeringsniva avseende lagring, overforing, atkomst och gallring.', category: 'Hanteringsregler', subcategory: 'Regler', level: 'Vagledning', iso_mapping: '5.13', implementation_guidance: 'Uppractta hanteringsregler som specificerar tillaten lagring, transport, delning och gallring per niva.', verification_guidance: 'Kontrollera att hanteringsregler finns for samtliga klassificeringsniver.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-10', title: 'Classification marking', title_nl: 'Klassificeringsmarkning', description: 'Information assets shall be marked with their classification level in a visible and consistent manner.', description_nl: 'Informationstillgangar ska markas med sin klassificeringsniva pa ett synligt och konsekvent satt.', category: 'Hanteringsregler', subcategory: 'Markning', level: 'Vagledning', iso_mapping: '5.13', implementation_guidance: 'Markera dokument och system med klassificeringsniva. Anvand enhetlig markning (sidhuvud, metadata, etiketter).', verification_guidance: 'Kontrollera att markering tilllampas pa klassificerade tillgangar.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-11', title: 'Access control aligned with classification', title_nl: 'Atkomstkontroll i linje med klassificering', description: 'Access controls shall be implemented in accordance with the classification level of information assets.', description_nl: 'Atkomstkontroller ska implementeras i enlighet med informationstillgangarnas klassificeringsniva.', category: 'Hanteringsregler', subcategory: 'Atkomstkontroll', level: 'Vagledning', iso_mapping: '5.15', implementation_guidance: 'Implementera atkomstkontroller som matchar klassificeringsnivan. Hogre niva kraver starkare kontroller.', verification_guidance: 'Kontrollera att atkomstkontrollerna ar i linje med klassificeringsniverna.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-12', title: 'Transmission protection requirements', title_nl: 'Krav pa overforigsskydd', description: 'Protection requirements for information transmission shall be defined per classification level.', description_nl: 'Skyddskrav for informationsoverforing ska definieras per klassificeringsniva.', category: 'Hanteringsregler', subcategory: 'Overforing', level: 'Vagledning', iso_mapping: '5.14', implementation_guidance: 'Definiera krypteringskrav for overforing per niva. Hogre niver kraver starkare kryptering.', verification_guidance: 'Kontrollera att overforigsskrav ar definierade och tilllampas.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },

  // -- Forvaltning av klassificering (Classification governance) --
  { control_number: 'KL-13', title: 'Classification training', title_nl: 'Utbildning i klassificering', description: 'Personnel shall receive training in the classification model and handling rules.', description_nl: 'Personal ska utbildas i klassificeringsmodellen och hanteringsreglerna.', category: 'Forvaltning', subcategory: 'Utbildning', level: 'Vagledning', iso_mapping: '6.3', implementation_guidance: 'Genomfor utbildning i klassificering for all personal. Anpassa efter roller och ansvarsniver.', verification_guidance: 'Kontrollera att utbildning genomforts och att personal kannar till klassificeringsmodellen.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-14', title: 'Periodic reclassification review', title_nl: 'Periodisk omklassificering', description: 'Classifications shall be reviewed periodically or when the context or value of information changes.', description_nl: 'Klassificeringar ska omprovas periodiskt eller nar sammanhanget eller vardet pa informationen andras.', category: 'Forvaltning', subcategory: 'Omklassificering', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Genomfor omklassificering minst arligen eller vid vasentliga forandringar.', verification_guidance: 'Kontrollera att omklassificering genomfors enligt plan.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-15', title: 'Classification audit trail', title_nl: 'Sparbarhet for klassificering', description: 'Classification decisions and changes shall be logged for traceability and audit purposes.', description_nl: 'Klassificeringsbeslut och forandringar ska loggas for sparbarhet och revisionsandamal.', category: 'Forvaltning', subcategory: 'Sparbarhet', level: 'Vagledning', iso_mapping: '5.37', implementation_guidance: 'Dokumentera klassificeringsbeslut, forandringar och ansvariga. Arkivera for sparbarhet.', verification_guidance: 'Kontrollera att sparbarhet finns for klassificeringsbeslut.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-16', title: 'Disposal rules per classification level', title_nl: 'Gallringsregler per klassificeringsniva', description: 'Disposal and retention rules shall be defined per classification level in accordance with archival requirements.', description_nl: 'Gallrings- och bevaranderegler ska definieras per klassificeringsniva i enlighet med arkivkrav.', category: 'Forvaltning', subcategory: 'Gallring', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Definiera gallringsregler per klassificeringsniva. Beakta arkivlagen och dataskyddsforordningen.', verification_guidance: 'Kontrollera att gallringsregler ar definierade och tilllampas.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },

  // -- Tillagg: Klassificering i praktiken --
  { control_number: 'KL-17', title: 'Classification of external information', title_nl: 'Klassificering av extern information', description: 'Information received from external parties shall be classified upon receipt according to the organization classification model.', description_nl: 'Information som mottas fran externa parter ska klassificeras vid mottagande enligt organisationens klassificeringsmodell.', category: 'Genomforande', subcategory: 'Extern information', level: 'Vagledning', iso_mapping: '5.14', implementation_guidance: 'Uppractta rutiner for klassificering av inkommande information. Beakta avsandarens klassificering.', verification_guidance: 'Kontrollera att extern information klassificeras vid mottagande.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-18', title: 'Classification inheritance in derived information', title_nl: 'Klassificeringsarv i haarledd information', description: 'Information derived from classified sources shall inherit at least the same classification level as the source.', description_nl: 'Information haarledd fran klassificerade kallor ska arva minst samma klassificeringsniva som kallan.', category: 'Genomforande', subcategory: 'Arv', level: 'Vagledning', iso_mapping: '5.12', implementation_guidance: 'Tilllampa arvsprincipen for harledda dokument. Aggregerad information kan kravan hogre klassificering.', verification_guidance: 'Kontrollera att klassificeringsarv tilllampas.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-19', title: 'Cloud service classification requirements', title_nl: 'Klassificeringskrav for molntjanster', description: 'Information stored in cloud services shall be classified, and the cloud service capability shall match the classification level.', description_nl: 'Information som lagras i molntjanster ska klassificeras och molntjanstens formaga ska matcha klassificeringsnivan.', category: 'Hanteringsregler', subcategory: 'Molntjanster', level: 'Vagledning', iso_mapping: '5.23', implementation_guidance: 'Bedome molntjanstens sakerhetsniva mot informationens klassificering. Hogklassificerad information kraver kvalificerade tjanster.', verification_guidance: 'Kontrollera att molntjanster matchar informationens klassificeringsniva.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
  { control_number: 'KL-20', title: 'Classification tool and metadata integration', title_nl: 'Verktyg och metadataintegration for klassificering', description: 'Classification metadata shall be embedded in documents and systems to enable automated enforcement of handling rules.', description_nl: 'Klassificeringsmetadata ska baddas in i dokument och system for att mojliggora automatiserad tilllampning av hanteringsregler.', category: 'Forvaltning', subcategory: 'Verktyg', level: 'Vagledning', iso_mapping: '5.13', implementation_guidance: 'Implementera klassificeringsverktyg som baddar in metadata. Integrera med DLP och atkomstkontrollsystem.', verification_guidance: 'Kontrollera att klassificeringsmetadata anvands for automatiserad hantering.', source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/' },
];

async function main(): Promise<void> {
  console.log('MSB Klassificering Ingestion Script');
  console.log('====================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} controls validated.`);

  const output = {
    framework: {
      id: 'msb-klassificering',
      name: 'Information Classification Guidance',
      name_nl: 'Vagledning for klassificering av information',
      issuing_body: 'Myndigheten for samhallsskydd och beredskap (MSB)',
      version: '2024',
      effective_date: '2024-01-01',
      scope: 'Guidance for classifying information assets by confidentiality, integrity, and availability, with handling rules per classification level',
      scope_sectors: ['government', 'digital_infrastructure'],
      structure_description: 'Organized by phase: classification model (KL-1 to KL-4), execution (KL-5 to KL-8, KL-17 to KL-18), handling rules (KL-9 to KL-12, KL-19), and governance (KL-13 to KL-16, KL-20).',
      source_url: 'https://www.informationssakerhet.se/metodstod/klassificering/',
      license: 'Public sector publication',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
