// scripts/ingest-msb-incidenthantering.ts
// MSB Vagledning for incidenthantering (Incident Management Guidance)
// Authority: Myndigheten for samhallsskydd och beredskap (MSB)

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'msb-incidenthantering.json');

const controls = [
  // -- Forberedelse (Preparation) --
  { control_number: 'IH-1', title: 'Incident response policy', title_nl: 'Policy for incidenthantering', description: 'An incident response policy shall be established defining scope, objectives, roles, and escalation paths.', description_nl: 'En policy for incidenthantering ska uppratttas som definierar omfattning, mal, roller och eskaleringsvaagar.', category: 'Forberedelse', subcategory: 'Policy', level: 'Vagledning', iso_mapping: '5.24', implementation_guidance: 'Uppractta en incidenthanteringspolicy godkand av ledningen. Definiera vad som utgor en incident och eskaleringsnivaer.', verification_guidance: 'Kontrollera att policyn finns, ar godkand och kommunicerad.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-2', title: 'Incident response team', title_nl: 'Incidenthanteringsteam', description: 'An incident response team with defined roles, competencies, and contact information shall be established.', description_nl: 'Ett incidenthanteringsteam med definierade roller, kompetenser och kontaktuppgifter ska inrattas.', category: 'Forberedelse', subcategory: 'Organisation', level: 'Vagledning', iso_mapping: '5.24', implementation_guidance: 'Utse ett incidenthanteringsteam. Definiera roller (teamledare, teknisk analytiker, kommunikationsansvarig). Uppractta kontaktlista.', verification_guidance: 'Kontrollera att teamet ar inrattat med tydliga roller och kontaktuppgifter.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-3', title: 'Incident classification scheme', title_nl: 'Klassificeringsschema for incidenter', description: 'A classification scheme for incidents shall be defined covering severity, type, and affected assets.', description_nl: 'Ett klassificeringsschema for incidenter ska definieras som omfattar allvarlighetsgrad, typ och paverkade tillgangar.', category: 'Forberedelse', subcategory: 'Klassificering', level: 'Vagledning', iso_mapping: '5.25', implementation_guidance: 'Definiera allvarlighetsniver (kritisk, hog, medel, lag). Definiera incidenttyper (dataintrung, ransomware, dataforlist, driftstorning).', verification_guidance: 'Kontrollera att klassificeringsschemat ar dokumenterat och kant av incidentteamet.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-4', title: 'Incident detection capabilities', title_nl: 'Formaga for incidentdetektering', description: 'Technical and organizational capabilities for detecting security incidents shall be established and maintained.', description_nl: 'Tekniska och organisatoriska formagor for att detektera sakerhetsincidenter ska uppratttas och underhallas.', category: 'Forberedelse', subcategory: 'Detektering', level: 'Vagledning', iso_mapping: '8.16', implementation_guidance: 'Implementera SIEM, IDS/IPS och logganalys. Uppractta rutiner for att personal rapporterar misstankta incidenter.', verification_guidance: 'Kontrollera att detekteringsformagor ar implementerade och testade.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-5', title: 'Incident response procedures', title_nl: 'Rutiner for incidenthantering', description: 'Step-by-step incident response procedures shall be documented for each incident type.', description_nl: 'Steg-for-steg-rutiner for incidenthantering ska dokumenteras for varje incidenttyp.', category: 'Forberedelse', subcategory: 'Rutiner', level: 'Vagledning', iso_mapping: '5.24', implementation_guidance: 'Uppractta detaljerade rutiner for vanliga incidenttyper. Inkludera beslutstrad och checklista.', verification_guidance: 'Kontrollera att rutiner finns for alla identifierade incidenttyper.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },

  // -- Hantering (Response) --
  { control_number: 'IH-6', title: 'Incident containment', title_nl: 'Incidentbegransning', description: 'Procedures for containing incidents to prevent further damage shall be defined and executable.', description_nl: 'Rutiner for att begrantsa incidenter for att forhindra ytterligare skada ska definieras och vara genomforbara.', category: 'Hantering', subcategory: 'Begransning', level: 'Vagledning', iso_mapping: '5.26', implementation_guidance: 'Definiera begrantsningsatgarder per incidenttyp (isolera system, stanga av natverksanslutning, byta losenord).', verification_guidance: 'Kontrollera att begrantsningsatgarder ar definierade och kan genomforas snabbt.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-7', title: 'Evidence collection and preservation', title_nl: 'Bevissakring och bevaring', description: 'Procedures for collecting and preserving digital evidence shall be established for potential legal proceedings.', description_nl: 'Rutiner for att sakra och bevara digitala bevis ska uppratttas for eventuella rattsliga forfaranden.', category: 'Hantering', subcategory: 'Bevissakring', level: 'Vagledning', iso_mapping: '5.28', implementation_guidance: 'Uppractta rutiner for forensisk bevissakring. Dokumentera beviskedjan (chain of custody). Anvand skrivskyddade kopior.', verification_guidance: 'Kontrollera att bevissakringsrutiner finns och att personal ar utbildad.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-8', title: 'Incident eradication', title_nl: 'Incidentavlagsning', description: 'After containment, the root cause shall be identified and eradicated from all affected systems.', description_nl: 'Efter begransning ska grundorsaken identifieras och avlagsnas fran alla paverkade system.', category: 'Hantering', subcategory: 'Avlagsning', level: 'Vagledning', iso_mapping: '5.26', implementation_guidance: 'Identifiera grundorsak. Avlagsna skadlig programvara, stang sarbarheter, aterrackll obehorigad tillgang.', verification_guidance: 'Kontrollera att grundorsaken ar identifierad och att alla instanser av hotet ar avlagsnade.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-9', title: 'System recovery after incident', title_nl: 'Systematerstaallning efter incident', description: 'Procedures for restoring affected systems to normal operation shall be defined and tested.', description_nl: 'Rutiner for att aterstalla paverkade system till normal drift ska definieras och testas.', category: 'Hantering', subcategory: 'Aterstallning', level: 'Vagledning', iso_mapping: '5.26', implementation_guidance: 'Uppractta aterstaallningsrutiner. Verifiera systemintegritet fore atertagnande i drift. Testa funktonalitet.', verification_guidance: 'Kontrollera att aterstaallning kan genomforas och att systemen fungerar korrekt efter aterstaallning.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },

  // -- Kommunikation (Communication) --
  { control_number: 'IH-10', title: 'Internal incident communication', title_nl: 'Intern incidentkommunikation', description: 'Communication procedures for informing management and relevant personnel during incidents shall be established.', description_nl: 'Kommunikationsrutiner for att informera ledning och relevant personal under incidenter ska uppratttas.', category: 'Kommunikation', subcategory: 'Intern', level: 'Vagledning', iso_mapping: '5.26', implementation_guidance: 'Definiera kommunikationskanaler och mottagare per allvarlighetsniva. Uppractta mallar for incidentrapporter.', verification_guidance: 'Kontrollera att kommunikationsrutiner ar definierade och kanda.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-11', title: 'External incident communication', title_nl: 'Extern incidentkommunikation', description: 'Communication procedures for notifying external parties (CERT-SE, regulators, affected parties) shall be defined.', description_nl: 'Kommunikationsrutiner for att underratta externa parter (CERT-SE, tillsynsmyndigheter, drabbade parter) ska definieras.', category: 'Kommunikation', subcategory: 'Extern', level: 'Vagledning', iso_mapping: '5.26', implementation_guidance: 'Identifiera rapporteringsplikt (CERT-SE, IMY, PTS). Uppractta kontaktlistor och mallar for extern kommunikation.', verification_guidance: 'Kontrollera att externa kommunikationsrutiner ar definierade och inkluderar alla rapporteringspliktiga mottagare.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-12', title: 'Regulatory notification obligations', title_nl: 'Regulatoriska anmalningsskyldigheter', description: 'Regulatory notification requirements shall be identified and mapped to incident types and timelines.', description_nl: 'Regulatoriska anmalningsskyldigheter ska identifieras och kopplas till incidenttyper och tidsfrister.', category: 'Kommunikation', subcategory: 'Anmalan', level: 'Vagledning', iso_mapping: '5.26', implementation_guidance: 'Kartlagg anmalningsskyldigheter: MSBFS 2020:7 (24h till CERT-SE), GDPR art. 33 (72h till IMY), NIS2 (24h/72h). Integrera i incidentrutiner.', verification_guidance: 'Kontrollera att alla anmalningsskyldigheter ar identifierade med tidsfrister.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },

  // -- Uppfoljning (Follow-up) --
  { control_number: 'IH-13', title: 'Post-incident review', title_nl: 'Efterhandsgenomgang av incident', description: 'A post-incident review shall be conducted after each significant incident to identify root causes and improvements.', description_nl: 'En efterhandsgenomgang ska genomforas efter varje betydande incident for att identifiera grundorsaker och forbattringar.', category: 'Uppfoljning', subcategory: 'Genomgang', level: 'Vagledning', iso_mapping: '5.27', implementation_guidance: 'Genomfor post-incident-genomgang med alla inblandade. Dokumentera tidslinje, grundorsak, atgarder och forbattringsforslag.', verification_guidance: 'Kontrollera att efterhandsgenomgangar genomfors och dokumenteras.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-14', title: 'Lessons learned implementation', title_nl: 'Implementering av erfarenheter', description: 'Lessons learned from incidents shall be documented and used to improve security controls and procedures.', description_nl: 'Erfarenheter fran incidenter ska dokumenteras och anvandas for att forbattra sakerhetsatgarder och rutiner.', category: 'Uppfoljning', subcategory: 'Erfarenheter', level: 'Vagledning', iso_mapping: '5.27', implementation_guidance: 'Sammanstall erfarenheter. Uppdatera rutiner, sakerhetsatgarder och utbildningsmaterial baserat pa lardomar.', verification_guidance: 'Kontrollera att erfarenheter leder till konkreta forbattringsatgarder.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-15', title: 'Incident statistics and trend analysis', title_nl: 'Incidentstatistik och trendanalys', description: 'Incident statistics shall be compiled and analyzed regularly to identify trends and recurring patterns.', description_nl: 'Incidentstatistik ska sammanstallas och analyseras regelbundet for att identifiera trender och aterkommande monster.', category: 'Uppfoljning', subcategory: 'Statistik', level: 'Vagledning', iso_mapping: '5.27', implementation_guidance: 'Sammanstall kvartalsvis incidentstatistik. Analysera trender for att identifiera systemiska svagheter.', verification_guidance: 'Kontrollera att incidentstatistik framstalls och analyseras regelbundet.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-16', title: 'Incident response capability testing', title_nl: 'Testning av incidenthanteringsformaga', description: 'Incident response capabilities shall be tested through regular exercises including tabletop and technical simulations.', description_nl: 'Incidenthanteringsformagan ska testas genom regelbundna ovningar inklusive bordsovningar och tekniska simuleringar.', category: 'Uppfoljning', subcategory: 'Ovning', level: 'Vagledning', iso_mapping: '5.24', implementation_guidance: 'Genomfor minst en bordsovning arligen och en teknisk simulering. Dokumentera resultat och forbattringsomraden.', verification_guidance: 'Kontrollera att ovningar genomfors och att resultat anvands for forbattring.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-17', title: 'Incident documentation and register', title_nl: 'Incidentdokumentation och register', description: 'All incidents shall be documented in an incident register with timeline, classification, actions, and outcome.', description_nl: 'Alla incidenter ska dokumenteras i ett incidentregister med tidslinje, klassificering, atgarder och utfall.', category: 'Uppfoljning', subcategory: 'Register', level: 'Vagledning', iso_mapping: '5.28', implementation_guidance: 'Uppractta ett incidentregister. Dokumentera alla incidenter oavsett allvarlighetsgrad.', verification_guidance: 'Kontrollera att incidentregistret ar komplett och att alla incidenter ar dokumenterade.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-18', title: 'Coordination with CERT-SE', title_nl: 'Samordning med CERT-SE', description: 'Organizations shall establish contact with CERT-SE and be prepared to share technical indicators during incidents.', description_nl: 'Organisationer ska uppractta kontakt med CERT-SE och vara beredda att dela tekniska indikatorer under incidenter.', category: 'Uppfoljning', subcategory: 'Samordning', level: 'Vagledning', iso_mapping: '5.5', implementation_guidance: 'Registrera organisationen hos CERT-SE. Uppractta kontaktvaagar for incidentutbyte. Forbered for att dela IoC (Indicators of Compromise).', verification_guidance: 'Kontrollera att kontakt med CERT-SE ar uppratttad och att tekniskt utbyte fungerar.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },

  // -- Tillagg: Fordjupad incidenthantering --
  { control_number: 'IH-19', title: 'Incident playbook library', title_nl: 'Bibliotek med incidentspelbocker', description: 'A library of incident response playbooks shall be maintained for common incident types with step-by-step procedures.', description_nl: 'Ett bibliotek med incidenthanteringsspelbocker ska underhallas for vanliga incidenttyper med steg-for-steg-rutiner.', category: 'Forberedelse', subcategory: 'Spelbocker', level: 'Vagledning', iso_mapping: '5.24', implementation_guidance: 'Uppractta spelbocker for ransomware, dataintrung, insiderhot, DDoS och dataforrlust. Uppdatera efter varje incident.', verification_guidance: 'Kontrollera att spelbocker finns for alla vanliga incidenttyper.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-20', title: 'Threat intelligence integration', title_nl: 'Integration av hotunderrattelser', description: 'Threat intelligence feeds shall be integrated into incident detection and response processes.', description_nl: 'Hotunderrattelser ska integreras i incidentdetekterings- och hanteringsprocesser.', category: 'Forberedelse', subcategory: 'Hotunderrattelser', level: 'Vagledning', iso_mapping: '5.7', implementation_guidance: 'Prenumerera pa CERT-SE:s hotinformation. Integrera IoC-foder i SIEM och brandvaggar.', verification_guidance: 'Kontrollera att hotunderrattelser integreras i detekteringsformagorna.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-21', title: 'Out-of-band communication channels', title_nl: 'Kommunikationskanaler utanfor bandet', description: 'Alternative communication channels shall be pre-established for use when primary systems are compromised.', description_nl: 'Alternativa kommunikationskanaler ska uppratttas i forvag for anvandning nar primara system ar komprometterade.', category: 'Kommunikation', subcategory: 'Reservkanal', level: 'Vagledning', iso_mapping: '5.24', implementation_guidance: 'Uppractta kommunikationskanaler oberoende av ordinarie IT-infrastruktur (t.ex. krypterade mobilappar, satellitkommunikation).', verification_guidance: 'Kontrollera att alternativa kommunikationskanaler ar testade och kanda av incidentteamet.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-22', title: 'Incident severity escalation criteria', title_nl: 'Eskaleringskreterier for incidentallvarlighet', description: 'Clear escalation criteria shall define when incidents require management notification, crisis team activation, or external assistance.', description_nl: 'Tydliga eskaleringskriterier ska definiera nar incidenter kraver ledningsnotifiering, kristeamaktivering eller extern hjalp.', category: 'Hantering', subcategory: 'Eskalering', level: 'Vagledning', iso_mapping: '5.25', implementation_guidance: 'Definiera eskaleringskriterier per allvarlighetsniva. Inkludera tidsramar och beslutsfattare for varje niva.', verification_guidance: 'Kontrollera att eskaleringskriterier ar definierade och kanda.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-23', title: 'Forensic readiness', title_nl: 'Forensisk beredskap', description: 'Systems shall be configured to support forensic investigation with adequate logging, time synchronization, and evidence preservation.', description_nl: 'System ska konfigureras for att stodja forensisk utredning med tillracklig loggning, tidssynkronisering och bevisbevarande.', category: 'Hantering', subcategory: 'Forensik', level: 'Vagledning', iso_mapping: '5.28', implementation_guidance: 'Sakerstall NTP-synkronisering pa alla system. Konfigurera loggning for forensisk analys. Uppractta forensiska verktyg.', verification_guidance: 'Kontrollera att forensisk beredskap finns for kritiska system.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-24', title: 'Incident cost tracking', title_nl: 'Incidentkostnadsuppfoljning', description: 'Costs associated with incident response shall be tracked to inform risk management and budget decisions.', description_nl: 'Kostnader forknippade med incidenthantering ska foljas upp for att informera riskhantering och budgetbeslut.', category: 'Uppfoljning', subcategory: 'Kostnad', level: 'Vagledning', iso_mapping: '5.27', implementation_guidance: 'Spar kostnader for incidenthantering (personal, verktyg, extern hjalp, driftstorning). Rapportera till ledningen.', verification_guidance: 'Kontrollera att incidentkostnader dokumenteras och rapporteras.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
  { control_number: 'IH-25', title: 'Cross-organizational incident exercises', title_nl: 'Tvarorganisatoriska incidentovningar', description: 'Joint incident response exercises shall be conducted with peer organizations and CERT-SE to test coordination.', description_nl: 'Gemensamma incidenthanteringsovningar ska genomforas med samarbetsorganisationer och CERT-SE for att testa samordning.', category: 'Uppfoljning', subcategory: 'Samovning', level: 'Vagledning', iso_mapping: '5.24', implementation_guidance: 'Delta i CERT-SE:s ovningar. Genomfor gemensamma ovningar med samarbetsparter minst vartannat ar.', verification_guidance: 'Kontrollera att tvarorganisatoriska ovningar genomfors.', source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/' },
];

async function main(): Promise<void> {
  console.log('MSB Incidenthantering Ingestion Script');
  console.log('=======================================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} controls validated.`);

  const output = {
    framework: {
      id: 'msb-incidenthantering',
      name: 'Incident Management Guidance',
      name_nl: 'Vagledning for incidenthantering',
      issuing_body: 'Myndigheten for samhallsskydd och beredskap (MSB)',
      version: '2024',
      effective_date: '2024-01-01',
      scope: 'Guidance for establishing and operating incident management capabilities for information security incidents',
      scope_sectors: ['government', 'digital_infrastructure'],
      structure_description: 'Organized by phase: preparation (IH-1 to IH-5, IH-19 to IH-20), response (IH-6 to IH-9, IH-22 to IH-23), communication (IH-10 to IH-12, IH-21), and follow-up (IH-13 to IH-18, IH-24 to IH-25).',
      source_url: 'https://www.informationssakerhet.se/metodstod/incidenthantering/',
      license: 'Public sector publication',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
