// scripts/ingest-msbfs.ts
// MSBFS 2020:6 and MSBFS 2020:7 — MSB Regulations
// Authority: Myndigheten för samhällsskydd och beredskap (MSB)

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'msbfs-2020.json');

const controls = [
  // ── MSBFS 2020:6 — Systematiskt informationssäkerhetsarbete ─────────────
  { control_number: '2020:6-1', title: 'Obligation for systematic information security work', title_nl: 'Krav på systematiskt informationssäkerhetsarbete', description: 'Government agencies covered by the regulation shall conduct systematic and risk-based information security work.', description_nl: 'Myndigheter som omfattas av föreskriften ska bedriva systematiskt och riskbaserat informationssäkerhetsarbete.', category: 'MSBFS 2020:6', subcategory: 'Allmänna krav', level: 'Bindande', iso_mapping: '5.1', implementation_guidance: 'Upprätta ett ledningssystem för informationssäkerhet baserat på ISO 27001. Integrera i verksamhetsstyrningen.', verification_guidance: 'Kontrollera att ledningssystem finns och att det omfattar alla krav i föreskriften.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-2', title: 'Risk analysis requirement', title_nl: 'Krav på riskanalys', description: 'The agency shall regularly conduct risk analyses of its information assets.', description_nl: 'Myndigheten ska regelbundet genomföra riskanalyser av sina informationstillgångar.', category: 'MSBFS 2020:6', subcategory: 'Riskhantering', level: 'Bindande', iso_mapping: '5.1', implementation_guidance: 'Genomför riskanalyser för alla informationstillgångar. Dokumentera resultat och riskbehandlingsplaner.', verification_guidance: 'Granska dokumenterade riskanalyser och kontrollera att de är aktuella.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-3', title: 'Information security policy requirement', title_nl: 'Krav på informationssäkerhetspolicy', description: 'The agency shall establish an information security policy approved by senior management.', description_nl: 'Myndigheten ska upprätta en informationssäkerhetspolicy som godkänts av ledningen.', category: 'MSBFS 2020:6', subcategory: 'Styrning', level: 'Bindande', iso_mapping: '5.1', implementation_guidance: 'Upprätta en policy som anger organisationens inriktning. Policyn ska godkännas av myndighetschefen.', verification_guidance: 'Verifiera att policyn finns, är daterad och undertecknad av ledningen.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-4', title: 'Assignment of information security roles', title_nl: 'Tilldelning av roller för informationssäkerhet', description: 'The agency shall assign roles and responsibilities for information security, including a designated CISO.', description_nl: 'Myndigheten ska tilldela roller och ansvar för informationssäkerhet, inklusive en utsedd informationssäkerhetsansvarig.', category: 'MSBFS 2020:6', subcategory: 'Roller', level: 'Bindande', iso_mapping: '5.2', implementation_guidance: 'Utse en CISO eller motsvarande funktion. Dokumentera ansvar i befattningsbeskrivningar.', verification_guidance: 'Kontrollera att roller är tilldelade och dokumenterade.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-5', title: 'Information classification obligation', title_nl: 'Krav på informationsklassificering', description: 'The agency shall classify its information assets regarding confidentiality, integrity, and availability.', description_nl: 'Myndigheten ska klassificera sina informationstillgångar avseende konfidentialitet, riktighet och tillgänglighet.', category: 'MSBFS 2020:6', subcategory: 'Klassificering', level: 'Bindande', iso_mapping: '5.12', implementation_guidance: 'Tillämpa MSB:s klassificeringsmodell. Klassificera alla informationstillgångar.', verification_guidance: 'Kontrollera att klassificering genomförts för alla väsentliga tillgångar.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-6', title: 'Security measures implementation', title_nl: 'Implementering av säkerhetsåtgärder', description: 'The agency shall implement security measures proportionate to the results of risk analyses.', description_nl: 'Myndigheten ska implementera säkerhetsåtgärder i proportion till resultaten av riskanalyser.', category: 'MSBFS 2020:6', subcategory: 'Åtgärder', level: 'Bindande', iso_mapping: '5.1', implementation_guidance: 'Välj och implementera åtgärder baserat på riskanalysens resultat. Dokumentera i en riskbehandlingsplan.', verification_guidance: 'Granska att åtgärder genomförts i enlighet med riskbehandlingsplanen.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-7', title: 'Training and awareness obligation', title_nl: 'Krav på utbildning och medvetenhet', description: 'The agency shall ensure that personnel have adequate knowledge of information security relevant to their duties.', description_nl: 'Myndigheten ska säkerställa att personalen har tillräcklig kunskap om informationssäkerhet i relation till sina arbetsuppgifter.', category: 'MSBFS 2020:6', subcategory: 'Kompetens', level: 'Bindande', iso_mapping: '6.3', implementation_guidance: 'Genomför regelbundna utbildningar anpassade till personalens roller.', verification_guidance: 'Kontrollera att utbildningar genomförs och att deltagarstatistik förs.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-8', title: 'Follow-up and evaluation', title_nl: 'Uppföljning och utvärdering', description: 'The agency shall regularly follow up and evaluate its information security work.', description_nl: 'Myndigheten ska regelbundet följa upp och utvärdera sitt informationssäkerhetsarbete.', category: 'MSBFS 2020:6', subcategory: 'Uppföljning', level: 'Bindande', iso_mapping: '5.36', implementation_guidance: 'Genomför regelbundna utvärderingar och revisioner av informationssäkerhetsarbetet.', verification_guidance: 'Granska utvärderingsrapporter och kontrollera att de leder till förbättringsåtgärder.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-9', title: 'Reporting to MSB', title_nl: 'Rapportering till MSB', description: 'The agency shall report on its information security work to MSB when requested.', description_nl: 'Myndigheten ska rapportera om sitt informationssäkerhetsarbete till MSB vid begäran.', category: 'MSBFS 2020:6', subcategory: 'Rapportering', level: 'Bindande', iso_mapping: '5.5', implementation_guidance: 'Upprätta rutiner för rapportering till MSB. Säkerställ att efterfrågad information kan sammanställas.', verification_guidance: 'Kontrollera att rapporteringsrutiner finns och att tidigare rapporter har skickats.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-10', title: 'Continual improvement requirement', title_nl: 'Krav på ständig förbättring', description: 'The agency shall continually improve its information security management system.', description_nl: 'Myndigheten ska ständigt förbättra sitt ledningssystem för informationssäkerhet.', category: 'MSBFS 2020:6', subcategory: 'Förbättring', level: 'Bindande', iso_mapping: '5.36', implementation_guidance: 'Använd PDCA-cykeln (Plan-Do-Check-Act) för ständig förbättring av informationssäkerhetsarbetet.', verification_guidance: 'Kontrollera att förbättringsåtgärder dokumenteras och genomförs.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },

  // ── MSBFS 2020:7 — Rapportering av IT-incidenter ─────────────────────────
  { control_number: '2020:7-1', title: 'IT incident reporting obligation', title_nl: 'Rapporteringsplikt för IT-incidenter', description: 'Government agencies shall report IT security incidents to MSB/CERT-SE without undue delay.', description_nl: 'Myndigheter ska rapportera IT-säkerhetsincidenter till MSB/CERT-SE utan onödigt dröjsmål.', category: 'MSBFS 2020:7', subcategory: 'Rapportering', level: 'Bindande', iso_mapping: '5.24', implementation_guidance: 'Upprätta rutiner för IT-incidentrapportering till CERT-SE. Definiera vem som rapporterar och inom vilken tid.', verification_guidance: 'Kontrollera att rapporteringsrutiner finns och att ansvariga känner till dem.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
  { control_number: '2020:7-2', title: 'Incident classification criteria', title_nl: 'Klassificeringskriterier för incidenter', description: 'The agency shall classify IT incidents based on impact on confidentiality, integrity, and availability to determine reporting requirements.', description_nl: 'Myndigheten ska klassificera IT-incidenter baserat på påverkan på konfidentialitet, riktighet och tillgänglighet för att fastställa rapporteringskrav.', category: 'MSBFS 2020:7', subcategory: 'Klassificering', level: 'Bindande', iso_mapping: '5.25', implementation_guidance: 'Tillämpa CERT-SE:s klassificeringsmodell. Definiera tröskelvärden för rapporteringsplikt.', verification_guidance: 'Granska klassificeringsmodellen och kontrollera att den tillämpas vid incidenter.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
  { control_number: '2020:7-3', title: 'Initial incident report', title_nl: 'Första incidentrapport', description: 'An initial incident report shall be submitted to CERT-SE within 24 hours of incident detection.', description_nl: 'En första incidentrapport ska lämnas till CERT-SE inom 24 timmar efter att incidenten upptäckts.', category: 'MSBFS 2020:7', subcategory: 'Tidskrav', level: 'Bindande', iso_mapping: '5.26', implementation_guidance: 'Säkerställ att processen medger rapportering inom 24 timmar. Använd CERT-SE:s rapporteringsformulär.', verification_guidance: 'Kontrollera att rapporteringstider har hållits vid tidigare incidenter.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
  { control_number: '2020:7-4', title: 'Follow-up incident report', title_nl: 'Uppföljande incidentrapport', description: 'A follow-up report shall be submitted to CERT-SE within one month with root cause analysis and measures taken.', description_nl: 'En uppföljande rapport ska lämnas till CERT-SE inom en månad med grundorsaksanalys och vidtagna åtgärder.', category: 'MSBFS 2020:7', subcategory: 'Uppföljning', level: 'Bindande', iso_mapping: '5.27', implementation_guidance: 'Genomför grundorsaksanalys och dokumentera vidtagna åtgärder. Rapportera resultat till CERT-SE.', verification_guidance: 'Granska uppföljningsrapporter och kontrollera att de har lämnats inom tidsfristen.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
  { control_number: '2020:7-5', title: 'Incident reporting process documentation', title_nl: 'Dokumentation av rapporteringsprocess', description: 'The agency shall document its IT incident reporting process, including roles, escalation paths, and communication channels.', description_nl: 'Myndigheten ska dokumentera sin process för rapportering av IT-incidenter, inklusive roller, eskaleringsvägar och kommunikationskanaler.', category: 'MSBFS 2020:7', subcategory: 'Process', level: 'Bindande', iso_mapping: '5.24', implementation_guidance: 'Dokumentera incidentrapporteringsprocessen med tydliga steg, ansvariga och kontaktuppgifter.', verification_guidance: 'Kontrollera att processdokumentation finns och att den är känd av berörda.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
  { control_number: '2020:7-6', title: 'Cooperation with CERT-SE during incidents', title_nl: 'Samarbete med CERT-SE vid incidenter', description: 'The agency shall cooperate with CERT-SE during incident response and provide requested technical information.', description_nl: 'Myndigheten ska samarbeta med CERT-SE vid incidenthantering och tillhandahålla begärd teknisk information.', category: 'MSBFS 2020:7', subcategory: 'Samarbete', level: 'Bindande', iso_mapping: '5.5', implementation_guidance: 'Säkerställ att teknisk personal kan samarbeta med CERT-SE. Upprätta kontaktvägar för teknisk kommunikation.', verification_guidance: 'Kontrollera att kontaktuppgifter till CERT-SE finns dokumenterade och att samarbetet fungerar.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
  { control_number: '2020:7-7', title: 'Incident record keeping', title_nl: 'Dokumentation av incidenter', description: 'The agency shall maintain records of all IT security incidents regardless of whether they meet the reporting threshold.', description_nl: 'Myndigheten ska upprätthålla dokumentation av alla IT-säkerhetsincidenter oavsett om de når rapporteringströskeln.', category: 'MSBFS 2020:7', subcategory: 'Dokumentation', level: 'Bindande', iso_mapping: '5.28', implementation_guidance: 'Upprätta ett incidentregister. Logga alla incidenter med tidpunkt, beskrivning, klassificering och åtgärder.', verification_guidance: 'Granska incidentregistret och kontrollera att alla incidenter dokumenterats.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },

  // ── MSBFS 2020:6 Additional requirements ──────────────────────────────────
  { control_number: '2020:6-11', title: 'External audit requirement', title_nl: 'Krav på extern revision', description: 'The agency shall arrange for external review of its information security work at regular intervals.', description_nl: 'Myndigheten ska arrangera extern granskning av sitt informationssäkerhetsarbete med regelbundna intervall.', category: 'MSBFS 2020:6', subcategory: 'Revision', level: 'Bindande', iso_mapping: '5.35', implementation_guidance: 'Genomför extern revision av informationssäkerheten minst vart tredje år.', verification_guidance: 'Kontrollera att extern revision har genomförts och att rekommendationer följs.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-12', title: 'Asset inventory obligation', title_nl: 'Krav på tillgångsinventering', description: 'The agency shall maintain an inventory of all information assets relevant to security.', description_nl: 'Myndigheten ska upprätthålla en inventering av alla informationstillgångar som är relevanta för säkerheten.', category: 'MSBFS 2020:6', subcategory: 'Tillgångar', level: 'Bindande', iso_mapping: '5.9', implementation_guidance: 'Upprätta och underhåll ett register över informationstillgångar. Koppla tillgångar till ägare.', verification_guidance: 'Granska tillgångsregistret och kontrollera att det är aktuellt.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-13', title: 'Third-party access control', title_nl: 'Kontroll av tredjepartsåtkomst', description: 'Access by external parties to the agency information systems shall be controlled and monitored.', description_nl: 'Åtkomst av externa parter till myndighetens informationssystem ska kontrolleras och övervakas.', category: 'MSBFS 2020:6', subcategory: 'Tredjepartsåtkomst', level: 'Bindande', iso_mapping: '5.19', implementation_guidance: 'Upprätta avtal med tredjeparter som inkluderar säkerhetskrav. Begränsa och logga tredjepartsåtkomst.', verification_guidance: 'Kontrollera att tredjepartsavtal inkluderar säkerhetskrav och att åtkomst loggas.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-14', title: 'IT systems lifecycle security', title_nl: 'Säkerhet under IT-systems livscykel', description: 'Security shall be integrated into all phases of the IT system lifecycle, from procurement through decommissioning.', description_nl: 'Säkerhet ska integreras i alla faser av IT-systemens livscykel, från upphandling till avveckling.', category: 'MSBFS 2020:6', subcategory: 'Livscykel', level: 'Bindande', iso_mapping: '5.8', implementation_guidance: 'Inkludera säkerhetskrav vid upphandling. Genomför säkerhetsbedömning vid livscykelns alla faser.', verification_guidance: 'Kontrollera att säkerhet beaktas vid upphandling, drift och avveckling av system.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },
  { control_number: '2020:6-15', title: 'Management review of information security', title_nl: 'Ledningens genomgång av informationssäkerhet', description: 'Senior management shall review the information security status at planned intervals.', description_nl: 'Ledningen ska granska informationssäkerhetens status med planerade intervall.', category: 'MSBFS 2020:6', subcategory: 'Ledningsgenomgång', level: 'Bindande', iso_mapping: '5.1', implementation_guidance: 'Genomför ledningens genomgång av informationssäkerheten minst årligen. Dokumentera beslut och åtgärder.', verification_guidance: 'Kontrollera att ledningens genomgång genomförs och att protokoll finns.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/' },

  // ── MSBFS 2020:7 Additional requirements ──────────────────────────────────
  { control_number: '2020:7-8', title: 'Lessons learned from incidents', title_nl: 'Erfarenhetsåterföring från incidenter', description: 'The agency shall systematically collect and apply lessons learned from IT incidents to improve security.', description_nl: 'Myndigheten ska systematiskt samla in och tillämpa erfarenheter från IT-incidenter för att förbättra säkerheten.', category: 'MSBFS 2020:7', subcategory: 'Erfarenhetsåterföring', level: 'Bindande', iso_mapping: '5.27', implementation_guidance: 'Genomför post-incident-genomgångar. Dokumentera och sprid erfarenheter. Uppdatera rutiner baserat på lärdomar.', verification_guidance: 'Kontrollera att post-incident-genomgångar genomförs och att åtgärder vidtas.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
  { control_number: '2020:7-9', title: 'Incident communication to stakeholders', title_nl: 'Incidentkommunikation till intressenter', description: 'The agency shall have procedures for communicating with relevant stakeholders during and after IT incidents.', description_nl: 'Myndigheten ska ha rutiner för kommunikation med relevanta intressenter under och efter IT-incidenter.', category: 'MSBFS 2020:7', subcategory: 'Kommunikation', level: 'Bindande', iso_mapping: '5.26', implementation_guidance: 'Definiera intressenter och kommunikationskanaler för incidenter. Upprätta mallar för incidentkommunikation.', verification_guidance: 'Kontrollera att kommunikationsrutiner finns och har testats.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
  { control_number: '2020:7-10', title: 'Incident response testing', title_nl: 'Testning av incidenthantering', description: 'The agency shall regularly test its incident response capabilities through exercises.', description_nl: 'Myndigheten ska regelbundet testa sin incidenthanteringsförmåga genom övningar.', category: 'MSBFS 2020:7', subcategory: 'Övning', level: 'Bindande', iso_mapping: '5.24', implementation_guidance: 'Genomför incidenthanteringsövningar minst årligen. Inkludera tabletop-övningar och tekniska tester.', verification_guidance: 'Kontrollera att övningar genomförs och att resultat dokumenteras.', source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20207/' },
];

async function main(): Promise<void> {
  console.log('MSBFS 2020 Ingestion Script');
  console.log('============================');
  mkdirSync(DATA_DIR, { recursive: true });
  console.log(`  ${controls.length} requirements.`);

  const output = {
    framework: {
      id: 'msbfs-2020',
      name: 'MSB Regulations on Information Security (MSBFS 2020:6 and 2020:7)',
      name_nl: 'MSB:s föreskrifter om informationssäkerhet (MSBFS 2020:6 och 2020:7)',
      issuing_body: 'Myndigheten för samhällsskydd och beredskap (MSB)',
      version: '2020',
      effective_date: '2020-10-01',
      scope: 'Legally binding regulations for Swedish government agencies on systematic information security work (MSBFS 2020:6) and IT incident reporting (MSBFS 2020:7)',
      scope_sectors: ['government'],
      structure_description: 'Two regulations: MSBFS 2020:6 covers systematic information security requirements (10 articles). MSBFS 2020:7 covers IT incident reporting to CERT-SE (7 articles).',
      source_url: 'https://www.msb.se/sv/regler/gallande-regler/krisberedskap-och-civilt-forsvar/msbfs-20206/',
      license: 'Swedish government regulation (public)',
      language: 'sv',
    },
    controls,
    metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
  };

  writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
  console.log(`Output written to ${OUTPUT_FILE} (${(readFileSync(OUTPUT_FILE).length / 1024).toFixed(1)} KB)`);
}

main().catch((err) => { console.error('Fatal error:', err); process.exit(1); });
